### ISSUE TITLE
di.se

### ISSUE THREAD

**Issue by Tobbe** [bogachenko/fuckfuckadblock#1]
### Basic information

**Check the link:** `https://www.di.se/`

**Category:**  Anti-adblock

**Reported from:** Sweden

**Filter lists:**
[x] Auto-update filter lists 
[x] Parse and enforce cosmetic filters
[  ] Ignore generic cosmetic filters

My filters​​​​​ 1 used out of 1​​​​

Built-in (5/7)
uBlock filters ​​​​​16,318 used out of 16,335​​​​
uBlock filters – Badware risks ​​​​​127 used out of 127​​​​
uBlock filters – Privacy​​​​​ 158 used out of 159​​​​
uBlock filters – Resource abuse ​​​​​190 used out of 190​​​​
uBlock filters – Unbreak​​​​​ 928 used out of 930​​​​

Ads (1/4)
EasyList​​​​​ 92,695 used out of 93,007​​​​

Privacy (1/3)
EasyPrivacy ​​​​​17,081 used out of 17,172
​​​​
Malware domains (2/4)
Malware Domain List​​​​​ 1,090 used out of 1,105​​​​
Malware domains​​​​​ 26,901 used out of 26,901​​​​
Annoyances (0/6)
Multipurpose (1/4)
Peter Lowe’s Ad and tracking server list ​​​​​2,965 used out of 2,966​​​​
Regions, languages (0/37)

Custom (2/2)
AakList (Anti-Adblock Killer)​​​​​ 2,115 used out of 2,178​​​​
Fuck Fuckadblock​​​​​ 1,068 used out of 1,536​​​​

### User environment
**Browser:** Chrome

**Extension:** uBlock Origin v1.19.2

### Additional message

The popup appears after a while, and you have to close it (not just remove the element). After you have closed it, it will appear again after a while.

The title of the popup is "Det verkar som du använder en annonsblockerare"

Is it possible to remove this popup?

**Comment by bogachenko** [comment]
Update the filter and try agane

***
BTW - this is not inline code

>Check the link:
Dagens Industri

inline code is made like this 

```
`di.se`
```
and it will be like this
`di.se`

**Comment by Tobbe** [comment]
Works great! Thanks for fixing 👍
