### ISSUE TITLE
mp4upload.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [bogachenko/fuckfuckadblock#10]
broken player

**Comment by bogachenko** [comment]
@smed79 Hi, your rule is blocking the player, can you delete?
`*$first-party,subdocument,domain=mp4upload.com`

Test here `https://www.mp4upload.com/wzpz9od3qagq`

**Comment by smed79** [comment]
Fixed https://hg.adblockplus.org/listefr/rev/61bd5caa7573

Thank you.
