### ISSUE TITLE
serpadres.es

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#101]
### Basic information

**Check the link:** `https://www.serpadres.es/`
**Category:** Anti-adblock

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Please fix.
Also, tag AdGuard: https://github.com/AdguardTeam/AdguardFilters/issues/71388

**Comment by bogachenko** [comment]
I saw this case but could not reproduce it. And I still can't.

**Comment by bogachenko** [comment]
The trigger comes from the adservice.google.es domain, but [I added a rule](https://github.com/bogachenko/fuckfuckadblock/commit/6d0ebeea2f0f1c5235552f8c69928b22856e249b) for it long ago and antiadblock does not trigger with this rule.

**Comment by bogachenko** [comment]
Damn it, the problem is in the platform. The rule works on the ADG extension, but not on the ADG program. Please take a look @ameshkov, why does it work like this?

**Comment by ameshkov** [comment]
@bogachenko there's a possibility that the query is blocked on the DNS level, in this case it won't get to AdGuard -> can't be replaced.

**Comment by wout-codes** [comment]
Maybe some kind of bug. Who is Ameshkov by the way? Is he the Software Engineer who created the AdGuard?

**Comment by wout-codes** [comment]
@bogachenko I think you have fixed it. Not showing anymore to disable AdGuard. 
Thank you!

**Comment by bogachenko** [comment]
> Who is Ameshkov by the way? Is he the Software Engineer who created the AdGuard?

@wout-codes This is A Man, he is a technical director at Adguard.

@ameshkov Is it like a speed race?

**Comment by wout-codes** [comment]
@ameshkov What happened to AdGuard Filters Developer? There are almost about 700 issues that aren't solved.

**Comment by bogachenko** [comment]
new year holidays, people with families

**Comment by wout-codes** [comment]
> new year holidays, people with families

I see. Filters gonna get outdated if they don't get back soon.

**Comment by ameshkov** [comment]
@wout-codes some of them have long holidays (until 11th of January) so the team is not fully operational :)

> @ameshkov Is it like a speed race?

Well, it's just an idea. 

I tried reproducing the issue with AG for Mac, but the rule (`adservice.....$redirect=`) works fine for me.
However, when DNS-level blocking is enabled, `adservice.google.es` points to `127.0.0.1` so it simply is not filtered by AG.

**Comment by wout-codes** [comment]
@ameshkov I have DNS - level blocking. Not causing anymore Anti Adblock pop up in the website.

**Comment by ameshkov** [comment]
@bogachenko what do you think about having a scriptlet to prevent `fetch` or replacing `Request`?

We could handle this kind of stuff easily:
```
                var n = new Request("https://adservice.google.es/adsid/integrator.js",{
                    method: "HEAD",
                    mode: "no-cors"
                });
                fetch(n).then(function(t) {
                    e(!1)
                }).catch(function(e) {
                    t(!0)
                })
```

I remember @uBlock-user experimented with it already. @uBlock-user could you please give some examples where this could be useful? If there're many, we could add such a scriptlet to the standard AG scriptlets library.

**Comment by bogachenko** [comment]
>when DNS-level blocking is enabled

@ameshkov I have disabled DNS blocking in the program, but I have the ADGH program installed (it works in the background, I forgot about it, it works and works, it blocks something) maybe the problem is in this. I will not check, I will take my word for it, especially since I do not have adservice.google.es in the logger, so you are right.

**Comment by bogachenko** [comment]
>what do you think about having a scriptlet to prevent fetch or replacing Request?

I don't know yet, I'm coping with blocking by improvised means, as long as it works. Deliver, i'll figure it out, I'm always happy with the update.

**Comment by uBlock-user** [comment]
@ameshkov Thanks for pinging me. `no-fetch-if` is currently used in uBO for 4 sites, but aside from that, I have found few cases on my own -- 

- hindustantimes.com
- new.lewd.ninja
- livemint.com
- animefever.tv

All anti-adblock issues ofcourse.

PS -- This is not a conclusive list and shouldn't be seen as such.

**Comment by uBlock-user** [comment]
@ameshkov Thanks for pinging me. `no-fetch-if` is currently used in uBO for 4 sites, but aside from that, I have found other cases on my own -- 

- new.lewd.ninja
- animefever.tv
- mdpDeBlocker anti-adblock
- antiadblock where a XHR request is fired to a blocked domain-url

All anti-adblock issues ofcourse.

PS -- This is not a conclusive list and shouldn't be seen as such.

**Comment by uBlock-user** [comment]
This case in uBO is fixed with `*$xmlhttprequest,redirect-rule=nooptext,domain=serpadres.es` so you will not be able to reproduce if you're using uBO.
