### ISSUE TITLE
kizi.com

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#102]
### Basic information

**Check the link:** `https://kizi.com/games/wheely-8`
**Category:** Anti-adblock

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Scroll down after going to that website. It says AdGuard detected. 
Fix it.
Tag Adguard too: https://github.com/AdguardTeam/AdguardFilters/issues/71283#issuecomment-753418400

**Comment by wout-codes** [comment]
Not fixed. Still detecting AdGuard. Try writing filters like the before issue.

**Comment by bogachenko** [comment]
No matter how hard I try, I cannot reproduce the problem and the sheets of that report do not help. Everything is clean for me.

**Comment by wout-codes** [comment]
Nevermind then.
