### ISSUE TITLE
ctrlv.link

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#103]
Link: `https://ctrlv.link/UhwC`

Browser: Google Chrome
Ad-Blocker: AdGuard for Windows

AdGuard was detected. (Anti AdBlock Script)

Tag AdGuard too: https://github.com/AdguardTeam/AdguardFilters/issues/70979

**Comment by bogachenko** [comment]
Install the ADG extension (along with the program), there again DNS blocking works.

**Comment by wout-codes** [comment]
@bogachenko Which AdGuard Extension? Assistant or the AdBlocker?

**Comment by bogachenko** [comment]
I have both installed, but I meant the first one.

**Comment by wout-codes** [comment]
> I have both installed, but I meant the first one.

If I need AdGuard Ad-Blocker extension, what is the point of having AdGuard for Windows? I have the Assistant by the way. Also, in tests, I have seen that AdGuard Adblocker extension blocks a lot more than AdGuard for Windows.

**Comment by bogachenko** [comment]
The ADGW program works with more complex rules, ADGE will not be able to fulfill them due to restrictions, for example, the browser itself.
But each program has its pros and cons, DNS blocking is both a plus and a minus.

**Comment by bogachenko** [comment]
I use a bundle of ADGE and ADGW, for example, when I use VPN https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported-products you can read this article in the chapter "VPN programs and Adguard"

**Comment by wout-codes** [comment]
I see. Yes, I agree Browser Extensions are strictly limited by Browser's API.

**Comment by wout-codes** [comment]
Not fixed. Still telling me to disable AdGuard.

**Comment by bogachenko** [comment]
I cannot reproduce, update the list, clear the cache and try again (can try in another browser).

**Comment by wout-codes** [comment]
Also, check AdGuard issues for Anti AdBlock and Pop ups. It will help your project.

**Comment by wout-codes** [comment]
> I cannot reproduce, update the list, clear the cache and try again (can try in another browser).

Maybe you can write new rules like the before issue.

**Comment by wout-codes** [comment]
Working thank you
