### ISSUE TITLE
memoryhackers.org

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#109]
### Basic information

**Check the link:** `https://memoryhackers.org/`
**Category:** Breakage

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Refer: https://github.com/AdguardTeam/AdguardFilters/issues/71634
A fix is appreciated.

**Comment by wout-codes** [comment]
How about this @bogachenko ?

**Comment by wout-codes** [comment]
New script that tell us to disable adblocker. AdGuard devs fixed this 3 times, and now they came up with another script.

**Comment by bogachenko** [comment]
>New script that tell us to disable adblocker. AdGuard devs fixed this 3 time

I know, I'm thinking of adding it here https://github.com/bogachenko/fuckfuckadblock/wiki/Unsupported-sites
haven't decided yet

**Comment by wout-codes** [comment]
You can remove this from the list of the wiki: washingtonpost.com. I do not see any pop ups or anti adblock

**Comment by bogachenko** [comment]
This is at the moment, they are quickly changing the script.

**Comment by wout-codes** [comment]
Yep. all adblockers might fail in that website just like twitch. Did you find a fix for Twitch ads and Anti AdBlock?

**Comment by llacb47** [comment]
@bogachenko I haven't seen wapo updating their anti-adblock recently. When was the last time they changed it?

**Comment by wout-codes** [comment]
I think 2019.

**Comment by bogachenko** [comment]
@llacb47 https://github.com/uBlockOrigin/uAssets/pull/7510

I do not follow them, when I added it there, they followed and changed.

**Comment by wout-codes** [comment]
Yes, they are like that. I have seen them doing those things in AdGuard too. When the devs do not response to some issues, they quickly find the problem that the issue describes then fixes it. Quite unfair.

**Comment by wout-codes** [comment]
Also, which one do you prefer, AdGuard Tracking Protection Filter or EasyPrivacy?

**Comment by bogachenko** [comment]
First, because I use ADG as the main blocker.

**Comment by bogachenko** [comment]
And please stop using GitHub as YouTube comments. If you want to ask something, write to the mail - `bogachenkove@gmail.com` or contact telegram `@bogachenkove`.

**Comment by wout-codes** [comment]
Ok, Sure

**Comment by bogachenko** [comment]
They updated the script again. Fuck they go. I added this site to https://github.com/bogachenko/fuckfuckadblock/wiki/Unsupported-sites

**Comment by wout-codes** [comment]
I see.
