### ISSUE TITLE
Filter question

### ISSUE THREAD

**Issue by llacb47** [bogachenko/fuckfuckadblock#11]
What is the need for these filters?
Line 143: `#@#.adsbygoogle` (Results in big ugly spaces - this rule is probably to get around anti-adblock but we have `generichide` for a reason)

Lines 350-351: (Disqus has trackers - they should not be globally whitelisted)
```
@@||disqus.com^
@@||disquscdn.com^
```
Line 352: `@@||cdnjs.cloudflare.com^$third-party` I think this is for `https://cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js` but the filter should be more specific, some ads scripts are served through there as well.

**Comment by llacb47** [comment]
To follow up, what is the purpose of these filters?
Lines 141-169:
```
#@##banner_ad
#@##sponsored-ad
#@#.afs_ads
#@#.ga
#@#.ads1x1
#@#.pub_300x250
#@#.pub_300x250m
#@#.pub_728x90
#@#.text-ad
#@#.textAd
#@#.text_ad
#@#.text_ads
#@#.text-ads
#@#.text-ad-links
#@#.ad-unit
#@##ad_test
#@#.img_ad
#@#.ad_300x250
#@#.act-ad-container
#@##adchecker
#@#.adchecker
#@#.pub300x250
#@#.ad300-250
#@#.text-ad-link
#@#.adsbox
#@#.adsense
#@#.adslot
#@#.adspot
#@#*
```

If they are to evade anti-adblock, this in my opinion is a bad way to do it. uAssets already has per-site whitelisting of `generichide` for the same purpose.

**Comment by bogachenko** [comment]
_This morning I left for work early, it was not possible to answer (in detail). I'm writing now._


>If they are to evade anti-adblock, this is IMO a bad way to do it.

and

>To follow up, what is the purpose of these filters?

I do not see anything bad, it helps well for sites-1day-live. They all have the same tricks (Engine,
trap-cosmetic filters), sometimes it is useful, sometimes not.

>Results in big ugly spaces - this rule is probably to get around anti-adblock

In my extension, my cosmetic filters are disabled, everything is exactly on cosmetic advertising. You can also block in other ways. 

>uAssets already has per-site whitelisting of generichide cosmetic filters for the same purpose.

Cool. I am happy for them. But this repository is not uAssets and this repository for 2 extensions.

Problems do not create these filters, if I am not right, give an example. Please.

**Comment by llacb47** [comment]
Oh, I did not know this repository was made for another extension.

**Comment by llacb47** [comment]
Line 353 `@@||cdnjs.cloudflare.com/*/fuckadblock.min.js$third-party` could probably be changed to `@@||cdnjs.cloudflare.com/*/fuckadblock.$script,third-party` just in case site doesn't use `min` version.
