### ISSUE TITLE
mobilityarena.com

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#114]
### Basic information

**Check the link:** `https://mobilityarena.com/`
**Category:** Anti-adblock

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows.

### Additional message
Please fix.

**Comment by wout-codes** [comment]
Not fixed. Still telling me to disable AdBlocker.

**Comment by wout-codes** [comment]
Not fixed. Still telling me to disable AdBlocker.

**Comment by bogachenko** [comment]
With filters set by default and with `Fuck Fuckadblock` I can't reproduce the problem.

**Comment by wout-codes** [comment]
Then where?

**Comment by bogachenko** [comment]
I don't see it in the program or in the extension. Checked on Firefox, Opera, Egde.

**Comment by wout-codes** [comment]
Do you use Google Chrome? It blocked the script in Edge without the AdGuard extension.

**Comment by bogachenko** [comment]
No, I don't use google chrome. But I think the problem will not be repeated there, the opera and the eagle with chrome have the same engine, no on them = no on it, so I think.

**Comment by wout-codes** [comment]
Ok I will check. This issue has been fixed.
