### ISSUE TITLE
kimcartoon.to

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#115]
### Basic information

**Check the link:** `https://kimcartoon.to/`
**Category:** Popup

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Anti AdBlock script has been blocked, only pop-ups.

**Comment by bogachenko** [comment]
How to reproduce?

**Comment by wout-codes** [comment]
Disable Ad-Block then see

**Comment by bogachenko** [comment]
_Disable adblock = take off pants and stand in the doggystyle pose._ 

Where are the sleeping windows, on the site itself or in (frame) in the video?

**Comment by wout-codes** [comment]
Frame

> _Disable adblock = take off pants and stand in the doggystyle pose._ (haha) Where did you get this?
> 
> Where are the pop-ups located, on the site itself or in (frame) in the video?

**Comment by wout-codes** [comment]
Isn't this a code to Tell us to Disable AdBlock?
<div id="adbWarnContainer" class="adbWarnContainer">
        <div class="background"></div>
        <div class="content">
            <p style="color: #ff0000; font-size: 20px;">PLEASE DISABLE ADBLOCK</p>
            <p><img src="/Content/images/adb.png"></p>
            <p>Adblock extensions will affect to a several website features, the VIDEO might to be UNPLAYABLE because of that. Please turn off for best experience!</p>
            <p><a id="closeAdbWarn" href="javascript:void(0);" class="aButton" style="width: 140px; padding: 5px;">OK! I understood</a></p>
        </div>
    </div>

**Comment by bogachenko** [comment]
I can't reproduce it. Give the full link to the problem page, which player server is playing the problem?

**Comment by wout-codes** [comment]
Here: https://kimcartoon.to/Cartoon/100-Wolf/Movie?id=97398

Press on the video you will see it. Also, disable AdBlocker if you have.

**Comment by wout-codes** [comment]
Any idea @bogachenko ?
