### ISSUE TITLE
watch-serieshd.cc

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#125]
### Basic information

**Check the link:** `https://watch-serieshd.cc/episodes/star-trek-enterprise-season-3-episode-6/`
**Category:** Popup

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Please fix.

**Comment by bogachenko** [comment]
>Please fix.

For heaven's sake, stop writing obvious things (in all your posts). The very fact that you are creating an issue here is already a veiled request to fix it. This field is created as **an additional one**, that's why i called it like that.

For example, I don't know where exactly the pop-up window is, on the site itself or in the frame? And whatever I ask such questions, you or someone else writes there about the steps for reproduction, or some other valuable information.
***
I can't reproduce the problem.

**Comment by wout-codes** [comment]
Hi, sorry. Click on the video you will see a pop up.

**Comment by wout-codes** [comment]
Hi, sorry @bogachenko . Click on the video you will see a pop up.

**Comment by wout-codes** [comment]
@bogachenko ?

**Comment by bogachenko** [comment]
What kind of player? A domain-names of advertising pop-ups are different, what are they?

**Comment by wout-codes** [comment]
Just click on the video, you will see popups.

**Comment by bogachenko** [comment]
>Just click on the video, you will see popups.

https://user-images.githubusercontent.com/8535285/103989356-b3bf0b00-51e3-11eb-9bd1-d36594ab3280.mp4

**Comment by wout-codes** [comment]
> > Just click on the video, you will see popups.
> 
>  Project002.mp4

Interesting. AdGuard Windows for me has problems I think.

**Comment by bogachenko** [comment]
Does he even work ? Come here https://checkadblock.ru/

**Comment by bogachenko** [comment]
Also, do you see such a request in the browser logger?
![1](https://user-images.githubusercontent.com/8535285/103990663-b6bafb00-51e5-11eb-843e-300c09e79873.jpg)

**Comment by wout-codes** [comment]
85 баллов из 100 = 85 out of 100

**Comment by wout-codes** [comment]
> Also, do you see such a request in the browser logger?
> https://user-images.githubusercontent.com/8535285/103990663-b6bafb00-51e5-11eb-843e-300c09e79873.jpg

How to check?

**Comment by wout-codes** [comment]
> Does he even work ? Come here https://checkadblock.ru/

100/100

**Comment by wout-codes** [comment]
> Also, do you see such a request in the browser logger?
> https://user-images.githubusercontent.com/8535285/103990663-b6bafb00-51e5-11eb-843e-300c09e79873.jpg

Nope.

**Comment by wout-codes** [comment]
I think I will move to the extension.

**Comment by bogachenko** [comment]
Go to the problematic site (I showed https://google.com as an example) use the keyboard shortcut to open the Developer Tools <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> Open the "Console" tab and search for "adguard"

**Comment by bogachenko** [comment]
> 
> 
> > Also, do you see such a request in the browser logger?
> > https://user-images.githubusercontent.com/8535285/103990663-b6bafb00-51e5-11eb-843e-300c09e79873.jpg
> 
> Nope.

Did you do everything right?

**Comment by wout-codes** [comment]
Yes

> > > Also, do you see such a request in the browser logger?
> > > https://user-images.githubusercontent.com/8535285/103990663-b6bafb00-51e5-11eb-843e-300c09e79873.jpg
> > 
> > 
> > Nope.
> 
> Did you do everything right?

**Comment by wout-codes** [comment]
Can you export a copy of your AdGuard Settings? I will use yours then check again.

**Comment by bogachenko** [comment]
You can just reset to factory settings.

**Comment by wout-codes** [comment]
Okay done. Still not working.

**Comment by bogachenko** [comment]
Do you see it in the request log (Network tab)?
https://user-images.githubusercontent.com/8535285/103994797-9e4ddf00-51eb-11eb-9453-20b6e345ccff.jpg

**Comment by wout-codes** [comment]
> Do you see it in the request log (Network tab)?
> https://user-images.githubusercontent.com/8535285/103994797-9e4ddf00-51eb-11eb-9453-20b6e345ccff.jpg

Yes I see.

**Comment by bogachenko** [comment]
Сука блять. i got it, add to my filters `|https://$script,3p,domain=dood.to,badfilter`

**Comment by wout-codes** [comment]
Which site?

**Comment by bogachenko** [comment]
You reported the site watch-serieshd.cc on this site the dood.to frame is installed, and on this frame you got pop-up windows. Why? Because you are subscribed to Easylist, there is a rule that blocks third-party scripts on this site. One of the third party sites was local.adguard.org, it is needed to block content on the page when you use the program. Without it, the program will not work, the script does not work = the program does not work.

If you add the rule to my filters, pop-ups should disappear

**Comment by wout-codes** [comment]
Oh should I remove EasyList and EasyPrivacy?

**Comment by bogachenko** [comment]
This is not necessary, they help, but sometimes they falsely work. Do you have a website, do you have popups?

**Comment by wout-codes** [comment]
Yes, yes, you are right. I removed EasyList and EasyPrivacy. Everything works properly.

**Comment by bogachenko** [comment]
You can repost about this case to the Adguard repository, they can fix it, and you will remove my fixing filter from the "My filters" tab
