### ISSUE TITLE
go.minilinks.in

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#126]
### Basic information

**Check the link:** https://go.minilinks.in/jH6M
**Category:** Breakage

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard Windows

### Additional message
Please fix. Cookie notices, placeholders fake links appear when using this list.

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues

**Comment by wout-codes** [comment]
I see, not perfect.
