### ISSUE TITLE
openshot.org

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#132]
### Basic information

**Check the link:** `https://www.openshot.org/`
**Category:** Anti-adblock

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Go to that website, it will tell you to disable your AdBlocker.

**Comment by bogachenko** [comment]
```
Not <code> but `

eg `https://google.com`
```

**Comment by wout-codes** [comment]
> ```
> Not <code> but `
> 
> eg `https://google.com`
> ```

Thanks for the tip.
