### ISSUE TITLE
mylink.st

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#134]
### Basic information

**Check the link:** ` https://mylink.st/OqQzF7J `
**Category:** Anti-adblock

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard Extension

### Additional message
When your filter list is enabled, AdGuard detected. When your filter list is disabled, AdGuard is not detected.

**Comment by wout-codes** [comment]
Why? Can't be fixed? Writing normal rules like before would work.

**Comment by bogachenko** [comment]
I have no anti-adblock. There is nothing to fix. I will look again tomorrow.

**Comment by wout-codes** [comment]
Hi @bogachenko,
When your filter list is enabled, AdGuard detected. When your filter list is disabled, AdGuard is not detected.
