### ISSUE TITLE
calculate.plus

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#140]
### Basic information

**Check the link:** `https://calculate.plus/es/categorias/area/convertir/5/km2/en/hm2`
**Category:** Anti-adblock

### User environment

**Browser:** Opera Browser
**Extension or program:** AdGuard for Windows

### Additional message
Tells me to disable the Ad-Blocker.

**Comment by bogachenko** [comment]
Already fixed yesterday in this commit https://github.com/bogachenko/fuckfuckadblock/commit/3e438d8083c40976bfa0a7aa47afb706e0960d3b
Check if Opera's native ad blocker is enabled, if so, disable it.

**Comment by wout-codes** [comment]
> 
> 
> Already fixed yesterday in this commit [3e438d8](https://github.com/bogachenko/fuckfuckadblock/commit/3e438d8083c40976bfa0a7aa47afb706e0960d3b)
> Check if Opera's native ad blocker is enabled, if so, disable it.

I tried. Your filter for this website doesn't work in any browsers. I also tried with AdGuard Extension, still it didn't work.
