### ISSUE TITLE
kitguru.net

### ISSUE THREAD

**Issue by brian6932** [bogachenko/fuckfuckadblock#144]
### Basic information

**Check the link:** `https://www.kitguru.net/`
**Category:** Anti-adblock
**Reported from:** United States

### User environment

**Browser:** Chromium
**Extension or program:**  uBlock Origin

### Additional message
You can close it, but it's pretty annoying

This worked for me under My filters (in uBO):
`www.kitguru.net###ljcomwpb-blanket > div`
`www.kitguru.net###ljcomwpb-blanket`

**Comment by bogachenko** [comment]
Please do not upload images until I ask you to.
