### ISSUE TITLE
reddit.streamsc.com

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#147]
### Basic information

**Check the link:**  `https://reddit.streamsc.com/sheffield-united-vs-tottenham-hotspur-live-stream/`
**Category:**  Anti-adblock & Pop-up
**Reported from:**  Singapore

### User environment

**Browser:** Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (64-bit)
**Extension or program:** uBlock Origin

### Additional message

ADBLOCK DETECTED
Unfortunately AdBlock might cause a bad affect on displaying content of this website. Please, deactivate it.

**Comment by bogachenko** [comment]
@rigaz29 Fixed only antiadblock. Pop-up windows I can not reproduce.
