### ISSUE TITLE
komputerswiat.pl

### ISSUE THREAD

**Issue by Barticf** [bogachenko/fuckfuckadblock#148]
### Basic information

**Check the link:** `https://www.komputerswiat.pl/recenzje/sprzet/komponenty-pc/samsung-870-evo-1-tb-test-najnowszego-ssd-ze-zlaczem-sata/kz5ve86?srcc=null#test-samsunga-870-evo-1-tb-testy-w-benchmarkach-syntetycznych`
**Category:** Breakage
**Reported from:** Poland

### User environment

**Browser:** Firefox
**Extension or program:** uBlock

### Additional message
When Fuck Fuckadblock list is on there is only few lines of content in website
There is same problem when Fanboy’s Enhanced Tracking List is on. Maybe you can do something with it ?

**Comment by bogachenko** [comment]
cc @ryanbr `@@||tinypass.com^$third-party,domain=komputerswiat.pl`
