### ISSUE TITLE
tsgtv.net

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#149]
### Basic information

**Check the link:**  `http://tsgtv.net/channel2/`
**Category:**  Anti-adblock, Pop-up
**Reported from:**  54.251.72.180

### User environment

**Browser:** Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
**Extension or program:**  uBlock Origin v1.32.4 

### Additional message
Hello there!
We make our revenue through ads. So please disable your adblocker
I have disabled the adblocker. Let me watch now.

**Comment by bogachenko** [comment]
Check it should work, if not write here.

>Reported from: 54.251.72.180

Use words, not ip. (eg. Australia, United States of America, France)
