### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by Barticf** [bogachenko/fuckfuckadblock#150]
### Basic information

**Check the link:** `https://www.polsatnews.pl/wiadomosc/2021-01-28/nie-zyje-ryszard-kotys-aktor-zmarl-po-ciezkiej-chorobie/`
**Category:** Anti-adblock
**Reported from:** Poland

### User environment

**Browser:** Firefox
**Extension or program:** uBlock

### Additional message
When Fuck Fuckadblock list is turned on

**Comment by bogachenko** [comment]
I have problems with this site, persistent errors with video playback, can you check and write.

**Comment by Barticf** [comment]
@bogachenko I added manual to ublock `@@||stat24.com/ad.xml$xmlhttprequest` but still I get info about adblock.
![obraz](https://user-images.githubusercontent.com/32641928/106250656-3c91fb00-6214-11eb-8369-a2c1f35b8897.png)
![obraz](https://user-images.githubusercontent.com/32641928/106250679-4582cc80-6214-11eb-95f5-1f9611cf165d.png)
![obraz](https://user-images.githubusercontent.com/32641928/106250707-4d427100-6214-11eb-952a-eb00916dce4a.png)
![obraz](https://user-images.githubusercontent.com/32641928/106250719-529fbb80-6214-11eb-8df0-8f27b20d4e10.png)

**Comment by bogachenko** [comment]
This rule `@@||stat24.com/ad.xml$xmlhttprequest` will not work because the previous rule contains an `important` flag `||stat24.com/ad.xml$xmlhttprequest,redirect=nooptext,important`

You need not add, but update.

**Comment by krystian3w** [comment]
Also wait ~10 minutes after commited updated version (glitch in `raw.github.com` cache).

Sometimes help: https://github.com/gorhill/uBlock/wiki/Advanced-settings#updateassetbypassbrowsercache

**Comment by Barticf** [comment]
@bogachenko ![obraz](https://user-images.githubusercontent.com/32641928/112206809-a3310500-8c16-11eb-831a-a222edde6a4b.png)
