### ISSUE TITLE
Failed, not a valid filter list

### ISSUE THREAD

**Issue by ObsessedHacker** [bogachenko/fuckfuckadblock#153]
### Basic information

**Check the link:** https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt&title=Fuck%20Fuckadblock
**Category:** Subscribe

### User environment

**Browser:** Google Chrome is up to date
Version 88.0.4324.146 (Official Build) (64-bit)
**Extension or program:** https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom Version 4.27.0

### Additional message
Error: Failed, not a valid filter list
![Screenshot](https://user-images.githubusercontent.com/13978119/106836689-4c8d5d00-66a2-11eb-912b-e45431036280.png)

**Comment by bogachenko** [comment]
Adblock is not supported, you can read why [here](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported-products).

[Support is provided only for extension 2](https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock), for [uBlock Origin](https://github.com/gorhill/uBlock) and [Adguard](https://adguard.com/) (and their forks).

Install **ONE of these extensions** to use my list. How to subscribe to uBlock Origin or Adguard read [here](https://github.com/bogachenko/fuckfuckadblock/wiki/Installation-instruction#article-in-english-language).
