### ISSUE TITLE
diariodegoias.com.br

### ISSUE THREAD

**Issue by pintassilgo** [bogachenko/fuckfuckadblock#155]
### Basic information

**Check the link:** `https://diariodegoias.com.br/goiania-tem-mais-um-caso-de-falha-na-aplicacao-da-vacina-veja/`
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:** Firefox
**Extension or program:** uBO in medium mode (3rd party scripts disabled)

### Additional message

Two filters I got to bypass this antiadblock:
`diariodegoias.com.br##^script:has-text(tags.premiumads.com.br/ads)`
`diariodegoias.com.br##+js(acis, onload)`

I think the first one is a little cheaper (more efficient).

It would be great to have a single filter to unbreak every site using that antiadblock (premiumads.com.br), but I don't know if it's possible. I tried just `##^script:has-text(tags.premiumads.com.br/ads)`, but it doesn't work. **Edit:** I think I got it:
`||tags.premiumads.com.br/$script,redirect=noop.js`

**Comment by bogachenko** [comment]
You just need to add this script to the whitelist and there will be no anti-adblock (and allow using third-party scripts here).
`https://tags.premiumads.com.br/ads/advertisement.js`

I have already added it to the white list using a regular expression (a hundred years ago)
https://github.com/bogachenko/fuckfuckadblock/blob/df53f5b6972b61b9774d2a37350d95333709fd7e/fuckfuckadblock.txt#L431

The rule works and there is nothing else to add, they only clutter up the list, making it bigger.
