### ISSUE TITLE
redtube.com & pornhub.com

### ISSUE THREAD

**Issue by JonasNo** [bogachenko/fuckfuckadblock#156]
### Basic information

**Check the link:** `https://www.redtube.com/2405206` `https://www.pornhub.com/view_video.php?viewkey=ph59a29984b4690`
**Category:** Breakage
**Reported from:** Sweden

### User environment

**Browser:** Chrome stable
**Extension or program:**  uBlock Origin

### Additional message
When EasyList `https://forums.lanik.us/` is used with Fuck Fuckadblock the video is stuck at loading.

**Comment by bogachenko** [comment]
Strong theme name.
I cannot reproduce the problem. Tried it on 3 different browsers, Firefox, Opera, Edge. Nothing. Everything is reproduced without the slightest freezes/breakdowns.

Try this: https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#before-sending-a-report
If that doesn't help, go to the logger and see which scriptlet on MY list breaks the above sites. 8 scriptlets for each of the above sites.

**Comment by JonasNo** [comment]
Using a completely new profile, all Chrome stable settings default. Only uBO installed & default settings.
Default subscriptions are:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
SWE: Frellwit's Swedish Filter 

Imported subscription:
Fuck Fuckadblock

On redtube the issue remains. On pornhub there is no issue. Chrome Canary & Firfox browser with same results.
On Firefox Developer browser, redtube have the same issue. On pornhub I get the message "No valid sources are avaliable for this video."

This is the link to fuck fuckadblock I use:
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt

The logger:
![uBO logger from redtube link - Chrome stable](https://user-images.githubusercontent.com/770975/108595149-981c5800-737e-11eb-887d-123951daf4d0.PNG)
![uBO logger from redtube link - Chrome stable - part 2](https://user-images.githubusercontent.com/770975/108595155-9e123900-737e-11eb-8cb6-4e80e3004f9a.PNG)

**Comment by bogachenko** [comment]
Are you sure that the problem is in my list, if you unsubscribe from it and check again - the problem will go away?
