### ISSUE TITLE
9anime comments breakage

### ISSUE THREAD

**Issue by distren** [bogachenko/fuckfuckadblock#16]
### Basic information

**Check the link:** `https://www2.9anime.nl/watch/cardfight-vanguard-shinemon-arc.4nlx/0kqq39`
**Category:** breakage
**Reported from:** US
**Filter lists:** uBO default + this one

### User environment
**Browser:** Firefox 70
**Extension:** uBO 1.21.2

### Additional message

Scroll down and there are no comments.

I think it is this CSP rule blocking the disqus domain: https://github.com/bogachenko/fuckfuckadblock/blob/1ba138ddfb41844d95080a60f4a27d040cf7ac25/fuckfuckadblock.txt#L216

As mentioned in https://github.com/bogachenko/fuckfuckadblock/issues/11#issue-474688794 Disqus indeed has trackers, so it should not be whitelisted (preventing other lists from blocking it), but FFA is an ad/popup list not a privacy list so I don't think Disqus should be actively blocked either.

On an unrelated question, how does this list compare to https://github.com/jspenguin2017/uBlockProtector ? Nano Defender seems to have more people maintaining it, and this has effort split maintaining the AdGuard filters, so it would seem Nano Defender would be better...

**Comment by bogachenko** [comment]
>As mentioned in #11 (comment) Disqus indeed has trackers, so it should not be whitelisted (preventing other lists from blocking it)

The rule in this 11-ticket that allowed Disqus by default in my list, I added by mistake.

>but FFA is an ad/popup list not a privacy list so I don't think Disqus should be actively blocked either.

When compiling the CSP rules in the first place, I took into account my interests. On pirated sites, I do not read comments at all, I went to the sites, downloaded / looked, and left. Everything. I didn’t think it was important to anyone, so in my CSP rules there are no Disqus, no Social Widgets Frames, so.... 

How will I have time or will I be bored, I will go over in all my CSP rules and add Disqus and SOC Widgets / someone uses this. OK.

> On an unrelated question, how does this list compare to https://github.com/jspenguin2017/uBlockProtector ? Nano Defender seems to have more people maintaining it, and this has effort split maintaining the AdGuard filters, so it would seem Nano Defender would be better...

You decide. You can always unsubscribe from my list.

**Comment by llacb47** [comment]
What is the difference between FFA and PressTheAttack?

**Comment by bogachenko** [comment]
in the first I write only anti adblock and popups, in the second phishing, dubious domains and scripts

**Comment by KonoromiHimaries** [comment]
@bogachenko cc

**Comment by bogachenko** [comment]
@KonoromiHimaries what is that?

**Comment by KonoromiHimaries** [comment]
@bogachenko broken oload player https://github.com/bogachenko/fuckfuckadblock/blob/master/fuckfuckadblock.txt#L204
