### ISSUE TITLE
leechpremium.link

### ISSUE THREAD

**Issue by blazesprings** [bogachenko/fuckfuckadblock#160]
### Basic information

**Check the link:**  `https://go.leechpremium.link/`
**Category:**  Timer of 10 secs every time the site redirects to the above link.
**Reported from:**  Singapore

### User environment

**Browser:** Chrome
**Extension or program:** uBlock Origin 

### Additional message

Steps to reproduce the problem :
1. Go to `https://leechpremium.link/index.php`
2. Generate download link for any file
3. After clicking download button, the above link appears 2-3 times and every time there is a timer of 10 secs.
   e.g. `https://go.leechpremium.link/shrtfly/?id=6324a4a687c421616157286`

**Comment by bogachenko** [comment]
>The rules in these lists are designed to filter pop-ups and bypass ad protection.

https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock#article-in-english-language

**Comment by bogachenko** [comment]
Link for generator - `https://katfile.com/1vvexmtevnuv/app567.part4.rar.html`

`http://go.leechpremium.link/go/?go=aHR0cDovL21lZ2F1cmwuaW4vMnQ2anVmR3g=` >>
`https://go.leechpremium.link/go/?go=aHR0cDovL21lZ2F1cmwuaW4vMnQ2anVmR3g=` >>
`https://go.slink.bid/full?api=ef7be13eeb40eb7fabad9e6202dc0461525ab37a&type=2&url=aHR0cDovL21lZ2F1cmwuaW4vMnQ2anVmR3g=` >>
`https://go.slink.bid/BKCJvNZu` >>
`http://megaurl.in/2t6jufGx` >>
`https://downfile.site/?type=2&token=2t6jufGx&salt=a2521a12393c305ec7464e05a9de5276` >>
`https://downfile.site/hipaa-a-must-have-health-service-in-vogue.html` >>
`https://downfile.site/why-is-wordpress-security-so-important.html` >>
`http://go.leechpremium.link/go/?go=aHR0cHM6Ly9hZHNob3J0LmNvL1FMYWliWVNa` >>
`https://go.leechpremium.link/go/?go=aHR0cHM6Ly9hZHNob3J0LmNvL1FMYWliWVNa` >>
`https://go.slink.bid/full?api=ef7be13eeb40eb7fabad9e6202dc0461525ab37a&type=2&url=aHR0cHM6Ly9hZHNob3J0LmNvL1FMYWliWVNa` >>
`https://go.slink.bid/HE5l3CY6Wg` >>
`https://adshort.co/QLaibYSZ` >>
`https://go.techgeek.digital/QLaibYSZ` >>
`http://go.leechpremium.link/go/?go=aHR0cDovL21lZ2FmbHkuaW4vUEFkMTdNeg==` >>
`https://go.leechpremium.link/go/?go=aHR0cDovL21lZ2FmbHkuaW4vUEFkMTdNeg==` >>
`https://go.slink.bid/full?api=ef7be13eeb40eb7fabad9e6202dc0461525ab37a&type=2&url=aHR0cDovL21lZ2FmbHkuaW4vUEFkMTdNeg==` >>
`https://go.slink.bid/1wBLS76hfg` >>
`http://megafly.in/PAd17Mz` >>
`https://travel.trangchu.news/?type=2&token=PAd17Mz&salt=6717c80b5b62f6ae817ef674251ac4a0` >>
`https://travel.trangchu.news/review-kinh-nghiem-du-lich-buon-ma-thuot-2022-chi-tiet.html` >>
`https://travel.trangchu.news/kinh-nghiem-du-lich-nha-trang-an-toan-mua-dich-nam-2022.html` >>
`http://go.leechpremium.link/go/?go=aHR0cHM6Ly9hZGJ1bGwubWUvRXFmNDE5ZQ==` >>
`https://go.leechpremium.link/go/?go=aHR0cHM6Ly9hZGJ1bGwubWUvRXFmNDE5ZQ==` >>
`https://go.slink.bid/full?api=ef7be13eeb40eb7fabad9e6202dc0461525ab37a&type=2&url=aHR0cHM6Ly9hZGJ1bGwubWUvRXFmNDE5ZQ==` >>
`https://go.slink.bid/x0WB0bKRsz` >>
`https://adbull.me/Eqf419e` >>
`https://deportealdia.live/` >>
`https://deportealdia.live/2021/01/21/la-nueva-temporada-2021-de-formula-1-causa-furor/` >>
`https://deportealdia.live/2021/01/24/los-jjoo-mas-cerca-de-su-cancelacion-en-2021/` >>
`https://adbull.me/Eqf419e?ref=aHR0cHM6Ly9nby5zbGluay5iaWQv` >>
`http://go.leechpremium.link/go/?go=aHR0cHM6Ly9waW5naXQuaW0vQTNvSlY=` >>
`https://go.leechpremium.link/go/?go=aHR0cHM6Ly9waW5naXQuaW0vQTNvSlY=` >>
`https://go.slink.bid/full?api=ef7be13eeb40eb7fabad9e6202dc0461525ab37a&type=2&url=aHR0cHM6Ly9waW5naXQuaW0vQTNvSlY=` >>
`https://go.slink.bid/iTb6` >>
`https://pingit.im/A3oJV` >>
`https://noweconomy.live/` >>
`https://noweconomy.live/66-trillion-euros-on-investments-in-the-world-to-reach-emissions-0/` >>
`https://pngit.live/A3oJV?ref=aHR0cHM6Ly9nby5zbGluay5iaWQv` >>
`http://go.leechpremium.link/go/?go=aHR0cHM6Ly9zbGluay5iaWQvSHN4bHdG` >>
`https://go.leechpremium.link/go/?go=aHR0cHM6Ly9zbGluay5iaWQvSHN4bHdG` >>
`https://go.slink.bid/full?api=ef7be13eeb40eb7fabad9e6202dc0461525ab37a&type=2&url=aHR0cHM6Ly9zbGluay5iaWQvSHN4bHdG` >>
`https://go.slink.bid/yEjyK` >>
`https://slink.bid/HsxlwF` >>
`http://dl.leechpremium.link/rd/02/?file=ce861eaba2`
