### ISSUE TITLE
dropgalaxy.in

### ISSUE THREAD

**Issue by blazesprings** [bogachenko/fuckfuckadblock#161]
### Basic information

**Check the link:** `https://dropgalaxy.in/tgzos96fbw4l`
**Category:** Anti-adblock
**Reported from:** Singapore

### User environment

**Browser:** Chrome
**Extension or program:** uBlock Origin

**Comment by bogachenko** [comment]
For the future, please use the old issues to ping problem sites.
***
Duplicate of #79 #86
