### ISSUE TITLE
nydailynews

### ISSUE THREAD

**Issue by nasca2000** [bogachenko/fuckfuckadblock#163]
### Basic information

**Check the link:** `https://nydailynews.com`
**Category:** Anti-adblock
**Reported from:**  USA
### User environment

**Browser:** Chrome 89.0.4389.95
**Extension or program:**

**Comment by bogachenko** [comment]
I can't reproduce this issue, I don't have anti-adblock with default settings + Fuck Fuck adblock.
However, there are many byte classes on this site, I will add one rule, I think it will help. If the problem persists, specify the extension or program you use to block ads, as well as the list of your subscriptions in it, and I'll reopen this question and try to help.

**Comment by nasca2000** [comment]
Hi,
I am blocking ads with ublock origin that is part of the VeePN virtual private network.
A screenshot of my subscriptions are attached.[Screenshot 2021-03-26 10.37.50 AM.png]
I should have specified that I only get the popup if I click on an article on nydailynews.com. Just going to nydailynews.com will not show it.
Thanks in advance.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
