### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by FadeMind** [bogachenko/fuckfuckadblock#17]
**Site Sample** | 
----------------|
https://pilot.wp.pl/tv/#polsat

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Firefox Quantum 69.0 x64 (lastest)
AdGuard version:                       | **7.2.2903.6 BETA [20190902]** 
Stealth Mode:					       | disabled

**Site Sample** | 
----------------|
https://pilot.wp.pl/tv/#polsat

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Firefox Quantum 69.0 x64 (lastest)
AdGuard version:                       | **7.2.2903.6 BETA [20190902]** 
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Cookiemonster List
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

FB share leaking when FFA is enabled. When FFA is disabled - then FB share iframe is blocked.
FIX from @krystian3w `pilot.wp.pl#?#.fb_iframe_widget` WORKS WELL. This issue is just INCOMPATIBILITY with lastest changes in Adguard For Windows 7.2.2903.6 BETA [20190902]. NOTICE: I using same setup for Adguard Extension and here NO LEAKING - all is blocked well.  

Adguard For Windows 7.2.2903.6 BETA [20190902] = FB iframe leaking
Adguard Extension 3.2.1 = FB iframe blocked

<details><summary><b>Screenshot:</b></summary>

![scr-1567443191-001](https://user-images.githubusercontent.com/9846948/64127872-e36e2f80-cdb3-11e9-98e1-a96caa1b1b63.png)

Reference https://github.com/MajkiIT/polish-ads-filter/issues/14588

</details><br/>

**Comment by bogachenko** [comment]
Eh. AG 7.2.2910 https://user-images.githubusercontent.com/8535285/64144082-af9c1400-ce5e-11e9-832f-2cb2c7b97b71.gif

**Comment by bogachenko** [comment]
>This issue is just INCOMPATIBILITY with lastest changes in Adguard For Windows

Write to the developers.
***
Although okay, it doesn’t matter. I will remove `generichide`, since many have problems with it.

**Comment by FadeMind** [comment]
@bogachenko  thank you.
