### ISSUE TITLE
droplink.co

### ISSUE THREAD

**Issue by callmenemo491** [bogachenko/fuckfuckadblock#171]
### Basic information

**Check the link:** `https://droplink.co/aXlrq8d9`
**Category:** Anti-adblock + Pop-up
**Reported from:** Japan

### User environment

**Browser:** Firefox 87

### Additional message

Site redirects to:  yoshare.net
and here it gives a 'adblock' popup

**Comment by bogachenko** [comment]
_Please do not upload images. If the file posted by the user contains anti-block /pop-ups, I will find it without an image (only in especially difficult cases, I can request an image or steps to reproduce)._

I cannot reproduce, the rule `@@*$generichide,domain=yoshare.net` works for me.

**Comment by callmenemo491** [comment]
fyi, the extra rule works for me. thanks!
