### ISSUE TITLE
speedsatoshi.com

### ISSUE THREAD

**Issue by callmenemo491** [bogachenko/fuckfuckadblock#173]
### Basic information

**Check the link:** `https://speedsatoshi.com/lootlinks/RsGsk8GTzCHhBI6zxN6qfnhmGA67XGTD`
**Category:** Anti-adblock
**Reported from:** Japan

### User environment

**Browser:** Firefox 87

**Comment by bogachenko** [comment]
The site `https://speedsatoshi.com/lootlinks/RsGsk8GTzCHhBI6zxN6qfnhmGA67XGTD` redirects me to the `https://www.lootlinks.net/`.

Give me the steps to reproduce this problem, where to click?

**Comment by bogachenko** [comment]
Anti-adblock has been fixed, but what about pop-up windows, where to click? Give me the steps to reproduce.

**Comment by callmenemo491** [comment]
the anti-adblock was what i was after..., sorry i forgot to remove the "popup" text (mistake).

**Comment by bogachenko** [comment]
BTW (I registered on this site) Here `https://www.speedsatoshi.com/shortlinks` are a lot of third-party sites containing pop-up windows (now I check them in turn, there are just a lot of them) so this can hardly be considered a mistake.
