### ISSUE TITLE
pastebin.com

### ISSUE THREAD

**Issue by brian6932** [bogachenko/fuckfuckadblock#176]
### Basic information

**Check the link:** `https://pastebin.com/`
**Category:** Anti-adblock
**Reported from:** United States

### User environment

**Browser:** Chromium
**Extension or program:**  uBlock Origin

This worked for me under My filters (in uBO):
`pastebin.com###__vliadb83`
`pastebin.com###__vliadb83-bg`

**Comment by bogachenko** [comment]
I cannot reproduce, does this rule `@@*$generichide,domain=pastebin.com` work ?

**Comment by brian6932** [comment]
how would I test that in uBO? Just paste it in My rules?

**Comment by bogachenko** [comment]
Since I have already made changes to the sheet, just update the list and check.

**Comment by brian6932** [comment]
That does not work

**Comment by bogachenko** [comment]
Yes, I was able to reproduce this in the Opera browser (Chromium based), but the fixes I added earlier work for me.
Try clearing your browser data. 

Tell me, is this `https://cdn.jsdelivr.net/gh/vli-platform/adb-analytics@77bebb/v1.0.min.js` script blocked when using [the logger](https://github.com/gorhill/uBlock/wiki/The-logger)?

**Comment by bogachenko** [comment]
>the list wasn't auto updating

FYI https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now
For the future - no need to wait for the list to update, just purge the cache and click update button.

**Comment by brian6932** [comment]
Yea I forgot that was a thing lol
