### ISSUE TITLE
Not a valid filter list

### ISSUE THREAD

**Issue by emkirsh** [bogachenko/fuckfuckadblock#180]
### Basic information

**Check the link:** `https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt&title=Fuck%20Fuckadblock`
**Category:**  AdblockPlus (fuckfuckadblock)
**Reported from:**  USA

### User environment

**Browser:** Microsoft Edge Dev MacOS
**Extension or program:** AdBlockPlus

### Additional message

I'm getting a message like this:
after installing by clicking the adblockplus subscribe link on the readme.md. Is this error okay (can I ignore it) or is something wrong? Thanks!

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock#article-in-english-language
