### ISSUE TITLE
thespectrum.com

### ISSUE THREAD

**Issue by dhkim0800** [bogachenko/fuckfuckadblock#182]
### Basic information

**Check the link:** `https://www.thespectrum.com/story/news/2021/04/17/heres-which-national-park-nearby-towns-still-require-mask-dont/7212642002/`
**Category:** Pop up and breakage
**Reported from:** Korea

### User environment

**Browser:** Chrome
**Extension or program:** Adguard for chrome

**Comment by bogachenko** [comment]
>Category: Pop up and breakage

Which window comes out and what is broken? Give me the steps to reproduce the problem + which filters are you subscribed to?

**Comment by dhkim0800** [comment]
I’m only using default filters of AdGuard and your filter. A popup that doesn’t let me read the article shows up, telling to disable ad blocker.

**Comment by bogachenko** [comment]
With default settings, I cannot reproduce anti-adblock, but check this rule `@@*$generichide,domain=thespectrum.com`, add it to the Custom Rules wait a second and check this site again.
