### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by swathigrate** [bogachenko/fuckfuckadblock#187]
### Basic information

**Check the link:** `https://dropgalaxy.com/getlink/11/`
**Category:** Anti-adblock
**Reported from:**  India 

### User environment

**Browser:**  Firefox 
**Extension or program:**  uBlock Origin

### Additional message 
When a click and free download its routing to another page and showing to disable adblock

**Comment by bogachenko** [comment]
>When a click and free download its routing to another page and showing to disable adblock

Such sites rely on cookies, next time add steps to reproduce the problem, for example 

`https://dropgalaxy.in/fkqlb29nxfdk` > `https://www.google.com/search?q=Techssting+site%3Atechssting.com` > `https://techssting.com` > `https://dropgalaxy.com/getlink/10/`

Also DO NOT upload screenshots, at least not until I ask you to.
