### ISSUE TITLE
myanimelist.net

### ISSUE THREAD

**Issue by onchodila** [bogachenko/fuckfuckadblock#188]
### Basic information

**Check the link:** `https://myanimelist.net/`
**Category:** Breakage
**Reported from:** Sweden

### User environment

**Browser:** Firefox 88.0
**Extension or program:** uBlock Origin v1.35.0

### Additional message

1. Created new Firefox profile.
1. Installed ublock origin.
1. Updated filters.
1. Visited `https://myanimelist.net/`

No ads are displayed.

but if you:

5. Add this list to custom lists.

Ads show up.

**Comment by bogachenko** [comment]
I don't see any ads, nevertheless try adding this rule and say
`@@*$generichide,domain=myanimelist.net,badfilter`

**Comment by onchodila** [comment]
That solves it.
