### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by DraconicNEO** [bogachenko/fuckfuckadblock#189]
### Basic information

**Check the link:** `https://megaup.net/2iIov/TEST.txt`
**Category:** Anti-adblock
**Reported from:** Canada

### User environment

**Browser:** Firefox Developer Edition v87
**Extension or program:** uBlock Origin 1.35.0

### Additional message
Anti Adblock Message Appears on any Download Page.

I tested Multiple Countries on My VPN and got the same result.
Here are the ones I tested:
- Japan
- USA
- Canada
- Germany
- France
- UK
- Russia
- Denmark
- Brazil

**Comment by StrawbarryVan** [comment]
Hello. I came here to report the same problem on the same website. I'm using uBlock Origin.

I tried different browsers: Avast, Brave, Chrome, Edge, Firefox, Opera, and Vivaldi. All of them display the same "Disable Adblock" nuisance rather than the download link.

![MegaUpNet](https://user-images.githubusercontent.com/81157283/116797123-12cdc600-aada-11eb-84d0-38d77d869bca.jpg)

**Comment by bogachenko** [comment]
@StrawbarryVan DO NOT UPLOAD images here, none at all.

@DraconicNEO @StrawbarryVan This site is problematic, that is, it is constantly changing, you can't keep track of it.  I'm thinking of adding it to UNSUPPORTED SITES, read here https://github.com/bogachenko/fuckfuckadblock/wiki/Unsupported-sites#article-in-english-language
while I spy on him, I will leave this issue open, as a temporary measure, add this rule to My Filters on uBO `@@||megaup.net^$elemhide`

**Comment by bogachenko** [comment]
fuck, one of the rules on my list interferes with the anti-ddos system of this site, I'll delete this rule when I get to my laptop

**Comment by DraconicNEO** [comment]
> as a temporary measure, add this rule to My Filters on uBO `@@||megaup.net^$elemhide`, this rule will remove anti-adblock but unblock some cosmetic ads.

If that method still allows some cosmetic ads is it safe?

**Comment by StrawbarryVan** [comment]
I can confirm that, while that temporary solution does indeed gets rid of the anti-adblock warning, once the d/l button is clicked, the page gets stuck on the anti-DDoS part.

As for cosmetic ads, all I saw were some social media links, on the right side of the page. Everything else is the same for me.

**Comment by bogachenko** [comment]
Removed unnecessary rules, now blocking protection from ddos on this site works.
***
@StrawbarryVan 

> Apologies for the image upload. I didn't know it was forbidden here. On uBlock Origin github page they actually ask for images to make requests more clear. I just assumed you had the same rules.

This is not the rule, this is the request. Almost everything can be described in words without resorting to photography. Sometimes I can ask to take a screenshot, very rarely, when I do not understand something. 

@DraconicNEO 

> If that method still allows some cosmetic ads is it safe?

This repository does not belong to the section "Preserving privacy", here I can allow a network request from Google which will be the culprit of the anti-block on some site, for example. I do not put privacy above all else, and in fact, you too, once you visit such sites. Such sites use advertising domains to check the adblock, specifically on this site there is an advertising domain `adskeeper.co.uk`, it then runs a script with an annoying notification. Of course, sometimes it is possible to bypass such restrictions by not allowing such questionable domain names, but sometimes not.


In this particular case, on this site, the script is encrypted (Here the script checks for blocks with ads `[id^="AdskeeperComposite"]` ), and so far I do not know how to decrypt it.

**Comment by DraconicNEO** [comment]
> This repository does not belong to the section "Preserving privacy", here I can allow a network request from Google which will be the culprit of the anti-block on some site, for example. I do not put privacy above all else, and in fact, you too, once you visit such sites. Such sites use advertising domains to check the adblock, specifically on this site there is an advertising domain `adskeeper.co.uk`, it then runs a script with an annoying notification. Of course, sometimes it is possible to bypass such restrictions by not allowing such questionable domain names, but sometimes not.

I was more concerned about something like Malware since that does more way more immediate harm than tracking.

**Comment by bogachenko** [comment]
There is nothing harmful, only tracking, such companies personalize content and make money.
Adguard and uBO allow such network requests to bypass anti-adblock. 
https://github.com/AdguardTeam/AdguardFilters/commit/6e3c5b218f908b102b0fd24396a2776be4d01ba5#diff-beb9872d5fbb0d321b23246ef65d99c4d842cd31f5654869bb0974cbd0b97dc4R850-R853
https://github.com/uBlockOrigin/uAssets/commit/0399098d88aababe79f1250f088596a2a1187e97#diff-03b955eebef8886aa0f1ef70b305e9b7996de9a9e0adc9fe002db5a21d301c9fR5076-R5077
