### ISSUE TITLE
joemonster.org

### ISSUE THREAD

**Issue by FadeMind** [bogachenko/fuckfuckadblock#19]
**Site Sample** | 
----------------|
https://joemonster.org/

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64 (lastest)
Browser:                               | Firefox Quantum 69.0 x64 (lastest)
AdGuard version:                       | **7.2.xxxx NIGHTLY** 
Stealth Mode:					       | disabled

| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuck Adblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Annoyances
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

`@@*$generichide,domain=joemonster.org` leaking facebook like scripts. 
Please remove this domain from this rule. And Adguard For Windows cannot handle very long lines with rules. Pages are damaged. 

![scr-1568049724-001](https://user-images.githubusercontent.com/9846948/64552235-204ba080-d337-11e9-801a-496beaeace83.png)

Same issue was with pilot.wp.pl (generichide)

CC @AdamWr @bogachenko  @hawkeye116477 @krystian3w

References https://github.com/MajkiIT/polish-ads-filter/issues/14641

**Comment by hawkeye116477** [comment]
`Please remove this domain from this rule. And Adguard For Windows cannot handle very long lines with rules. Pages are damaged.`
I guess if that's the case, that's rather should be fixed on AdGuard. Even if he removes that domain from this rule, then if he add another again, problem can happen again.

**Comment by krystian3w** [comment]
Same troubles with:

`@@||pilot.wp.pl^$generichde`
`@@||joemonster.org^$generichde`

on AdGuard App?

**Comment by bogachenko** [comment]
> Same issue was with pilot.wp.pl (generichide)

I do not have generichde for pilot.wp.pl

***
joemonster.org generichde, i will delete.

***
the other day, as time will be, I’ll write the rules for this repository ... and one of what I will not delete is the breakdown of social icons. it's annoying
