### ISSUE TITLE
how to use this with tampermonkey

### ISSUE THREAD

**Issue by rocket625** [bogachenko/fuckfuckadblock#192]
1. how is this added to tamper monkey manually. 
2. is there a link to add this like the reek script that updates automatically?

**Comment by bogachenko** [comment]
>how is this added to tamper monkey manually.

This cannot be used by custom script managers.
https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock#article-in-english-language

>is there a link to add this like the reek script that updates automatically?

Nope. There is no script at all.
