### ISSUE TITLE
onelinks.site, linkgoo.site

### ISSUE THREAD

**Issue by pastormorris** [bogachenko/fuckfuckadblock#193]
Good evening beautiful community, can you add these domains to the list? I give an example of each.

https://onelinks.site/
https://gdrivelatinohd.net/raya-y-el-ultimo-dragon-2021-bd50-full-1080p-latino-ingles-iso/

https://linkgoo.site/
https://www.descargatepelis.com/facultad-de-derecho-2021-temporada-1-1080p-web-dl/
This one does work:

https://drivelinks.me
https://www.peliculasgoogledrive.info/del-crepusculo-al-amanecer-1996-latino-bdrip-google-drive-onix/

https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssets@master/filters/filters.txt
In this list is the one that I want to add these two domains onelinks.site, linkgoo.site

For example there is this domain: drivelinks.me
https://github.com/uBlockOrigin/uAssets/issues/7964

and it works perfect, you can try here: https://www.peliculasgoogledrive.info/violento-y-furioso-2019-latino-1080p-google-drive-onix/

Thanks!.

**Comment by bogachenko** [comment]
Dead domains, deleted.
