### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by kairusds** [bogachenko/fuckfuckadblock#194]
The filter list doesn't get recognized by AdBlock Plus and the Subscribe link on the README file does not work.

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock#article-in-english-language

> In this repository, filters are created for AdGuard and uBlock Origin and other ad-blocking programs created based on these two (e.g. AdNauseam).

**Comment by bogachenko** [comment]
You can also read why this is impossible - https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported-products
