### ISSUE TITLE
boostupstation.com

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [bogachenko/fuckfuckadblock#195]
### Basic information

**Check the link:** `https://boostupstation.com/`
**Category:** Anti-adblock
**Reported from:** Indonesia

### User environment

**Browser:** Cent Browser Version 4.3.9.248 (Official Build) (32-bit) (Portable) (Chromium 86.0.4240.198)
**Extension or program:** Ublock Origin Version 1.35.2
**DNS:** No

**Comment by TheBSODAndWSODFan** [comment]
I Have Ublock Origin And Adblock Plus Enabled

**Comment by bogachenko** [comment]
Please do not upload images here, at all, never (at least until I ask if any issue/s is not clear).
Also, using 2 ad blockers will only hurt your internet surfing. It's like using 2 antiviruses on a computer, they will conflict with each other and cause false positives.

**Comment by Yuki2718** [comment]
> I Have Ublock Origin And Adblock Plus Enabled

That's probably why you see anti-adb. Using ABP alongside breaks uBO's resource redirection and is only a source of trouble. Use only uBO.
