### ISSUE TITLE
blackspigot.com

### ISSUE THREAD

**Issue by Bagou450** [bogachenko/fuckfuckadblock#196]
### Basic information

**Check the link:** `https://blackspigot.com/`
**Category:** Breakage
**Reported from:** France

### User environment

**Browser:** Chrome
**Extension or program:** Adguard Home
**DNS:** AdGuard Home

**Comment by bogachenko** [comment]
>Extension or program: Adguard Home

First one, Fuck Fuck adblock does not work on ADGH, it only works on uBlock Origin, Adguard for Windows/Android/Mac<partially>, as well as on the Adguard browser extension.

> Category: Breakage

My list can't break this site because it's not added there, Fuck Fuckadblock doesn't filter the site `blackspigot.com`.
