### ISSUE TITLE
Does it work with adguard windows?

### ISSUE THREAD

**Issue by AngelosNaoumis** [bogachenko/fuckfuckadblock#2]
Does this filter work with adguard windows app? It is mentioned that windows app does not have scriptlets but there are some filters in the default windows app with scriptlets.

**Comment by bogachenko** [comment]
Hello

> Does this filter work with adguard windows app?

No, it does not work. I wrote about this in README.md. Adguard for Windows does not yet support them (as far as I know apps for windwos, mac and android do not support them yet). When they release an update, I really do not know, I myself want to use only the program, not the extension.

>It is mentioned that windows app does not have scriptlets but there are some filters in the default windows app with scriptlets.

This is for those who support them.

Perhaps they are looking at the report if there are more reports from the extension (and not from the program), then they write with scriptlets, I do not know, you can ask them.

**Comment by AngelosNaoumis** [comment]
Are you using both windows application and browser addon (with just the filters that do not work with windows app) ?

**Comment by bogachenko** [comment]
extension only

**Comment by krystian3w** [comment]
This syntax gone in the feature:

```
gazeta.pl,tokfm.pl,sport.pl,plotek.pl#%#AG_setConstant('ONTVminiatureBlocked', 'trueFunc');
tokfm.pl#%#AG_setConstant('gazeta_pl.Player.FloatingPlayer.floatPlayer', 'noopFunc');
```

---

new:

```
gazeta.pl,tokfm.pl,sport.pl,plotek.pl#%#//scriptlet("set-constant", ONTVminiatureBlocked, trueFunc)
tokfm.pl#%#//scriptlet("set-constant", gazeta_pl.Player.FloatingPlayer.floatPlayer, noopFunc)
```

**Comment by grx7** [comment]
Does it work with ublock Origin?

Can you add: https://rutube.ru/video/d71480a6c3af24876b270a4313a69fc2/?pl_type=source&pl_id=21208

its fucking annoying to watch Tantci with ads

**Comment by bogachenko** [comment]
@grx7 I do not delete ads. I delete only anti adblock and pop ups

**Comment by krystian3w** [comment]
Delete only leftover (empty) generated by generichide - IMO needed if no possible fix with scriplet (or less exeception).

**Comment by grx7** [comment]
> Delete only leftover (empty) generated by generichide - IMO needed if no possible fix with scriplet (or less exeception).

how do you delete that?

**Comment by krystian3w** [comment]
e.g.: domain. com`##.adsbygoogle` 

https://github.com/bogachenko/fuckfuckadblock/blob/e6195092936b1245dbe3df41ebb91a6283b70360/fuckfuckadblock.txt#L514
