### ISSUE TITLE
udemydownload.com

### ISSUE THREAD

**Issue by chirag127** [bogachenko/fuckfuckadblock#203]
### Basic information 

**Check the link:**  `https://udemydownload.com/english-for-beginners-intensive-spoken-english-course/`
**Category:** Anti-adblock
**Reported from:**  India

### User environment

**Browser:** Chrome
**Extension or program:** AdGuard Browser extension v3.6.5
**DNS:** No

I'm also using https://github.com/adsbypasser/adsbypasser user script .

**Comment by bogachenko** [comment]
Please do not upload any images here, it will take you 5 seconds to fill out the form with text.
