### ISSUE TITLE
carousell.com.hk

### ISSUE THREAD

**Issue by tkp206093** [bogachenko/fuckfuckadblock#207]
### Basic information

**Check the link:**  `https://www.carousell.com.hk`
**Category:** Breakage
**Reported from:** Hong Kong

### User environment

**Browser:** Google Chrome 91.0.4472.124
**Extension or program:** uBlock Origin 1.36.0
**DNS:** No

### Additional message

As long as this filtering list is turned on, there is no way to completely remove the position of the advertisement. There will be residual advertisements on the web page. If you close this list, you can filter the entire web page normally.

**Comment by bogachenko** [comment]
You need to come here https://github.com/easylist/easylistchina try to describe the problem there, they should help. I am not engaged in advertising, only anti-adblock and pop-ups.

By the way, I tried with a Hong Kong IP and nothing, I could not reproduce the problem and did not find an advertisement there, **but if this is what I think** then read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues

**Comment by tkp206093** [comment]
I'm sorry that my English is very bad, so you may not fully understand what I'm talking about by then

I mean not engaged in advertising

Is make unable to remove the free space of the clean advertisement


Enable
![image](https://user-images.githubusercontent.com/29872453/124131469-6a74b780-dab2-11eb-9b34-a3ae73c7eb96.png)

![image](https://user-images.githubusercontent.com/29872453/124131734-a9a30880-dab2-11eb-874f-147417d62373.png)

![image](https://user-images.githubusercontent.com/29872453/124132045-fc7cc000-dab2-11eb-80d2-86a89b96d42d.png)


turn off
![image](https://user-images.githubusercontent.com/29872453/124131526-7a8c9700-dab2-11eb-984b-d8db8dcde800.png)

![image](https://user-images.githubusercontent.com/29872453/124131783-b6bff780-dab2-11eb-9c8c-84aef96c5159.png)

![image](https://user-images.githubusercontent.com/29872453/124132114-0dc5cc80-dab3-11eb-8b11-020f15a28285.png)

**Comment by bogachenko** [comment]
I have already understood you, this is a common problem when using my sheet. When using my sheet, SOMETIMES there are empty spaces from advertising. Yes, yes, I know about it. That's why I gave you an article about it to read https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues 

By the way, please do not upload any images here until you are asked (if the question is not clear).

**Comment by Yuki2718** [comment]
Thx, reproduced with Hong Kong IP.
