### ISSUE TITLE
photopea.com

### ISSUE THREAD

**Issue by FFSMNRK** [bogachenko/fuckfuckadblock#208]
### Basic information

**Check the link:** `https://www.photopea.com`
**Category:** Anti-adblock
**Reported from:** USA

### User environment

**Browser:** Chrome 67.0.3396.87
**Extension or program:** uBlock Origin
**DNS:** None

**Comment by bogachenko** [comment]
I can not reproduce, give me the steps for this, what exactly should be done to receive a warning about the adblock on this site?

**Comment by FFSMNRK** [comment]
The adblocker has to be on for the notice to appear.

**Comment by FFSMNRK** [comment]
<img width="1451" alt="Screen Shot 2021-07-11 at 5 51 26 PM" src="https://user-images.githubusercontent.com/50444757/125241893-0a53f180-e2ba-11eb-9375-fa67a57d5ddb.png">

**Comment by FFSMNRK** [comment]
I only have _the two_ adblockers (ABP and uBO); the other extensions seen are Session Buddy, Charset, Image Search, Initab, Hola VPN, and several others that are for VK/Soundcloud, and of course Tampermonkey.

Now disabling all _those_ seems to do it. (Reenabling them, minus ABP, also seems to work...?)

**Comment by bogachenko** [comment]
>I only have the two adblockers

You have 3 of them, I saw this in your screenshot, which I deleted, in addition to that you have the Tempermonkey container for user scripts installed, and I do not know what scripts you installed there.  In short, read this article https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions#article-in-english-language

> Now disabling all those seems to do it. (Reenabling them, minus ABP, also seems to work...?)

Sweet.
