### ISSUE TITLE
clickbits.io

### ISSUE THREAD

**Issue by Boyrules** [bogachenko/fuckfuckadblock#21]
Sir please add `https://clickbits.io/` too in list

**Comment by llacb47** [comment]
`https://adshares.net/`

**Comment by bogachenko** [comment]
@Boyrules  `clickbits.io` - already added 893d17ce232b98f444cbd74fc17f528f5395bc1b
@llacb47 and what should I do about it?

**Comment by Boyrules** [comment]
Thank u so much sir
