### ISSUE TITLE
uup.rg-adguard.net

### ISSUE THREAD

**Issue by FadeMind** [bogachenko/fuckfuckadblock#211]
### Basic information

**Check the link:** https://uup.rg-adguard.net/
**Category:** Breakage
**Reported from:** Poland

### User environment

**Browser:** Edge
**Extension or program:** Adguard Extension
**DNS:** Google DNS

### Additional message

```
@@/^https?:\/\/(www\.)?.*\/ad[svbxo]?([_-a-zA-Z0-9.]{1,15})?\.js/$script,xmlhttprequest,other
```
from FFA leaking iframe banner ads top on site.

Workaround
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=uup.rg-adguard.net,important,third-party
```

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues
