### ISSUE TITLE
zetrotranslation.com

### ISSUE THREAD

**Issue by volcbs** [bogachenko/fuckfuckadblock#215]
### Basic information

**Check the link:** `https://zetrotranslation.com/novel/but-because-i-like-you/chapter-1-you-never-know-what-might-happen-in-life/`
**Category:** Anti-adblock
**Reported from:** Indonesia

### User environment

**Browser:** Microsoft Edge Version 94.0.972.2
**Extension or program:** uBlock Origin v1.37.0

### Additional message

It appears after few seconds.

**Comment by bogachenko** [comment]
I can only reproduce if I block the request `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`
but my rule, which is located below, allows it, so I do not have an anti-block on this site
https://github.com/bogachenko/fuckfuckadblock/blob/7b73ebbac342acbbaa8295d6dbf05c3a897d5dfb/fuckfuckadblock.txt#L463
