### ISSUE TITLE
rureka.com

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#219]
### Basic information

**Check the link:**  `https://rureka.com/kustomisasi-pulpstone-openwrt-18-06-2-amlogic-s905x-stb-hg680p-dan-b860h-oleh-rureka/`
**Category:** Anti-adblock
**Reported from:**  Indonesia

### User environment

**Browser:**  Google Chrome 92.0.4515.131 (Official Build) (32-bit)
**Extension or program:**  uBlock Origin
**DNS:**  No
**Extensions:**  No

**Comment by rigaz29** [comment]
Broken
https://rureka.com/brainfuck-tunnel-alternatif-http-injector-untuk-openwrt/
https://rureka.com/zee.js

**Comment by bogachenko** [comment]
not broken, just updated the script
