### ISSUE TITLE
techyneed.com

### ISSUE THREAD

**Issue by 0xh3LL0** [bogachenko/fuckfuckadblock#220]
### Basic information

**Check the link:** `https://a2zapk.com/1084863-opera-mini-fast-web-browser-56-1-2254-57583-mod-armeabi-v7a-a2z.html`
**Category:** Anti-adblock
**Reported from:** Indonesia

### User environment

**Browser:** Firefox 88
**Extension or program:** uBlock Origin
**DNS:** None
**Extensions:** None

**Comment by bogachenko** [comment]
I can’t reproduce, I don’t get Anti-Adblock, reset the default settings in uBO (and then install the FFA sheet) and try again.
Also update your browser and disable Tracking Protection in Firefox.

**Comment by 0xh3LL0** [comment]
update my browser to firefox 91
reset ubo and reinstall ffa
disable tracking protection
turn off those settings in about:config

i even delete the cache with ccleaner and disable any other addon but the adblock still detected...

![Untitled1](https://user-images.githubusercontent.com/23132217/130006557-1c010843-4c86-4dde-b765-e4903703f7bc.png)
![Untitled2](https://user-images.githubusercontent.com/23132217/130006561-2907cc26-4fca-49fa-ae9b-e0cdbee2f757.png)
![Untitled3](https://user-images.githubusercontent.com/23132217/130006563-e2812edc-f6db-4236-9567-7c171f6ec49c.png)
![Untitled4](https://user-images.githubusercontent.com/23132217/130006564-acb112a4-f430-40ab-9513-61592ed6c17a.png)

**Comment by bogachenko** [comment]
Don't upload images here.
You wrote in the DNS column - cloudflare, (this is not a filtering DNS, although I asked to fill it in only if it is such - I corrected it to no), are you sure that you use it and only it? Do you have any third-party programs, such as Pi-Hole or Adguard Home?
Have you changed the file hosts.txt? Have you checked this site on another browser?

**Comment by 0xh3LL0** [comment]
no, i dont even use vpn
for host i'm using [bebasid](https://github.com/bebasid/bebasid), but mainly only for unlocking website from indonesia

havent tried with another browser yet, but i'll try

**Comment by 0xh3LL0** [comment]
tried with chrome 92, its just same.

**Comment by bogachenko** [comment]
I can only reproduce anti-adblock if I block `googlesyndication.com` but I have it unblocked

**Comment by 0xh3LL0** [comment]
looks like unblocking googlesyndication really did the trick,
thanks
