### ISSUE TITLE
9to5mac.com, 9to5google.com, electrek.co

### ISSUE THREAD

**Issue by Ob1w4** [bogachenko/fuckfuckadblock#221]
### Basic information

**Check the link:**  `https://9to5mac.com/`, `https://9to5google.com/` and `https://electrek.co/`
**Category:** Breakage
**Reported from:**  France

### User environment

**Browser:**  Chrome 92
**Extension or program:**  uBlock Origin
**DNS:**  Cloudflare
**Extensions:**  None

### Additional message

 The dark mode of the three websites is not working when Fuck Fuckadblock is enabled. It works fine when Fuck Fuckadblock is disabled. You can check by clicking the sun icon in the upper right corner. Nothing happens. But it works when Fuck Fuckadblock is disabled in uBlock Origin.

The fix should be the same for the three websites, since they are using the same theme and are part the same brand (9to5)

**Comment by bogachenko** [comment]
>The dark mode of the three websites is not working
>Extensions: None
