### ISSUE TITLE
chd4.com

### ISSUE THREAD

**Issue by shawanroy** [bogachenko/fuckfuckadblock#223]
### Basic information

**Check the link:** `https://www.chd4.com/` 
**Category:** Anti-adblock
**Reported from:** Bangladesh 

### User environment

**Browser:** Firefox 91.0.2 (64-bit) 
**Extension or program:** uBlock Origin 
**DNS:** NO 
**Extensions:** uBlock Origin

**Comment by Yuki2718** [comment]
Need an account to test, even worse it's invitation-only.

**Comment by shawanroy** [comment]
> Need an account to test, even worse it's invitation-only.
Username Password in comment

**Comment by bogachenko** [comment]
@shawanroy It will work if you really do not use third-party DNS.

**Comment by shawanroy** [comment]
@bogachenko thanks work great!  Credential hide in comment tag.

**Comment by shawanroy** [comment]
### Basic information

**Check the link:** `https://www.chd4.com/`
**Category:** Breakage
**Reported from:** Bangladesh

### User environment

**Browser:**  Chromium 93.0.4577.63
**Extension or program:**  uBlock Origin  
**DNS:**  No 
**Extensions:** uBlock Origin

### Additional message
username/password hide in comment tag

**Comment by Yuki2718** [comment]
> username/password hide in comment tag

It's deleted.

**Comment by bogachenko** [comment]
@shawanroy What exactly is broken? Describe the problem to me.
@Yuki2718 Not deleted, to see them you need to be a collaborator of this repository, that is, to be able to edit posts.

**Comment by shawanroy** [comment]
> @shawanroy What exactly is broken? Describe the problem to me.
> @Yuki2718 Not deleted, to see them you need to be a collaborator of this repository, that is, to be able to edit posts.

@bogachenko Not working on chrome or chromium based browser also checked on Linux and Windows. I am using only ublock orgin extention and this script in ublock orgin.

**Comment by bogachenko** [comment]
>Category: Breakage

What exactly is broken?

**Comment by shawanroy** [comment]
> > Category: Breakage
> 
> What exactly is broken?

@bogachenko  Sorry writing mistake. It should be Anti-adblock category.

**Comment by bogachenko** [comment]
@shawanroy Check it, add it to My Filters, does it work - `chd4.com##+js(aopw, checkAdBlocker)` ?

**Comment by shawanroy** [comment]
> @shawanroy Check it, add it to My Filters, does it work - `chd4.com##+js(aopw, checkAdBlocker)` ?

yes working

**Comment by Yuki2718** [comment]
> Not deleted, to see them you need to be a collaborator of this repository, that is, to be able to edit posts.

Makes sense, as credentials are credentials even if disposable.

**Comment by bogachenko** [comment]
> Makes sense, as credentials are credentials even if disposable.

IDK if this is his main account or (a disposable) not a real one, if the user does not consider it necessary to publish it to the public, I will not do this either.

**Comment by shawanroy** [comment]
Reason to hide account credentials:  Multiple access with same account with different IP address should be banded from site admin.  (BTW this is not my main account) 
@Yuki2718  if you need this account, I will give, but how can I give you?

**Comment by Yuki2718** [comment]
@shawanroy Github doesn't have a secure way to send that, anyway the issue is fixed. If I need them again, I may share my email address.
