### ISSUE TITLE
chd4.com

### ISSUE THREAD

**Issue by shawanroy** [bogachenko/fuckfuckadblock#225]
### Basic information

**Check the link:** `https://www.chd4.com/`
**Category:** Breakage
**Reported from:** Bangladesh 

### User environment

**Browser:**  Firefox 91.0.2 
**Extension or program:**  uBlock Origin  
**DNS:**  No 
**Extensions:** uBlock Origin  

### Additional message
username/password hide in comment tag

**Comment by bogachenko** [comment]
Please do not create a million alone and the same problems for the same sites, next time you write in old topic/s - #223

**Comment by shawanroy** [comment]
> @shawanroy Please do not create a million identical issues for the same sites, next time, please write in the old topic/s - #223
> @Yuki2718 the rule `chd4.com##.adsbygoogle:upward(2)` should be deleted.

@bogachenko okay.

**Comment by Yuki2718** [comment]
@shawanroy @bogachenko Can you provide user name and password to check?

**Comment by bogachenko** [comment]
@Yuki2718 You don't need this, just take my word for it https://imgur.com/a/WwtyXQK

**Comment by Yuki2718** [comment]
Okay, thx for the video.
