### ISSUE TITLE
AdBlock Plus support

### ISSUE THREAD

**Issue by Iquaridys** [bogachenko/fuckfuckadblock#226]
### User environment

**Browser:** Last Version Firefox
**Extension or program:** [Adblock Plus - free ad blocker](https://addons.mozilla.org/id/firefox/addon/adblock-plus/)
**DNS:** No
**Extensions:** Default with fuckfuckadblock

### Additional message

got  Not a valid filter list  , in the add-ons , i think the syntax not right.

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported-products

https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock#article-in-english-language
> In this repository, filters are created for AdGuard and uBlock Origin and other ad-blocking programs created based on these two (e.g. AdNauseam).

**Comment by bogachenko** [comment]
Before opening a ticket, see similar  #194 #180 #153
