### ISSUE TITLE
handelsblatt.com

### ISSUE THREAD

**Issue by Morku** [bogachenko/fuckfuckadblock#228]
### Basic information

**Check the link:** `https://www.handelsblatt.com/`
**Category:** Anti-adblock
**Reported from:**  Germany

### User environment

**Browser:**  Firefox 93.0 64-Bit
**Extension or program:**  AdGuard (for Windows)
**DNS:**  AdGuard DNS

**Comment by bogachenko** [comment]
It's not an anti-adblock, it's a paywall.
Nothing will change if I bypass it, you will lose the content of articles (this is paid content), look for example here `https://www.handelsblatt.com/finanzen/anlagestrategie/trends/geldentwertung-unterschaetzte-inflation-warum-die-preise-immer-staerker-steigen/27664384.html`
part of the article is hidden, but if you want, for example, you can add this rule `handelsblatt.com##+js(abort-on-property-read.js, localStorage)`
it will remove the notification window. However, I will not add this to my list.

In the future, please don't upload any images here until I ask.
