### ISSUE TITLE
soap2day.ac

### ISSUE THREAD

**Issue by npn225** [bogachenko/fuckfuckadblock#238]
### Basic information

**Check the link:** `https://soap2day.ac/MczozMjoiMTE5Njd8fDY4LjE5OS4xMTguNzF8fDE2MzY0MzU5MzkiOw.html`
**Category:** Anti-adblock
**Reported from:** United States 

### User environment

**Browser:** Mozilla Firefox 94.0 & Brave Browser 95.1.31.88
**Extension or program:** uBlock Origin and Adguard
**DNS:** No
**Extensions:** Have thoroughly checked with all other extensions turned off!  Have checked both my adblockers individually. With Brave Browser, have also checked with Brave Shields turned off.  The site (soap2day) is recognizing the adblockers.

### Additional message

Soap2day has a gateway site (`https://soapgate.org/`) that leads to various versions of its service.  All of them detect adblock and, if you are using Brave, Brave Shields **must** be turned off in order to get into the actual websites.

**Comment by bogachenko** [comment]
@npn225 From which site did you go to `soap2day.ac`? Give me the full path.

**Comment by bogachenko** [comment]
I can't reproduce it, I checked it on Opera, Firefox and even on a virtual machine in the same Firefox browser - nothing. The video frame loads and the movie goes.

**Comment by npn225** [comment]
I just checked it right now myself and found that the issue seems to have completely resolved itself. 

The site really was detecting and preventing adblock just yesterday. Anyway, thanks for your help and attention.

**Comment by npn225** [comment]
> I can't reproduce it, I checked it on Opera, Firefox and even on a virtual machine in the same Firefox browser - nothing. The video frame loads and the movie goes.
> 
> For me on these sites there is only this warning:
> 
> ```
> Note:
> Please do not open Adblock, we found that it will block the player's loading.
> We upgraded the Player. Please click the "Switch To Old Player" button if you still want to use the Old Player.
> This page has pop-up and native ads. Pop-up ads sometimes automatically open a link when you click anywhere on the page.
> If the ads contains porn, violence or other uncomfortable content, please take a screenshot and send to our mailbox : [support@soap2day.net](mailto:support@soap2day.net). We will try to block the malicious ads.
> ```
> 
> There was a pop-up window on one of the mirrors, so I removed it.

Hey bogachenko, 

After some additional tests on Firefox, it seems that the problem only persists when the AdGuard AdBlocker is used. 

When AdGuard is enabled on Firefox, the videos won't play. Ublock Origin seems to be working perfectly fine though. 

I was wondering if you could do another test to see if you could reproduce the problem on Firefox with AdGuard Adblock.

I'm not reopening this issue though since the workaround is to simply use Ublock Origin instead of AdGuard.

**Comment by bogachenko** [comment]
I'll open it as a reminder that I need to do something, I'll check in about 15 hours

**Comment by bogachenko** [comment]
I downloaded the AdGuard AdBlocker browser extension and checked, again nothing. However, I checked with the filter settings (+FFA sheet) by default.

Probably you have too many third-party filter lists connected, check if the site swears at the adblock if you activate only `Base filter`, `Tracking Protection filter`, `Annoyances filter`, `Social media filter` (and optionally `Fuck Fuckadblock`) in the expansion

**Comment by Yuki2718** [comment]
> check you

I can't reproduce either with uBO or AG, video works fine and no request to `wewon.to` on my side.

**Comment by npn225** [comment]
> @npn225
> 
> > When AdGuard is enabled on Firefox, the videos won't play.
> 
> Your problem is in the `||[wewon.to](http://wewon.to)^` filter (from `EasyList` and `Base filter`) blocks the viewing of the movie.
> 
> @Yuki2718 check you

I don't know how you figured this out when you couldn't reproduce my issue but yeah, this solved it.

At first I used the dynamic filtering feature to set `||wewon.to^` and other filters to gray in order to weed out what was wrong. Unfortunately, this didn't work. 

I tried to set them to green but I couldn't and thought the feature to dynamically allow filters was removed. 

After seeing you comment, I read up some more on uBlock and learned that you have to press the 'Ctrl' key when the uBlock drop-down menu is open in order to be able to dynamically allow specific filters and set them to green. 

Thanks for your help and my apologies for wasting everyone's time.

**Comment by bogachenko** [comment]
@npn225 

>I don't know how you figured this out when you couldn't reproduce my issue but yeah, this solved it.

It's probably translation difficulties, but I was ONLY looking for a notification banning the use of an ad blocker, not a false request blocking the viewing of a movie.

>Have thoroughly checked with all other extensions turned off! Have checked both my adblockers individually. With Brave Browser, have also checked with Brave Shields turned off. The site (soap2day) is recognizing the adblockers.
>The site (soap2day) is recognizing the adblockers.

Because you wrote it. 
***
Anyway, you are welcome. If there are similar questions, it is better to ask them by mail - [bogachenkove@gmail.com](mailto:bogachenkove@gmail.com), telegram [@bogachenkove](https://t.me/bogachenkove) or write to reddit [/u/bogachenkove](https://www.reddit.com/user/bogachenkove/).
