### ISSUE TITLE
dropgalaxy.in

### ISSUE THREAD

**Issue by blazesprings** [bogachenko/fuckfuckadblock#239]
### Basic information

**Check the link:** `https://dropgalaxy.in/tmq142h4u0sk`
**Category:** Anti-adblock
**Reported from:** Singapore

### User environment

**Browser:** Chrome  96.xx
**Extension or program:** Ublock Origin 1.38.6
**DNS:** No

**Comment by blazesprings** [comment]
I have updated the filter lists. Still I am seeing the message.

**Comment by bogachenko** [comment]
It is specific to Chrome, everything works for Firefox. I need to do some tests.

**Comment by blazesprings** [comment]
I just checked in FF also, The message appears.

**Comment by bogachenko** [comment]
Update the sheet and try again in Firefox, everything works there like a Swiss watch.

Now about Chrome, I turned off "Safe Browsing", allowed any ads to be displayed in the browser's site settings (I also turned off "the sandbox" function and cleaned cookies, plus I turned off the secure DNS server in the browser settings) and then turned off the uBO ad blocker in general, BUT nothing happened, the site still shows a notification about using the adblock.

I will leave this question open for now, perhaps someday I will return to it.

**Comment by bogachenko** [comment]
@blazesprings Tell me, are you sure that you do not use third-party DNS server? Take a test on the site https://www.dnsleaktest.com/ or on this https://www.perfect-privacy.com/en/tests/dns-leaktest and tell me which DNS server do you use?<br>**I am interested in the ISP column in the table that you will see after passing the test.**
PS: Before passing this test, make sure that the "Safe DNS server" is disabled in your browser settings.

**Comment by blazesprings** [comment]
@bogachenko before doing that test, I am interested to know where is that Safe DNS server? In chrome or in FF?

**Comment by bogachenko** [comment]
@blazesprings In Chrome. Open your browser settings -> Privacy and security -> Security -> Use a Safe DNS-server.

>Btw, I never use any DNS either as an extension or any application.

https://en.wikipedia.org/wiki/DNS_over_HTTPS
