### ISSUE TITLE
imgyvdw.buzz

### ISSUE THREAD

**Issue by gosndka** [bogachenko/fuckfuckadblock#241]
### Basic information

**Check the link:** `http://imgyvdw.buzz/5uewyxoai`
**Category:** Anti-adblock
**Reported from:**  india

### User environment

**Browser:**  Firefox 94.0.1
**Extension or program:** Ublock Origin
**DNS:** No
**Extensions:** IDM

**Comment by gosndka** [comment]
http://imgkoc.buzz/j4pek
 Has been patched, they still show the popup "To disable the ubo" @bogachenko

**Comment by gosndka** [comment]
The fix is not working @bogachenko 
![Capture](https://user-images.githubusercontent.com/92586328/147542881-adda4bf9-29de-4bc1-87cb-1e4aa25e79e4.JPG)

**Comment by bogachenko** [comment]
Please stop pinging me, I see. I am in this thread + I have tracking enabled for my repositories.
And don't upload any images here at all, please.
