### ISSUE TITLE
myanimelist.net

### ISSUE THREAD

**Issue by runboy93** [bogachenko/fuckfuckadblock#243]
### Basic information

**Check the link:** `https://myanimelist.net`
**Category:** Breakage
**Reported from:** Finland

### User environment

**Browser:** Vivaldi 4.3 (Android)
**Extension or program:** Vivaldi adblock
**DNS:**
**Extensions:**

### Additional message

This seems to be problem with mobiles devices only (Android, iOS), basically this happens:
https://www.reddit.com/r/MyAnimeList/comments/r08lnn/anyone_know_how_to_fix_this_cant_click_anything/

When you open website on mobile device and mobile browser, after waiting for while whole screen be grayed out and can't tap anything.

Noticed this host on mobile website, which is not on desktop website: "smartadserver.com"

**Comment by bogachenko** [comment]
Is this happening because of my list?

**Comment by Yuki2718** [comment]
This is indeed cookie consent leftover which can matter only if you partially blocked the prompt. You didn't explain what lists are used on Vivaldi, moreover, AFAIK FFA is only for uBO or AG - Vivaldi's (half-baked) blocker is not supported. This can't be a matter on default uBO settings and already addressed in AG Annoyances. I'll open PR for Fanboy Annoyance.

**Comment by Yuki2718** [comment]
@bogachenko Close the issue, it's not a problem of your list.
