### ISSUE TITLE
viprow.me

### ISSUE THREAD

**Issue by foodog123** [bogachenko/fuckfuckadblock#248]
### Basic information

**Check the link:** `https://en.viprow.me/sky-sports-news-ssn-breaking-sports-news-online-stream-1`
**Category:** Anti-adblock
**Reported from:**  Malaysia

### User environment

**Browser:**  Firefox 94.0.2 64 bit
**Extension or program:**  uBlock Origin 
**DNS:**  No
**Extensions:**  None

**Comment by bogachenko** [comment]
I can't reproduce the anti-adblock problem where it appears.
Give the steps to reproduce and check with the default settings (+ FFA sheet) for uBO

**Comment by foodog123** [comment]
The issues comes and goes. When issue was posted, there was anti-adblock on the listed domain.

But now the sites working as usual. Strange but it has happened on and off before as well.

Will screenshot the issue when it happens again.

**Comment by bogachenko** [comment]
>Will screenshot the issue when it happens again.

No need, just ping me

**Comment by foodog123** [comment]
issue is back, could you have a look?

Cheers.

Link : https://en.viprow.me/sky-sports-news-ssn-breaking-sports-news-online-stream-1

**Comment by bogachenko** [comment]
I was able to reproduce only once, then the problem disappeared. Okay, I'll watch later.

**Comment by foodog123** [comment]
The adblock disables the embed player, but the site works fine.

When you try the link, it should say, 'kindly remove/disable adblock, and reload the page'
![Capture](https://user-images.githubusercontent.com/47375839/145543287-3a7136c2-d279-4d44-9ce0-f52808d5d051.JPG)
.

**Comment by foodog123** [comment]
I managed to isolate the issue that is causing it. 

It is my browser VPN that is causing it.

I am using Windscribe browser VPN
