### ISSUE TITLE
streamonsport.to

### ISSUE THREAD

**Issue by bnff** [bogachenko/fuckfuckadblock#251]
### Basic information

**Check the link:** `https://www.streamonsport.to/`
**Category:** Anti-adblock
**Reported from:** FR

### User environment

**Browser:**  Chrome Version 94.0.4606.81
**Extension or program:** uBlock Origin
**DNS:** 1.1.1.1
**Extensions:** i don't care about cookie

**Comment by bogachenko** [comment]
@bnff Where exactly, in which video frame? There is nothing on the site itself.
