### ISSUE TITLE
hdfilmcehennemi.tv

### ISSUE THREAD

**Issue by BaSsAmMq** [bogachenko/fuckfuckadblock#254]
### Basic information

**Check the link:**  `https://www.hdfilmcehennemi.tv`
**Category:** Anti-adblock
**Reported from:**  Turkey

### User environment

**Browser:**  Google Chrome Version 96.0.4664.93
**Extension or program:**  uBlock Origin
**DNS:**  No

### Additional message
I am using these filter lines to remove the ads of the website.

```
! 2021-12-14 https://www.hdfilmcehennemi.tv
www.hdfilmcehennemi.tv##.money--wide.money
www.hdfilmcehennemi.tv##.pgskn > [href="/pagereklam"]
www.hdfilmcehennemi.tv##.active.money--video.money
www.hdfilmcehennemi.tv##a.money-text
www.hdfilmcehennemi.tv##money money--video active
www.hdfilmcehennemi.tv##+js(ra.js, data-money, div.play-that-video)
```
Of course, you are the expert. 😅

**Comment by bogachenko** [comment]
What you are writing about is an advertisement, not a pop-up window, I will not add it, you have made good rules, but I would add this `||hdfilmcehennemi.*/*.mp4|$media` and then you can ask this Japanese @Yuki2718 to add this Turkish filters to the rules for Adguard.

In the uBO settings, enable the TUR: AdGuard Turkish filter (if you don't have it enabled, there are a lot of good rules for Turkish sites)

**Comment by BaSsAmMq** [comment]
Thanks for the reply I didn't exactly know how to label it as an AD and it is my first comment 😅

**Comment by Yuki2718** [comment]
It seems everything is covered by the Turkish filters and those other TLDs such as .biz, .vip have different structure. Though .tv seems to be switched from .pw, I'll reserve wildcard until we see next switch.

**Comment by bogachenko** [comment]
eg. `hdfilmcehennemi.net`, `hdfilmcehennemi.org` or `hdfilmcehennemi.com` now redirect to `hdfilmcehennemi.tv`
however you still haven't fixed https://github.com/AdguardTeam/AdguardFilters/commit/98d45aa7a4e97c33745018b668b0e5d9945de00f#diff-a4c8ef63acc75c9c2f86ad3631a1ab92cc51d565a789870a9000622cbd3dae89R34
