### ISSUE TITLE
getpaidstock.com

### ISSUE THREAD

**Issue by wasi-master** [bogachenko/fuckfuckadblock#255]
### Basic information

**Check the link:** `https://getpaidstock.com/`
**Category:** Anti-adblock
**Reported from:** Bangladesh

### User environment

**Browser:** Firefox
**Extension or program:** uBlock Origin
**DNS:** Google DNS as main and Cloudfare as backup
**Extensions:** A lot but none that could interfere with this

**Comment by bogachenko** [comment]
Please do not download any images here, including screenshots (at least until I ask for this)

I can not reproduce, one of these rules works for you? 
`||getpaidstock.com/cookie.js$script` or `getpaidstock.com##+js(abort-on-property-read.js, adblockDetector)`

**Comment by wasi-master** [comment]
I just tried revisiting the website and now even I can't reproduce, weird.
