### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by BaSsAmMq** [bogachenko/fuckfuckadblock#257]
### Basic information

**Check the link:**  `https://tr.investing.com/`
**Category:** Anti-adblock
**Reported from:**  Turkey

### User environment

**Browser:**   Google Chrome Version 96.0.4664.110
**Extension or program:**  uBlock Origin
**DNS:**  No
**Extensions:** Non that might interfere

uBlock Origin, Kaspersky Protection, Pop up blocker for Chrome™ - Poper Blocker, Don't Fuck With Paste, SuperCopy, Allow Right Click and Copy, SingleFile, Honey, IDM Integration Module, Tampermonkey, Allow Right-Click, OneTab, Dark Reader, GoFullPage - Full Page Screen Capture, Adobe Acrobat, Join, TinEye Reverse Image Search, Video Speed Controller.

### Additional message
All `*.investing.com` and `www.investing.com` websites show an ad blocker Popup

The Popup
>**We've noticed you're using an ad blocker**
>
>We spend millions of dollars each year so you can access, for FREE, the highest quality real-time quotes and charts. This is made possible only thanks to the advertising on our site.
>
>To continue using Investing.com, please allow this domain on your ad blocker.
>
>**Allow this domain**
>**Subscribe to our Ad-Free version**

**Comment by bogachenko** [comment]
>Pop up blocker for Chrome™ - Poper Blocker
>Kaspersky Protection Plugin
>Tampermonkey

https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions
***
I can't reproduce this issue

**Comment by BaSsAmMq** [comment]
**Short Answer:** Purge all caches and Updating the lists fixed the issue.

At first, I tried to reproduce it using Windows Sandbox but I was unable to reproduce it, then I disabled all my extensions and tried but also that was not helpful even a browser restart didn't fix the problem, but as you said a list update was the solution before that a cache purge was necessary because the "Update now" button was grayed out.

😇👍🏼
