### ISSUE TITLE
acronym24.com

### ISSUE THREAD

**Issue by andreewmat** [bogachenko/fuckfuckadblock#260]
### Basic information

**Check the link:**  `https://acronym24.com/`
**Category:** Breakage
**Reported from:**  Germany

### User environment

**Browser:**  Firefox 95
**Extension or program:**  uBlock
**DNS:**  No
**Extensions:**  only uBlock

### Additional message
With the filter activated, there are some placeholders. With the filter disabled, everything is fine.

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues

Yup.
