### ISSUE TITLE
noticiascripto.site

### ISSUE THREAD

**Issue by gototheskinny** [bogachenko/fuckfuckadblock#263]
### Basic information

**Check the link:** `https://www.peliculasgd.net/raya-ultimo-dragon-2021-mx-bdremux-2160p-4k-latino-googledrive/`
**Category:** Anti-adblock
**Reported from:** Turkey

### User environment

**Browser:** Google Chrome v97.0.4692.71 x64 Windows 10 21H2
**Extension or program:** uBlock Origin
**DNS:** Yandex DNS/Adguard DNS(not works even if you disable uB.)
**Extensions:** Privacy Badger, FastForward (shortner bypasser), SponsorBlock

### Additional message

 If you go to this link and select public link it forwards to this site: https://drivelinks.me/ than you click "haz clic aqui" button this forwards you to this cancer site: https://noticiascripto.site/. When using Adguard DNS(what i normaly use) this site is not letting you to get what you want. I switched to Yandex DNS, disabled uBo in this condition everything works well. I have the Spa/Por filters enabled doesn't works. Obviously this is so annoying. Could you guys fix or bypass this cancer site ? I saw someone posted an issue like this back in last may it got solved.

**Comment by gototheskinny** [comment]
https://github.com/uBlockOrigin/uAssets/issues/11378
I tried and now it's not saying disable Adblock. Thanks!

**Comment by gototheskinny** [comment]
> please don't upload any pictures here 

Got it. Thanks for the fix.

**Comment by krystian3w** [comment]
Repo no support upload photos, users have fake number folder for photos.

Also you can use matches-path to block github buttons only in your repo.
