### ISSUE TITLE
babiato.co

### ISSUE THREAD

**Issue by akn19** [bogachenko/fuckfuckadblock#265]
### Basic information

**Check the link:** `https://babiato.co/`
**Category:** Popup
**Reported from:** indonesia

### User environment

**Browser:** Chrome v97.0.4692.99
**Extension or program:** uBlock Origin 
**DNS:** No
**Extensions:** uBlock Origin

**Comment by bogachenko** [comment]
Give steps to reproduce. What is happening and on which page (full address)?
The "Additional message" section (in the issue markup) is designed specifically for this.
