### ISSUE TITLE
elektroupdate.com

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#269]
### Basic information

**Check the link:**  `https://safe.elektroupdate.com/2019/04/tips-and-advice-about-desktop-computers.html`
**Category:** Anti-adblock
**Reported from:**  Indonesia

### User environment

**Browser:**  Google Chrome Versi 98.0.4758.82 (Build Resmi) (64 bit)
**Extension or program:**  uBlock Origin 1.41.2
**DNS:**  -
**Extensions:**  -

**Comment by bogachenko** [comment]
How did you get to this site? Give full path
