### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by Pocarai** [bogachenko/fuckfuckadblock#270]
**Check the link:** `https://dropgalaxy.com/u6zweoaliyky`
**Category:** Anti-adblock
**Reported from:** Philippines
### User environment

**Browser:** Kiwi Browser 98.0.4758.106
**Extension or program:** uBlock Origin 1.41.2
**DNS:** Inside in AOSP Private DNS: Automatic
**Extensions:**  No

### Additional message

 After I click `create download` Link. They detect adblocker whether what their visitors do with adblocker

**Comment by bogachenko** [comment]
Firstly, the link you gave me didn't work, for some reason I got a notification about the deleted file (Now everything is working, I changed the domain from `com` to `in`, the link is working).

Secondly, privacy and Fuck Fuckadblock are not compatible. Don't use privacy-protecting DNS and out-of-the-box ad-blocking browsers, which Kivi belongs to, with my list.

Third, don't create new problems when they already exist https://github.com/bogachenko/fuckfuckadblock/issues?q=dropgalaxy.

**Comment by bogachenko** [comment]
@Pocarai Do these rules work for you?

```
@@||vlitag.com^$xmlhttprequest,image,script,subdocument,domain=dropgalaxy.com
@@||dsh7ky7308k4b.cloudfront.net^$script,domain=dropgalaxy.com
@@||uniconsent.com^$xmlhttprequest,script,domain=dropgalaxy.com
@@||adform.net^$xmlhttprequest,script,domain=dropgalaxy.com
```
