### ISSUE TITLE
papunika.com

### ISSUE THREAD

**Issue by LordDeimos666** [bogachenko/fuckfuckadblock#271]
### Basic information

**Check the link:** `https://papunika.com/`
**Category:** Anti-adblock
**Reported from:** Italy

### User environment

**Browser:** Firefox 97.0.1 
**Extension or program:** uBlock Origin 1.41.6
**DNS:** 1.1.1.1 / 1.0.0.1 / 9.9.9.9 
**Extensions:** uBlock Origin only active at the moment ot test

### Additional message
Just opening the link the banner on the sides of the page appear.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/936b6654d35fb34dd76bd3ec5f432ff19cb1897b

report directly at uBO Assets
https://github.com/uBlockOrigin/uAssets/issues

**Comment by bogachenko** [comment]
@mapx- directly on reddit, you (not you personally, but the team) delete every mention of my repository (user messages are deleted, and under the deleted message you refer to uAssets) it's okay, although it's strange, why such hostility? But this is my repository, why are you allowing yourself to do this here?

**Comment by mapx-** [comment]
The goal is helping more users which are not understanding anti adblocking issues are fixed in uBlock filters list.

**Comment by bogachenko** [comment]
What do I care about most users? You fixed this problem in your repository (you don’t even have to link in [the comment](https://github.com/uBlockOrigin/uAssets/commit/936b6654d35fb34dd76bd3ec5f432ff19cb1897b#diff-797b6a4651b26bae2fe5c1356907cab9f4293a9d66af9bae981788d918def1b2R948), I won’t be offended), but advertising like this is brazen.
