### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by MF-Debug** [bogachenko/fuckfuckadblock#275]
### Basic information

**Check the link:** `https://www.apkmirror.com/apk/nekki/shadow-fight-3/shadow-fight-3-1-27-3-release/shadow-fight-3-rpg-fighting-1-27-3-2-android-apk-download/`
**Category:** Anti-adblock
**Reported from:** Bangladesh

### User environment

**Browser:** Firefox Nightly 99.0a1 (64-bit)
**Extension or program:** uBlock Origin
**DNS:** 1.1.1.1
**Extensions:** uBlock Origin only while testing this

### Additional message

The anti-adblock message appears not only for the given link, also for any link from the website before downloading any apks.

**Comment by bogachenko** [comment]
I can't reproduce it, reset the default settings in Firefox and in uBO, and also check with the tracking block disabled in Firefox.

**Comment by DraconicNEO** [comment]
> I can reproduce it if I only disable - `uBlock filters`, because there is a rule there `apkmirror.com#@#.gooWidget` that removes the antiadblock. Anyway, go back to the default settings.

Hi I have ublock Filters enabled but it still has this issue so I think they might've changed something.

**Comment by bogachenko** [comment]
I can't reproduce the fix that Gypsy added works for me. There is no anti-adblock https://github.com/uBlockOrigin/uAssets/commit/22f6e5019f026d5823754b728c06b085ede1c1a2
