### ISSUE TITLE
exey.io

### ISSUE THREAD

**Issue by goooglefc** [bogachenko/fuckfuckadblock#277]
### Basic information

**Check the link:** `https://exe.io/8fKMdbkf`
**Category:** Anti-adblock
**Reported from:** Asia

### User environment

**Browser:** Chrome Version 98.0.4758.102
**Extension or program:** Adguard
**DNS:** 1.1.1.1
**Extensions:** Checked without addons

### Additional message

note:NSFW link.
After "Click Here to continue"
next page you get this
"Please disable Adblock to proceed to the destination page."

**Comment by bogachenko** [comment]
Dude I read what you wrote here https://github.com/bogachenko/fuckfuckadblock/issues/181#issuecomment-1052755805, why are you opening duplicates?

**Comment by bogachenko** [comment]
Can not reproduce. You did not specify what IP you have, Asia is a loose concept. It could be India, it could be Japan, it could be China or Korea. Maybe the problem is in the language sheet that you connected. Check with filters - Adguard Base filter, Adguard Tracking Protection Filter and Fuck Fuckadblock.

Also, the Chrome browser has a built-in ad blocker, it must be disabled.

**Comment by goooglefc** [comment]
> Dude I read what you wrote here [#181 (comment)](https://github.com/bogachenko/fuckfuckadblock/issues/181#issuecomment-1052755805), why are you opening duplicates?

Sorry for that

**Comment by goooglefc** [comment]
> Can not reproduce.
> 
> > Reported from: Asia
> 
> You did not specify what IP you have, Asia is a loose concept. It could be India, it could be Japan, it could be China or Korea. Maybe the problem is in the language sheet that you connected. Check with filters - Adguard Base filter, Adguard Tracking Protection Filter and Fuck Fuckadblock. Also, the Chrome browser has a built-in ad blocker, it must be disabled. Can you test this in another browser too?
> 
> > DNS: 1.1.1.1
> 
> Check in the hosts.txt file you didn't configure anything?

Thanks! Its now working.
