### ISSUE TITLE
artunnel57.com

### ISSUE THREAD

**Issue by ElissonRodrigues** [bogachenko/fuckfuckadblock#278]
### Basic information

**Check the link:** `https://artunnel57.com`
**Category:** Anti-adblock
**Reported from:** Brazil 

### User environment

**Browser:** Kiwi Browser v98.0.4758.106
**Extension or program:** Only Adguard beta
**DNS:** Cloudflare (1.1.1.1)
**Extensions:** Adguard beta, SponsorBlock, HTTPS Everywhere, Popup Blocker (strict)

### Additional message

the page opens normally, but after a few seconds it redirects to another location, which tells you to turn off the ad blocker.

**Comment by bogachenko** [comment]
> Popup Blocker (strict)
> SponsorBlock

No need, since you have Adguard installed. 

>HTTPS Everywhere

A useful stuff, but browsers already have a similar feature by default.

**Comment by ElissonRodrigues** [comment]
> Popup Blocker (strict) 

The adguard could not block all popups, This extension blocks everyone. 

> HTTPS Everywhere

Yes, I like to use this extension, but I plan to remove it in the future.

> ```https://artunnel57.com```

I cleared the cache, but it still keeps redirecting to: ```https://artunnel57.com/adblock/adblock.php```

**Comment by bogachenko** [comment]
>I cleared the cache, but it still keeps redirecting to: https://artunnel57.com/adblock/adblock.php

Are you using Adguard extension or Adguard for Android?


> The adguard could not block all popups, This extension blocks everyone.

You can just report problem sites here and you won't need this app. Adguard relies on filter lists, no site in the list = no filtering. Your extension blocks everything by mask. Although it's up to you.

**Comment by ElissonRodrigues** [comment]
>Are you using Adguard extension or Adguard for Android?

I am using the extension (<a href="https://chrome.google.com/webstore/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl">Web Store</a>)

>You can just report problem sites here and you won't need this addon.

Right, thanks.

**Comment by bogachenko** [comment]
Are you sure? I just rechecked and everything works perfect for me. Checked on Firefox Mobile and Kiwi everything works fine everywhere.

**Comment by ElissonRodrigues** [comment]
Yes. It didn't work. But I got it with these rules:

*$csp=script-src 'self' 'unsafe-eval' http: https:,domain=artunnel57.com|kituweh.xyz
@@*$generichide,domain=artunnel57.com|kituweh.xyz

I have a fork, of your project, very nice.

**Comment by ElissonRodrigues** [comment]
Yes. It didn't work. But I got it with these rules:

```*$csp=script-src 'self' 'unsafe-eval' http: https:,domain=artunnel57.com|kituweh.xyz```

```@@*$generichide,domain=artunnel57.com|kituweh.xyz```

I have a fork of your project. Thanks for keeping it.
![Screenshot_20220228-052250_Kiwi Browser](https://user-images.githubusercontent.com/25101186/155949125-2feaf5b7-6904-48b3-ac04-5c0ac32ec679.jpg)

**Comment by bogachenko** [comment]
You just banned inline scripts with your rule, If this site will be updated and on the site there will be something else beyond the bite of the inline script, your rule breaks it, dangerous. @Yuki2718 check the site, can you reproduce? 

PS: **Do not upload any images here.**

**Comment by ElissonRodrigues** [comment]
It worked without any problem. 

mapx- Made a commit with a better solution:
https://github.com/uBlockOrigin/uAssets/commit/7a73278af90d3d108830e2af2bc049f9b37b3a1b

**Comment by Yuki2718** [comment]
Adding
```
@@||artunnel57.com^$generichide
artunnel57.com#%#//scriptlet("abort-on-property-read", "onload")
```
(the second can be replaced with `artunnel57.com##+js(abort-on-property-read.js, onload)`) and no anti-adb either on desktop or Android, looks to be a matter of OP side.

> mapx- Made a commit with a better solution:

The same target, probably the reason for `nosiif` was to reduce chance of breakage (aborting `window.onload` is risky, but not as blocking whole inline-script).
