### ISSUE TITLE
dailywire.com

### ISSUE THREAD

**Issue by gir489** [bogachenko/fuckfuckadblock#28]
https://www.dailywire.com/news/poll-trump-losing-to-biden-warren-by-double-digits

It's not actually an issue with fuckfuckadblock, it's actually an issue with presstheattack. But because that one has issues disabled for some reason, I'm posting it here.

https://i.imgur.com/RZLeXke.png

**Comment by bogachenko** [comment]
19 hours ago could reproduce it, but I had no time for corrections, left it, thought then I will look. Now everything seems to work by itself.
