### ISSUE TITLE
chd4.com

### ISSUE THREAD

**Issue by tazihad** [bogachenko/fuckfuckadblock#281]
Ad block detecting for last 2 days.
They block whole page and show me an image.

This is the script that is run

```
(function detectAdblock(callback) {  
  var addblocktype = 295000;
  var flaggedURL = 'https://doubleclick.net/9314750086.js';
   // console.log("-- doubleclick.net")
    if (window.fetch) {
      var request = new Request(flaggedURL, {
        method: 'HEAD',
        mode: 'no-cors',
      });
      fetch(request)
        .then(function(response) {
          if (response.status === 404) {
            callback(false);
          } else {
            callback('unknown (' + response.status + ')');
          }
        })
        .catch(function(error) {
          callback(true);
        });
    } else {
      var http = new XMLHttpRequest();
      http.open('HEAD', flaggedURL, false);

      try {
        http.send();
      } catch (err) {
        callback(true);
      }

      if (http.status === 404) {
        callback(false);
      } else {
        callback('unknown (' + http.status + ')');
      }
    }
  })(function (detected) {
    
   if (detected==true){
	   //console.log("sure detected hash 295000 " + detected)
	   document.body.innerHTML= "<img src=ano5.png> ";
   }else{
	   //console.log("not sure doubleclick.net" + detected)
   }


  })




```

**Comment by bogachenko** [comment]
`crazyhd.com,chd4.com##+js(abort-on-property-read.js, detectAdBlock)` Does it work for you?

**Comment by tazihad** [comment]
both not working. this is a private torrent tracker.

**Comment by bogachenko** [comment]
I know this is a private tracker, could you send me your login and password to my email - bogachenkove@gmail.com or comment it out in the next your message (comments are not visible to other users), when I bypass the anti-adblock you will change the password.
Also, what kind of ad blocker and browser do you have installed, is a third-party DNS server enabled and your operating system?

**Comment by bogachenko** [comment]
I can't create a profile, because I don't have Facebook, and it says to post a registration post ~and pray to allah~ that someone invited me there.

**Comment by NichirinSword** [comment]
Any solution for this site? I can't get into this site without disabling ublock origin. There are many annoying ads in this site that's why I hate to disable adblocker.

**Comment by bogachenko** [comment]
You can read what I need to reproduce the problem and how it can be conveyed. No login and password = keep your privacy and sit with anti-blocking.

**Comment by bogachenko** [comment]
~Thank you for sharing your account from this site to solve your problem.~ 
@tazihad @NichirinSword I found an account from this crappy site and fixed the anti-adblock, check it should work now.
<!--

https://www.freeaccounts.bi3.shop/2022/02/chd4com-x35-accounts.html

avoidridz:1234
frankensteinporag:Porag76724
Lalgulapi:55542
taimul:905926
shaikhmonir:13579280
Lalgulapi:55542
hridoy947bd:hridoy947BD
goldenboyfaysal:faysal302909
shaikhmonir:13579280
wakilrahman:248773
sky420pe:SKY420PE
alamin1789:345980
Symphonye12:601643
oparthiv007:3_5/*k+`->}UUo)q}J>MIj-5J@L,,{
Tahmid60:2760
injam007:333monju698
ahmedsayeem00:770125
hossainanowar72:891620
jahangirxp22:519652
shuuvo9090:62079
roksan:317142
crazyhdanik:109903
masudrahman1:masud98765
imransaju56:0056saju
sarwer:17087
soyodsafim:safim@simu
Atekreza:01832703946
Russell_khan:123456
satadal:Bhoumick#1991
MInayeem:364325
Tusharsabbir:457741
emonsikder:07654321

->
