### ISSUE TITLE
oploverz.asia

### ISSUE THREAD

**Issue by rheznendra** [bogachenko/fuckfuckadblock#283]
### Basic information

**Check the link:** `https://oploverz.asia`
**Category:** Popup
**Reported from:** Indonesia

### User environment

**Browser:** Vivaldi (5.1.2567.57)
**Extension or program:** Adguard

### Additional Information
It shows blank white box pop up like [this](https://prnt.sc/J43twqyOa6y_) and also domain often changed usually every 3-5 months (probably got block by government). Ex previous domain : `oploverz.bz`, `oploverz.fan`

**Comment by bogachenko** [comment]
Don't use screenshots at all. Use words.
Have a good day.

**Comment by bogachenko** [comment]
I recommend adding the rule against advertising `*.gif|$image,domain=oploverz.*|194.163.152.200|65.108.132.145`

**Comment by rheznendra** [comment]
new site `oploverz.co.in`

**Comment by bogachenko** [comment]
The pop-up window is removed by the old rule, but I wrote above about annoying gif images
