### ISSUE TITLE
nontongp.xyz

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#284]
### Basic information

**Check the link:**  `https://www.nontongp.xyz/p/live-streaming-motogp_8.html`
**Category:** Breakage
**Reported from:**  Singapore

### User environment

**Browser:**  98.0.1 (64-bit)
**Extension or program:**  Ublock Origin Latest
**DNS:**  -
**Extensions:**  -

### Additional message
live stream not playing

**Comment by bogachenko** [comment]
I can't click play with adblock turned off, the problem is not on my list. Where did you get this website? It looks like a dummy website

**Comment by rigaz29** [comment]
![gp1](https://user-images.githubusercontent.com/5234767/159150028-d869f1f2-f5fe-4400-8b6d-38c1a3288b4b.png)
can play on private tab

**Comment by rigaz29** [comment]
<html>
<body>


// Work with JSON data here
--
  | if (data.countryCode == "ID" \|\| data.countryCode == "MY" \|\| data.countryCode == "SG"){
  | if (data.countryCode == "ID" \|\| data.countryCode == "MY" \|\| data.countryCode == "SG"){
  | tele()
  | document.getElementById("info").innerHTML = "DANA DARI IKLAN SAYA GUNAKAN UNTUK MAINTENANCE SERVER, SAAT INI HANYA 1% PENGUNJUNG YANG KLIK IKLAN!!! jangan lupa matikan ADBLOCK dan VPN";
  | }
  | else {
  | tele()
  | document.getElementById("info").innerHTML = "please turn off ADBLOCK and VPN";
  | }
  | }
  |  
  | else {
  | document.getElementById("vid").src= ""


</body>
</html>

can't be played outside sg, id, my

**Comment by bogachenko** [comment]
Damn, I can't reproduce (it seems geolock is still here, the frame does not appear without a Singapore IP) because of the EasyPrivacy filter, but `@@||pro.ip-api.com^$xhr,domain=www.nontongp.xyz` this fixed it and now I can see the frame.

I can reproduce the frame, even with this inscription `DANA DARI IKLAN SAYA GUNAKAN UNTUK MAINTENANCE SERVER, SAAT INI HANYA 1% PENGUNJUNG YANG KLIK IKLAN!!! jangan lupa matikan ADBLOCK dan VPN`, which subscriptions do you use? Especially regional ones?

**Comment by rigaz29** [comment]
just default of ublock origin
yes, the frame can reproduce with this filter `@@||pro.ip-api.com^$xhr,domain=www.nontongp.xyz`

**Comment by bogachenko** [comment]
>just default of ublock origin

I don't know what regional filters are enabled by default for singapore, i didn't find it in uBO settings.

>  yes, the frame can reproduce with this filter @@||pro.ip-api.com^$xhr,domain=www.nontongp.xyz

Okay, good. You to @Yuki2718 or @ryanbr

**Comment by Yuki2718** [comment]
As far as I could find, all streaming are from `nontongp.xyz` so added the exception only for this domain.

**Comment by bogachenko** [comment]
I wrote a post scriptum **for the future**, they change domains. there is a redirect from `com` to `xyz`. spot it soon and `xyz` will fall off

**Comment by Yuki2718** [comment]
> Why didn't you add this for adguard too? 

Because AG Tracking Protection doesn't block `ip-api.com` in the first place and I hesitate to add tracker that has beyond a certain amount of false positive.
