### ISSUE TITLE
Does not work with AdBlock Plus anymore [Bug]

### ISSUE THREAD

**Issue by yodaluca23** [bogachenko/fuckfuckadblock#286]
The filter list no longer works with AdBlock Plus, I did research and I believe this is due to an AdBlock Plus update may you please make it work again?

![image](https://user-images.githubusercontent.com/67206487/159383163-e812d56e-fefc-4e92-91d9-c78e292cdad7.png)

**Comment by bogachenko** [comment]
It never worked with Adblock Plus.

Read https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock
and especially this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#adblock-and-adblock-plus
