### ISSUE TITLE
Issue with some shortlinks

### ISSUE THREAD

**Issue by MrJktra** [bogachenko/fuckfuckadblock#289]
Hi,

When i turn on this list I can't download anymore from psarips website because the download links are stuck on "Getting link" after the countdown ends.

**Comment by bogachenko** [comment]
Already fixed in https://github.com/bogachenko/fuckfuckadblock/issues/288

**Comment by MrJktra** [comment]
> Already fixed in #288 And please post link examples for the future.

https://skincarie.com/HlmxOL?
