### ISSUE TITLE
upi.com

### ISSUE THREAD

**Issue by gir489** [bogachenko/fuckfuckadblock#29]
`https://www.upi.com/Top_News/World-News/2019/10/25/Eight-Russian-soldiers-killed-on-a-base-in-Siberia/3861572012335/`

Seems to be detecting AdGuard then not loading the article. If I disable AdGuard, I can read the article fine.

<details><summary><b>Screenshot 1:</b></summary>

![image](https://user-images.githubusercontent.com/7742541/67587223-67dc8f00-f721-11e9-9a6d-a2a11c20c267.png)

</details>

<details><summary><b>Screenshot 2:</b></summary>

![image](https://user-images.githubusercontent.com/7742541/67587232-6e6b0680-f721-11e9-8543-42de0970646e.png)
</details>

**Comment by bogachenko** [comment]
I can't reproduce it. Turn off subscriptions in turn to find out which breaks the article.
