### ISSUE TITLE
irisbuddies.ml

### ISSUE THREAD

**Issue by hackyit1951** [bogachenko/fuckfuckadblock#290]
### Basic information

**Check the link:** `https://www.irisbuddies.ml`
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser**: Microsoft Edge Chromium 99.0.1150.46 x64
**Extension or program**: uBlock Origin
**DNS**: Google Public DNS 8.8.8.8
**Extensions**: ViolentMonkey with f*ck f*ckadblock from https://github.com/Mechazawa/FuckFuckAdblock 

### Additional message

this site uses a different script which is worse than the others: `https://adregain.ru/unblock/`
Screenshot: `https://i.postimg.cc/g2GKJjmj/screenshot.jpg`
(sorry my bad english)

**Comment by bogachenko** [comment]
(this does not apply to this issue) Delete the script that you use in violentmonkey and read https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions
