### ISSUE TITLE
komikcast.com

### ISSUE THREAD

**Issue by rheznendra** [bogachenko/fuckfuckadblock#294]
### Basic information

**Check the link:** `https://komikcast.com/komik/the-worlds-best-engineer/`
**Category:** Breakage
**Reported from:** Indonesia

### User environment

**Browser:** Vivaldi (5.1.2567.73)
**Extension or program:** Adguard

### Additional message

fuckfuckadblock somehow removing `.visited` class on opened chapter link, for example if i opened Chapter 32.2 it should has blue background instead of grey/black or whatever that color. I notice this problem since last week. Previously never happend.

**Comment by bogachenko** [comment]
I am getting this error.

>Access was denied Error code
>You do not have access to komikcast.com.
>The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.

**Comment by rheznendra** [comment]
Is using web proxy can help bypassing this geolock and help you develop? I don't really know much about how this geolock work.
But if i use web proxy from `https://www.hidemyass.com/proxy` and select the Czech Republic for the server, i can manage to open the site, and if i choose US or other country listed on the server it's not work.

**Comment by bogachenko** [comment]
already using it, man. already. update the list, now it should work fine
