### ISSUE TITLE
adinserter.pro

### ISSUE THREAD

**Issue by DrGekt0r** [bogachenko/fuckfuckadblock#296]
### Basic information

**Check the link:** `https://adinserter.pro/documentation`
**Category:** Anti-adblock
**Reported from:** Czech Republic
### User environment

**Browser:** Librewolf 98.0.2-1
**Adblocker:** uBlock Origin 1.42.0
**Extensions:** Audio Equalizer, Authenticator, BetterTTV, Bitwarden, CanvasBlocker, Dark Reader, FastForward, LibreWolf Updater, Return Youtube, Disloke, Simple Translate, Song ID, SponsorBlock, Stylus, Video Speed Controller, Web Translate
**DNS:**  No

**Comment by bogachenko** [comment]
Please don't upload screenshots of anything here, use words.

Off-topic, If you have an ad blocker, uBO or AdGuard installed, then the SponsorBlock extension is not needed.

**Comment by DrGekt0r** [comment]
> Please don't upload screenshots of anything here, use words.
> 
> Off-topic, If you have an ad blocker, uBO or AdGuard installed, then the SponsorBlock extension is not needed.

Why? SponsorBlock skips in-video integrations made by the content creator), adblocker blocks only Youtube (Google) ads

**Comment by DrGekt0r** [comment]
Just checked the site, the issue is fixed now. Thank you for a quick fix @bogachenko

**Comment by krystian3w** [comment]
I agree to don't disable SP if Bogachenko no have evidence to break injected json-prune.

uBo rejected import SP function.
In AdGuard maybe works replace if someone are have knowledge how cut few seconds by use replace.

**Comment by Yuki2718** [comment]
This can not be triggered if you sticked with uBO default filter lists. It's triggered means either
1. You have non-default list.
2. Your regional list includes a bad filter
3. Something is interferring (e.g. other extensions)
