### ISSUE TITLE
anidub.club

### ISSUE THREAD

**Issue by DrGekt0r** [bogachenko/fuckfuckadblock#297]
### Basic information

**Check the link:** `https://online.anidub.club/anime/full/11546-svjaz-princess-povtornoe-pogruzhenie-tv-2-princess-connect-redive-tv-2-01-iz-13.html`
**Category:** Breakage
**Reported from:** Czech Republic

### User environment

**Browser:** Librewolf 98.0.2-1
**Adblocker:** uBlock Origin 1.42.0
**Extensions:** Audio Equalizer, Authenticator, BetterTTV, Bitwarden, CanvasBlocker, Dark Reader, FastForward, Gesturefy, LibreWolf Updater, Return Youtube Dislike, Simple Translate, Song ID, SponsorBlock, Stylus, Video Speed Controller, Web Translate, Windscribe
**DNS:** None

### Additional message

When I turn the adblock on I can't watch the video (it doesn't buffer at all) and change the quality. When I turn it off, everything works just fine

**Comment by DrGekt0r** [comment]
Thank you for a quick fix @bogachenko

**Comment by DrGekt0r** [comment]
@bogachenko UPD: It was fixed, but now I can't change the quality again: but it's not like last time, now I see the sign "HD blocked - Adblock Detect".
UPD2: This issue sometimes appears, sometimes not, so I know that you don't want anybody to post images here, but just to show what I see I'll leave a link: https://imgur.com/a/AXai5b3

**Comment by bogachenko** [comment]
I'll take a look later. The site behaved strangely, I also sometimes lost the opportunity to choose the quality, but then everything worked.

**Comment by bogachenko** [comment]
I can't reproduce it now

**Comment by DrGekt0r** [comment]
> I can't reproduce it now

Just opened the link and reproduced it, maybe refresh the site many times

**Comment by bogachenko** [comment]
everything works fine for me. the site is Russian, try with a regional subscription. Товарищ

**Comment by DrGekt0r** [comment]
> everything works fine for me. the site is Russian, try with a regional subscription. Товарищ

Already tried it without a VPN, see the same thing. Maybe I can give you my uBlock backup so you can reproduce? Можем, кстати, перейти на русский

**Comment by bogachenko** [comment]
Попробую позже ещё раз, на компьютере и телефоне не могу воспроизвести. Если кинешь резервную копию, то кидай на pastebin.com (выстави там неделю, как срок действия пасты, не надо захламлять и без того полный мусора сайт).

**Comment by DrGekt0r** [comment]
Так, Pastebin не дает мне создать Public или Unlisted paste, только Private. Поэтому предалагаю создать аккаунт с временной почтой, дать тебе логин и пароль и таким образом скинуть резервную копию

**Comment by DrGekt0r** [comment]
@bogachenko Создал аккаунт и paste, могу прислать логин:пароль на почту или куда будет удобнее

**Comment by bogachenko** [comment]
Как понять не даёт создать ~,что пишет~?
В настройках uBO заходишь, в первой вкладки этих настроек, в самом низу будет пункт "резервное копирование в файл", поскольку у тебя фаерфокс, наверняка файл сохранился в папке "загрузки", открываешь эту папку и этот файл и все содержимое клавишами копировать ctrl±a и ctrl+c сохраняешь это все в буфер обмена. Потом заходишь на pastebin.com и на самой главной странице будет поле "New paste", в него комбинацией клавиш ctrl+v вставляешь из буфера в это поле. Листаешь ниже этого поле, будет настройка "Paste Expiration"ставишь "1 Week". Все. И нажимаешь большую белую кнопку на которой скучным жирным текстом написано "Create New Paste"

**Comment by DrGekt0r** [comment]
Так как скриншоты ты не любишь, вот что пишет мне Pastebin при попытке создать paste:
Pastebin’s SMART filters have detected potentially offensive or questionable content in your paste.
The content you are trying to publish has been deemed potentially offensive or questionable by our filters, because of this you’re receiving this warning.
This paste can only be published with the visibility set to "Private".

**Comment by bogachenko** [comment]
А блять, все верю. Это из за названия моего фильтра. Лол.
Проверю пока без резервной копии (позже) , если не получится, то вставить все сюда, объясню как.

**Comment by DrGekt0r** [comment]
Окей, сюда вообще можно и текстом, и .txt залить

**Comment by bogachenko** [comment]
Не надо ничего сюда заливать, особенно загружать файлы. Любые. Если понадобится, только текстом, соблюдая разметку конечно же

**Comment by DrGekt0r** [comment]
Без проблем, как удобнее - так и сделаю

**Comment by bogachenko** [comment]
Я могу воспроизвести проблему, только если добавлю в Мои Фильтры:
```
||stats.anidub.life/vast.php$xhr,domain=online.anidub.club,important
online.anidub.club#@#+js(abort-on-property-read, adblock)
```
В иных случаях проблема не возникает. Если ты подписан на стандартные фильтры uBO + RU AdList + FFA и больше ничего, то у тебя не должно быть этой проблемы. Если же ты подписан на ещё что то, то необходимо протестировать с настройками по умолчанию для uBO и желательно не на васянском браузере.

**Comment by DrGekt0r** [comment]
Ну вот, зашел на сайт, теперь все работает, видимо из-за твоего fix'а @bogachenko  (или нет, так как в logger'е нашел "@@||stats.anidub.life/vast.php|$xmlhttprequest,domain=anidub.club|anidub.com|anidub.life|imasdk.googleapis.com|loveanime.live|myanime.online|rusanime.ru" от Ru Adlist, горящее зеленым). В любом случае, огромное спасибо тебе заприложенные усилия и потраченное время

**Comment by bogachenko** [comment]
А если `@@||anidub.*/vast.php|$xmlhttprequest,badfilter` добавить в Мои фильтры, то не работает?

**Comment by DrGekt0r** [comment]
Для начала, отключив Ru Adlist - снова не могу менять качество.


> А если `@@||anidub.*/vast.php|$xmlhttprequest,badfilter` добавить в Мои фильтры, то не работает?

Неа, не работает @bogachenko  :(

**Comment by bogachenko** [comment]
Отключать я не просил, я лишь просил добавить в мои правила и Counters убрать тоже не надо, против Яндексо-параши хорошо помогает.

PS: ах да он не швед, это норвежец

**Comment by DrGekt0r** [comment]
> Отключать я не просил, я лишь просил добавить в мои правила и проверить, так же и Counters удалять тоже не надо, против Яндексо-параши хорошо помогает.
> 
> PS: ах да он не швед, это норвежец

Так я Counters давно уже убрал, они много лишнего режут, Annoyances хватает. 
И как это не отключать, в чем смысл тогда? Ну да ладно, проверил не отключая, ничего не изменилось, менять качество могу.
Все, что горит зеленым в logger'е с правилом в My filters: твое @@|http*:*/player/js/anidub-ad2.js$script, @@||imasdk.googleapis.com/js/core/bridge*.html$domain=~spotify.com от Adguard base, @@||stats.anidub.life/vast.php|$xmlhttprequest,domain=anidub.club|anidub.com|anidub.life|imasdk.googleapis.com|loveanime.live|myanime.online|rusanime.ru и @@/adfox.js|$xmlhttprequest,1p,domain=anidub.club|anidub.com|anidub.life|loveanime.live|myanime.online|rusanime.ru оба от Ru Adlist,
UPD: Неважно так неважно, еще раз спасибо

**Comment by bogachenko** [comment]
Смысл в том, чтобы проверить, что и без моего недавнего правила, можно было меня качество, т.к исключение для этого запроса, который триггерил антиадблок, уже было добавлено RuAdList (добавил для автономности от этого листа).
Проблема, я думаю, была в злоупотреблении подписками, которые ты благополучно исправил.

**Comment by DrGekt0r** [comment]
> Смысл в том, чтобы проверить, что и без моего недавнего правила, можно было меня качество, т.к исключение для этого запроса, который триггерил антиадблок, уже было добавлено RuAdList (добавил для автономности от этого листа). Проблема, я думаю, была в злоупотреблении подписками, которые ты благополучно исправил.

Теперь понял, благодарю за пояснение. Anyway, все хорошо, что хорошо заканчивается)
