### ISSUE TITLE
YouTube Issues

### ISSUE THREAD

**Issue by gir489returns** [bogachenko/fuckfuckadblock#298]
IDK if this is an edge case of YouTube adding new ads and AdBlocker just hasn't gotten around to compensating for them yet, but YouTube keeps fucking showing me ads and it's very annoying. Can you look into it? I have this script and AdBlocker with stock + annoyances on.

**Comment by bogachenko** [comment]
How does youtube advertising relate to my list?

**Comment by gir489returns** [comment]
> How does youtube advertising relate to my list?

I knew you were gonna ask that. This is trying to stop ad blocking. Sounded right up your ally?

**Comment by bogachenko** [comment]
>Sounded right up your ally?

Nope. I only provide access to the sites.
***
>AdBlocker

which one exactly? uBO or Adguard?

**Comment by gir489returns** [comment]
I'm using AdGuard.

**Comment by bogachenko** [comment]
Adguard - the program or browser extension?

**Comment by gir489returns** [comment]
Yeah I already did and there's 8 other people complaining about it already, hahahahaha.

**Comment by bogachenko** [comment]
For the rest of the questions what? Extension or program? Which browser and its version, which operating system?
On Windows 10, in the Firefox 98 Browser + Adguard extension v4.0.141 with Base Filter, Traking Protection Filter, Annoyances Filter and my list - Fuck Fuckadblock (which does not relate to YouTube in any way), I cannot reproduce your problem.
