### ISSUE TITLE
ac-mo.com and ventax.net

### ISSUE THREAD

**Issue by PutterPlace** [bogachenko/fuckfuckadblock#30]
http://ac-mo.com/NKV5sk
http://ventax.net/jBBO

Both of these seem to be using FuckAdBlock, but not being taken care of by fuckfuckadblock. Be careful, as these sites contain ads that are NSFW.

<details><summary>Screenshot 1 (ac-mo.com)</summary>
<p>

![ac-mo.com](https://user-images.githubusercontent.com/20749449/68563937-cb023d00-0414-11ea-8ec9-47c5216f6675.png)

</p>
</details>

<details><summary>Screenshot 2 (ventax.net)</summary>
<p>

![ventax.net](https://user-images.githubusercontent.com/20749449/68563942-cfc6f100-0414-11ea-82ad-0de16a7f59c3.png)

</p>
</details>

**Comment by bogachenko** [comment]
Only `ac-mo.com` added.
`ventax.net` was added a long time ago. Just update the filter.
