### ISSUE TITLE
coveryourtracks.eff.org

### ISSUE THREAD

**Issue by DrGekt0r** [bogachenko/fuckfuckadblock#300]
### Basic information

**Check the link:** `https://coveryourtracks.eff.org`
**Category:** Anti-adblock
**Reported from:** France

### User environment

**Browser:** Librewolf 98.0.2-1
**Adblocker:** uBlock Origin 1.42.4
**Extensions:** Audio Equalizer, Authenticator, BetterTTV, Bitwarden, CanvasBlocker, Dark Reader, FastForward, Gesturefy, LibreWolf Updater, PotPlayer YouTube Shortcut, Return Youtube Dislike, Simple Translate, Song ID, SponsorBlock, Stylus, Video Speed Controller, Web Translate, Windscribe
**DNS:** None

### Additional message

Site detects Ad blocking and Tracking protection

**Comment by bogachenko** [comment]
Исправлен только обход адблока, трекеры не в моей части, но если надо в мои фильтры добавь
`@@|http*:*/kcarting-tally?&trackingserver=$subdocument`

**Comment by DrGekt0r** [comment]
Все еще обнаруживает "Blocking tracking ads" ("Blocking invisible trackers" тоже, но если не по твоей части - окей)
Увидел, что ты @bogachenko  и в свой фильтр добавил `@@|http*:*/kcarting-tally?&trackingserver=$subdocument`, но с ним, опять же, все еще обнаруживает, добавил в My filters - ничего не изменилось

**Comment by bogachenko** [comment]
>Горящие красным ||do-not-tracker.org^, ||eviltracker.net^ и ||trackersimulator.org^

этого нет в настройках по умолчанию, это у adguard взято.

**Comment by DrGekt0r** [comment]
> > Горящие красным ||do-not-tracker.org^, ||eviltracker.net^ и ||trackersimulator.org^
> 
> этого нет в настройках по умолчанию, это у adguard взято.

Да, Adguard Tracking Protection, но он же не Custom filter

**Comment by bogachenko** [comment]
Он не включен по умолчанию и его нет в региональных настройках = пользовательский.

**Comment by DrGekt0r** [comment]
> Он не включен по умолчанию и его нет в региональных настройках = пользовательский. Смысл настроек по умолчанию - они одинаковы для всех.

Понял, тогда буду уточнять, какие фильтры блокируют

**Comment by DrGekt0r** [comment]
@bogachenko Отключил Enhanced protection для firstpartysimulator.org и firstpartysimulator.net, ну и конечно для самого coveryourtracks.eff.org - все как надо (включая "Blocking invisible trackers") даже с включенным Adguard Tracking protection и Easy Privacy. Спасибо @bogachenko
