### ISSUE TITLE
mitele.es

### ISSUE THREAD

**Issue by diestro123** [bogachenko/fuckfuckadblock#301]
### Basic information

**Check the link:** `https://www.mitele.es/`
**Category:** Anti-adblock
**Reported from:** Spain

### User environment

**Browser:** Brave Browser 100.0
**Adblocker:** Brave Browser 
**Extensions:** Windscribe,Shazam,Bypass Paywall

**Comment by bogachenko** [comment]
>Adblocker: Brave Browser
>`**Adblocker:** <!-- The name of the ad blocker, only uBlock Origin or AdGuard and its version. -->`

Do not pay attention to this, I wrote it this way, for beauty.
