### ISSUE TITLE
reaperscans.id

### ISSUE THREAD

**Issue by rheznendra** [bogachenko/fuckfuckadblock#308]
### Basic information

**Check the link:** `https://reaperscans.id`
**Category:** Anti-adblock
**Reported from:** Indonesia

### User environment

**Browser:** Vivaldi (5.2.2623.41)
**Adblocker:** Adguard

**Comment by rheznendra** [comment]
Well since there is no response yet and i got annoyed by that pop up every time openning new page so i use this rule temporary until my man fix this. Also i am very noob to this adblock rule, so my bad if this not working for some of you guys :)

`reaperscans.id##div[class*="-blackout"].active`
`||reaperid.b-cdn.net/wp-content/plugins/deblocker/js/ads.min.js$important,script`
`reaperscans.id#$#.wrap{ filter:unset!important; -webkit-filter: unset!important; }`
`reaperscans.id##div[class$="-wrapper"]`

**Comment by bogachenko** [comment]
@rheznendra Sorry for the wait, I've been very busy for the last month.
@ameshkov Андрей, дорогой, что ты сделал с Adguardом, почему мое правило `||googleads.g.doubleclick.net/pagead/id^$xmlhttprequest,redirect-rule=nooptext` не работает, т.к судя по логгеру расширение выбирает стороннее правило (с вашего листа) `/googleads.$~script,domain=~github.com|~github.io`, а перенаправление не делает. Я пропустил какое то обновление?
PS: работает только если повысить важность, флагом `important`.
PSS: так же проверь телегу, я тебе баг нашел, на другом сайте. Сможешь воспроизвести?

**Comment by bogachenko** [comment]
@rheznendra Andrey disappeared, the answer was delayed. He does not answer anywhere (he used to answer in Telegram, now he has disappeared there), he may be busy, I will close the problem, because the problem is not in my sheet, as a temporary solution, you can disable their filter using this rule and everything will work for you.

`/googleads.$~script,domain=~github.com|~github.io,badfilter`

**Comment by bogachenko** [comment]
@rheznendra It seems the site has been updated and now there is no anti-adblock at all, if you constantly visit it, let me know and I'll see what can be done.

**Comment by rheznendra** [comment]
yup, it's not using anti adblock for now...
probably because some people reporting that they still got the pop up to turning off the adblock even when they already did it 😂

**Comment by rheznendra** [comment]
ah, i see

**Comment by rheznendra** [comment]
new domain, https://shinigami.id

**Comment by rheznendra** [comment]
![image](https://user-images.githubusercontent.com/13180942/232266274-f90c2391-965f-4644-bf8a-a5313d1457b6.png)

it looks like this on me
above Sedang Hangat, Komik Terbaru, & Mirror

i tried to add custom rule like shinigami.id###aswift_1_host 
or shinigami.id##.adsbygoogle
but it doesn't work,

is it because this async script?
![image](https://user-images.githubusercontent.com/13180942/232266397-d89316f2-ce1d-4349-9ebc-1c264060e04e.png)

**Comment by rheznendra** [comment]
> ![image](https://user-images.githubusercontent.com/13180942/232266274-f90c2391-965f-4644-bf8a-a5313d1457b6.png)
> 
> it looks like this on me above Sedang Hangat, Komik Terbaru, & Mirror
> 
> i tried to add custom rule like shinigami.id###aswift_1_host or shinigami.id##.adsbygoogle but it doesn't work,
> 
> is it because this async script inside div tag? ![image](https://user-images.githubusercontent.com/13180942/232266397-d89316f2-ce1d-4349-9ebc-1c264060e04e.png)

or i guess that;s because another filter i use, i haven't check it yet

**Comment by bogachenko** [comment]
For the thousandth time, **please don't upload images here.**

Your problem does not belong to my list, it is better to ask such questions by mail - bogachenkove@gmail.com , reddit - /u/bogachenkove or telegram @bogachenkove.

you will find the solution here https://github.com/bogachenko/filterlist/blob/main/bogachenkoPF.txt#L186-L190
