### ISSUE TITLE
voxc.org

### ISSUE THREAD

**Issue by PutterPlace** [bogachenko/fuckfuckadblock#31]
`http://voxc.org/4C1ZZ`

Seems to be using FuckAdBlock, but not being taken care of by fuckfuckadblock despite being referenced in the filter (their site could've been updated since it was last added). Double-checked to be sure my filter is up-to-date.

<details><summary>Screenshot (voxc.org)</summary>
<p>

![voxc.org](https://user-images.githubusercontent.com/20749449/69187297-f5708c00-0adf-11ea-8ae4-f4734b57647c.png)

</p>
</details>

**Comment by bogachenko** [comment]
The site has not been updated. He is the same. I can not reproduce your problem. I do not see extension icons for ad blocking in your private mode. Have you allowed your add-ons to work in private mode? Check this, go to the `chrome:// extensions` tab select your extension (uBO or Adguard) by clicking on the "Details" button, scroll down, find the option "Allow to use in incognito mode".

**Comment by PutterPlace** [comment]
AdGuard is enabled in incognito for me. The icon doesn't show because I resized my address bar to not show extension icons in incognito mode, but it is most definitely enabled, and the filter is up-to-date.

**Comment by bogachenko** [comment]
Add this to your "Custom filter"
```
voxc.org#@%#//scriptlet("abort-on-property-read", "PopUP")
voxc.org#@%#AG_abortOnPropertyRead('PopUP');
```

**Comment by Alex-302** [comment]
On my end I see dozens of blocked elements at icon.
Changed your rules.
