### ISSUE TITLE
bdnewszh.com

### ISSUE THREAD

**Issue by multichoyce** [bogachenko/fuckfuckadblock#310]
### Basic information

**Check the link:** `http://streamspass.live/`
**Category:** Anti-adblock
**Reported from:** VPN

### User environment

**Browser:** FireFox 100.0.2
**Adblocker:** Ublock 
**Extensions:** Xbrowsersync, Bitwarden 
**DNS:** CloudFlare

### Additional message

The rules for bdnewszh.com are already in the default ublock lists

**Comment by bogachenko** [comment]
>The rules for bdnewszh.com are already in the default ublock lists

Happy for them.

>Reported from: VPN

I don't give a shit about your real IP, this item is only needed to determine if the site has a geolock or not.
