### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by bnff** [bogachenko/fuckfuckadblock#311]
### Basic information

**Check the link:** `https://fr.investing.com/equities/institut-biophytis-sas`
**Category:** Popup
**Reported from:** FR 

### User environment

**Browser:**  Chrome Version 101.0.4951.67 (Build officiel) (64 bits)
**Adblocker:**  only uBlock Origin
**Extensions:**  I dont care about cookies
**DNS:**  CloudFlare

### Additional message
Not on home of website only on action ...

**Comment by bogachenko** [comment]
There is no ad popup on this site, steps to reproduce?

**Comment by bnff** [comment]
Hello,
it's strange i still have the problem

![image](https://user-images.githubusercontent.com/34969833/170668123-2de91f2e-b655-4d1d-8ca4-ee2e780eb9d9.png)

**Comment by bogachenko** [comment]
**Do not upload any images here.**

What filter lists do you use? Go to your uBO settings in the "Support" tab and copy the "Diagnostics" field here on github to get something similar

```
uBlock Origin: 1.42.4
Chromium: 101
filterset (summary): 
  network: 63269
  cosmetic: 35480
  scriptlet: 21488
  html: 0
listset (total-discarded, last updated): 
  removed: 
    RUS-0: null
    plowe-0: null
    ublock-badware: null
    ublock-filters: null
    ublock-privacy: null
    ublock-quick-fixes: null
    ublock-unbreak: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25817-30, never
  default: 
    user-filters: 0-0, never
    easylist: 67454-50, 1d.4h.54m
    easyprivacy: 27093-122, 1d.4h.54m
    ublock-abuse: 75-0, 1d.4h.53m
filterset (user): [empty]
switchRuleset: 
  added: [array of 1 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  tooltipsDisabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 320 ms
  maxAssetCacheWait: 213 ms
```

**Comment by bnff** [comment]
Sorry


uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 115677
  cosmetic: 3
  scriptlet: 42193
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25817-580, 11h
    adguard-annoyance: 53426-46364, 4d.2h.48m
    adguard-social: 17371-16792, 4d.2h.47m
    fanboy-annoyance: 71250-62981, 4d.2h.47m
    fanboy-cookiemonster: 32161-32161, 4d.2h.47m
    fanboy-social: 23406-23406, 4d.2h.47m
    fanboy-thirdparty_social: 68-21, 4d.2h.47m
    ublock-annoyances: 4426-1413, 4d.2h.47m
  default: 
    user-filters: 4-0, never
    FRA-0: 27696-9131, 4d.2h.48m
    easylist: 67379-35274, 4d.2h.47m
    easyprivacy: 27061-536, 4d.2h.47m
    plowe-0: 3671-814, 4d.2h.47m
    ublock-abuse: 75-3, 4d.2h.47m
    ublock-badware: 4128-500, 4d.2h.47m
    ublock-filters: 31428-11354, 4d.2h.47m
    ublock-privacy: 214-13, 4d.2h.47m
    ublock-unbreak: 1789-272, 4d.2h.47m
    urlhaus-1: 8328-0, 11h
filterset (user): [array of 4 redacted]
trustedset: 
  added: [array of 10 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
  ignoreGenericCosmeticFilters: true
  parseAllABPHideFilters: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 207 ms (selfie)
  maxAssetCacheWait: 101 ms

**Comment by bogachenko** [comment]
I still can't reproduce, the problem is on your side. Try with default settings, you have too many filters enabled and important features disabled like "Ignore generic cosmetic filters" and "Parse and enforce cosmetic filters".
