### ISSUE TITLE
us.tamrieltradecentre.com

### ISSUE THREAD

**Issue by capricorn180** [bogachenko/fuckfuckadblock#312]
### Basic information

**Check the link:** `https://us.tamrieltradecentre.com/pc/Trade/SearchResult?ItemID=6132&SortBy=LastSeen&Order=desc`
**Category:** Anti-adblock
**Reported from:** AU

### User environment

**Browser:** Firefox v100.0.2 (64-bit)
**Adblocker:** uBlock Origin
**Extensions:** Privacy Badger, Decentraleyes, HTTPS Everywhere (tested with all disabled)
**DNS:** 1.1.1.1

### Additional message

Popup occurs during item searches and breaks the site

`https://us.tamrieltradecentre.com/pc/Trade/SearchResult?ItemNamePattern=test`
https://i.imgur.com/KQbtXXb.png

JS Blocking function, uses what appears to be a random hash in url as well
GetAdMode()
`https://us.tamrieltradecentre.com/bundles/View`
`https://us.tamrieltradecentre.com/bundles/View?v=URLfmeUmag2PEQlnwsPvniFr-IKKue5vdFJr9nXOjLE1`

**Comment by bogachenko** [comment]
Turn off "Ignore general cosmetic rules" in uBO settings
