### ISSUE TITLE
guruhitech.com

### ISSUE THREAD

**Issue by michael1900** [bogachenko/fuckfuckadblock#318]
### Basic information

**Check the link:** `https://guruhitech.com/`
**Category:** Anti-adblock
**Reported from:** Italia

### User environment

**Browser:** Safari iOS
**Adblocker:** Adguard

**Comment by bogachenko** [comment]
You bought iOS - well done, and now [throw it away](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos).

PS: This xhr `https://quantcast.mgr.consensu.org/tcfv2/google-atp-list.json` slows down the site.
