### ISSUE TITLE
all18xxx.com & wildteenporn.com

### ISSUE THREAD

**Issue by JonasNo** [bogachenko/fuckfuckadblock#32]
## Basic information

**Check the link:** `http://all18xxx.com/video/18422.html` and `http://wildteenporn.com/video/442435`

**Category:** redirect
**Reported from:** Sweden

**Filter lists:** 
```
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

EasyList

EasyPrivacy

Malware Domain List
Malware domains

Peter Lowe’s Ad and tracking server list
SWE: Frellwit's Swedish Filter

<<<Custom>>>
Anti-Facebook List
https://secure.fanboy.co.nz/fanboy-antifacebook.txt
Fanboy's Enhanced Tracking List
https://secure.fanboy.co.nz/enhancedstats.txt
Fanboy's Social Blocking List
https://easylist-downloads.adblockplus.org/fanboy-social.txt
Fanboy's Swedish
https://secure.fanboy.co.nz/fanboy-swedish.txt
Fuck Fuckadblock
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt


```
### User environment
**Browser:** Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Extension:** uBlock Origin

### Additional message
Been stumbling upon these sorts of nasty redirect sites more and more so it is time to figure out how to break the redirection thing.
Im unable to capture how it redirects from the link you clicked to a random NSFW site (those also have the same behavior).
Just click on a random link, if it doesnt redirect you just press F5 and it will eventually do that.
Im hoping uBlock or a userscript can break that redirection thing.

If you are able to capture how, please teach me how you did it, please.

**Comment by bogachenko** [comment]
Today (and maybe tomorrow) I'm busy for now, block cookies for this site. README `https://support.google.com/chrome/answer/95647` "Allow or block cookies for a specific site"

**Comment by bogachenko** [comment]
I can think of nothing more, only the rules are higher.
