### ISSUE TITLE
AdBlock Plus support

### ISSUE THREAD

**Issue by Tech-How** [bogachenko/fuckfuckadblock#320]
### Additional message

When I try to add the filter to Adblock Plus, it tells me that it is "Not a valid filter list." How can I get around this?

**Comment by bogachenko** [comment]
In the project description I wrote:

>In this repository, filters are created for AdGuard and uBlock Origin.

what is unclear about this? Also https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#adblock-and-adblock-plus
***
Duplicate of #153 #286 #226 #194 #180
