### ISSUE TITLE
interpals.net

### ISSUE THREAD

**Issue by etnguyen03** [bogachenko/fuckfuckadblock#321]
### Basic information

**Check the link:** `https://interpals.net`
**Category:** Anti-adblock
**Reported from:** USA

### User environment

**Browser:** Firefox 101.0.1
**Adblocker:** uBlock Origin 1.42.1
**Extensions:**  Bitwarden
**DNS:** No third-party DNS

**Comment by bogachenko** [comment]
If you're talking about a big popup - "Welcome to Interpals/Please allow ads on our site" then it gets by with the `generichide` rule, which is already on my list for this site.

**Comment by etnguyen03** [comment]
I apologize, something was wrong with my ublock. It works. Sorry for the inconvenience.

**Comment by bogachenko** [comment]
It happens. Please check with a different browser before your next submission. BTW - update uBO to [1.43.0](https://github.com/gorhill/uBlock/releases/tag/1.43.0)
