### ISSUE TITLE
sms24.me

### ISSUE THREAD

**Issue by SoftwareRat** [bogachenko/fuckfuckadblock#322]
It has anti-adblock code on `https://assets.sms24.me/js/app.js?2.57`

**Comment by SoftwareRat** [comment]
For help: https://github.com/uBlockOrigin/uAssets/commit/cd75fdd8ebc963e62a88c4ad3c34cdedc953b9d5

**Comment by SoftwareRat** [comment]
If you scroll, anti-adblock detection is still working

**Comment by SoftwareRat** [comment]
I normally use third-party DNS filtering and /etc/hosts, now I am not at home and just use hosts file

**Comment by SoftwareRat** [comment]
```
❯ ping googlesyndication.com
PING googlesyndication.com (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.187 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.051 ms
^C
--- googlesyndication.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1062ms
rtt min/avg/max/mdev = 0.051/0.119/0.187/0.068 ms
❯ ping doubleclick.net
PING doubleclick.net (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.048 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.073 ms
^C
--- doubleclick.net ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1024ms
rtt min/avg/max/mdev = 0.048/0.060/0.073/0.012 ms
```

hmm I try to unblock

**Comment by SoftwareRat** [comment]
![image](https://user-images.githubusercontent.com/40393784/174779245-242563b5-eab6-471e-a5b9-04b4ea2d11d1.png)

Firefox tracking protection block too

**Comment by SoftwareRat** [comment]
I disabled Firefox Tracking Protection, now it takes longer until antiadblock script works, just ublock blocking these sites

**Comment by bogachenko** [comment]
Have you put Firefox trackers on maximum protection? Do not load any images here, please.

**Comment by SoftwareRat** [comment]
Yes, but I disabled for sms24 and now just uBlock Origin blocking these sites

**Comment by bogachenko** [comment]
You, let me guess a bunch of third -party filtering lists for UBO?

**Comment by SoftwareRat** [comment]
> You use, let me guess a bunch of third-party filtering lists for UBO which blocks these domains?

Yes

**Comment by bogachenko** [comment]
GJ.
Check with the default settings for UBO, on another browser and clean the cookies.
Just unlock the domains above and you will not have an anti adblock.
