### ISSUE TITLE
gwaher.com

### ISSUE THREAD

**Issue by raperov** [bogachenko/fuckfuckadblock#323]
### Basic information

**Check the link:** `https://gwaher.com/faucet`
**Category:** Anti-adblock
**Reported from:** Russia

### User environment

**Browser:** Chrome
**Adblocker:** uBlock Origin
**Extensions:** 
**DNS:** 

### Additional message
Сообщение о обнаружении АДблока появляется после авторизации на сайте

**Comment by bogachenko** [comment]
Не загружай сюда никакие изображения, пожалуйста.
