### ISSUE TITLE
feyorra.top

### ISSUE THREAD

**Issue by raperov** [bogachenko/fuckfuckadblock#324]
### Basic information

**Check the link:** `https://feyorra.top/dashboard`
**Category:** Anti-adblock, need account
**Reported from:** Russia

### User environment

**Browser:** Chrome
**Adblocker:** uBlock Origin
**Extensions:** 
**DNS:** 

### Additional message

При авторизации на сайте обнаруживается АДблок

**Comment by bogachenko** [comment]
Могу воспроизвести, только если заблокирую домен рекламы от гугла - `googlesyndication.com`, а он у меня разблокиорван правилом `@@/^https?:\/\/(www\.)?[^\s]+\/ad[svbxo]?[-_]?[a-z]{1,15}\.js/$script,xmlhttprequest`.

Думаю твоя проблема схожа с этой https://github.com/bogachenko/fuckfuckadblock/issues/322#issuecomment-1161554441

**Comment by raperov** [comment]
Блокировка скрипта, самое простое для меня. Фильтр работает, а с хост файлом мне не очень ясно и куда твоё правило применять не понятно.

**Comment by bogachenko** [comment]
Ты не применишь мое правило в hosts.txt или в стороний DNS сервер, оно создано, только для детальной блокировки, для програм Adguard или расширения uBlock Origin.

Как я уже писал в том теме на которую ссылался, совмещать и обмазываться подобными программами в связке не самая лучшая идея, у тебя всегда будут ложные срабатывания (выбери что-то одно, либо приватность, либо доступ к сайтам. Есть сайты, этот не в счёт, где ты никак не заблокируешь скрипт вызывающий срабатывание скрипта антиадблока, и только разблокировка рекламных доменов поможет с входом на сайт, а как мне разблокировать их если большинство ты побанил в hosts.txt).

**Comment by raperov** [comment]
у меня hosts файл пустой и фильтрующие DNS сервера не использую, но uBlock Origin обнаруживается на сайтах даже если я добавляю подобные сайты в белый список.

**Comment by bogachenko** [comment]
Очевидно проблема на твоей стороне, я залесть в твой компьютер не смогу.

Обнаруживается только в хромогом браузере или где то еще?
Ты не заполнил пункт Extensions, вероятно ты используешь расширения которые имеют доступ к сайтам. Например Privacy Badger или тому подобные, в любом случае нужно проверять только с одним uBO.

**Comment by raperov** [comment]
в любом браузере, даже где не установлены расширения, на хроме стоит HTTPS Everywhere

**Comment by bogachenko** [comment]
Первое. Списки фильтров у тебя по умолчанию для русского региона + FFA или ты добавил что то свое - васянское?
Второе. Конкретно для этого сайта зайди в Журнал сетевых запросов (на хромогом вкладка называется - Сеть или как то так и вызывается вызывается комбинацией клавиш <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>), там выбери тип `JS` или `Script`, и в поле поиска вбей `googlesyndication.com`, дальше нажми кнопку обновить вкладку страницы <kbd>F5</kbd> и смотри блокируется ли этот домен у тебя в хромогом.

**Comment by raperov** [comment]
1. Список фильтров по умолчанию
2. В DevTools гугл отсутствует и сайт заработал даже без фильтра, вроде ничего не делал больше. В любом случае спасибо. А у меня еще вопрос: как сайт определяет IP адрес? Если скриптом, то можно это обойти или предоставлять ему другой IP?

**Comment by raperov** [comment]
Спустя час опять опять АДблок обнаружился.  https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_CONNECTION_RESET

**Comment by bogachenko** [comment]
>Спустя час опять опять АДблок обнаружился. https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_CONNECTION_RESET

Иди в журнал сетевых запросов расширения uBO и смотри разблокирован ли у тебя этот запрос. Если нет, проблема в твоем компьютере - программы/hosts.txt/dns/и тому подобное, в любом случае проблема на твоей стороне, что-то то или кто-то блокирует этот запрос.

**Comment by bogachenko** [comment]
Ты в этом смысле... Просят отключить, т.к. выдают статический (публичный), а не твой личный (динамический) IP-адрес. Все эти IP давно побанены и AdGuard VPN в этом боюсь не поможет.

Например, IP TORa всем известны и даже гугл внес их в черный список (бесконечная капча).
