### ISSUE TITLE
https://hilanofaucet.com/

### ISSUE THREAD

**Issue by raperov** [bogachenko/fuckfuckadblock#325]
### Basic information

**Check the link:** https://hilanofaucet.com/
**Category:** Anti-adblock, need account
**Reported from:** Russia

### User environment

**Browser:** Chrome
**Adblocker:** uBlock Origin
**Extensions:** no
**DNS:** no

### Additional message

Нужен аккаунт. При авторизации выходит это сообщение на белом фоне: "disable your adblock on this site"

**Comment by raperov** [comment]
hilanofaucet.com прекратил работу, можно удалить

**Comment by bogachenko** [comment]
Конкретно для этого сайта я использовал не именной фильтр (не ,domain=hilanofaucet.com`), поэтому фильтра, только для сайта `hilanofaucet.com` в моем списке нет, а тот фильтр что я добавил используется для многих сайтов для обхода, особенно которые публикуешь ты.
