### ISSUE TITLE
viefaucet.com

### ISSUE THREAD

**Issue by raperov** [bogachenko/fuckfuckadblock#326]
### Basic information

**Check the link:** `https://viefaucet.com/`
**Category:** Anti-adblock, need account
**Reported from:** Russia

### User environment

**Browser:** Chrome
**Adblocker:** uBlock Origin
**Extensions:** no
**DNS:** no

### Additional message

Нужен аккаунт. При авторизации появляется сообщение в правом верхнем углу страницы: "Warning Please disable your adblock!"

**Comment by bogachenko** [comment]
Воспроизвести не могу, проблема все еще актуальна?
