### ISSUE TITLE
simpletraffic.co

### ISSUE THREAD

**Issue by FoxsCode** [bogachenko/fuckfuckadblock#327]
### Basic information

**Check the link:** `https://simpletraffic.co`
**Category:** Anti-adblock
**Reported from:** 

### User environment

**Browser:** Edge 102.0.1245.44
**Adblocker:** uBlock Origin
**Extensions:** Too many, but they are all disabled except some roblox ones ( RoGold, RoPro BTRoblox )
**DNS:** No

**Comment by bogachenko** [comment]
Do not load any images here, please.

On the main page of this antiadblock was not found, give me steps for playback.

**Comment by bogachenko** [comment]
Do not load the images here, please. On the main page of this Adblock was not found, give me steps to reproduce this problem.

**Comment by bogachenko** [comment]
@Yuki2718 `||simpletraffic.co^$badfilter`

**Comment by Yuki2718** [comment]
Which list has the rule?

**Comment by bogachenko** [comment]
Main, ENG

**Comment by Yuki2718** [comment]
I can't find.

**Comment by Yuki2718** [comment]
But `||simpletraffic.co^$badfilter` is already in Unbreak

**Comment by bogachenko** [comment]
> I can't find. But found the rule in EL.

yep, Adguard English sheet takes advertising domains with Easylist, and uBO has already been corrected. And in Adguard (But a person uses uBO, It is strange where it is already fixed), I can reproduce the problem if on this site if I just turn on the Adguard English.

Can you reproduce AA?

**Comment by Yuki2718** [comment]
I can't with or without Base enabled. Is this require login?

**Comment by bogachenko** [comment]
No, the login is not required, it appears immediately. Try ADG without the rule above with the English filter

**Comment by Yuki2718** [comment]
Okay on AG Extension I see anti-adb, it's no wonder given the rule blocks everything first party, which is now fixed thx to you.
