### ISSUE TITLE
btcbunch.com

### ISSUE THREAD

**Issue by raperov** [bogachenko/fuckfuckadblock#329]
### Basic information

**Check the link:** `https://btcbunch.com/`
**Category:** Anti-adblock, need account
**Reported from:** Russia

### User environment

**Browser:** Chrome
**Adblocker:** uBlock Origin
**Extensions:** No
**DNS:** No

### Additional message

AdBlock Detected! При авторизации появляется розовый экран

**Comment by raperov** [comment]
Что-то поломалось. С данным фильтром всплывает розовое окно: AdBlock Detected!

**Comment by bogachenko** [comment]
Не могу воспроизвести, однако на сокращенных ссылках от этой платформы есть много что интересного.
