### ISSUE TITLE
gustmag.com

### ISSUE THREAD

**Issue by PutterPlace** [bogachenko/fuckfuckadblock#33]
### Basic information

**Check the link:** `https://gustmag.com/KhmHzlUV`
**Category:** anti-adblock
**Reported from:** United States
**Filter lists:**

    AdGuard Base Filter
    EasyList
    Fuck Fuckadblock
      https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt

### User environment
**Browser:** Chrome v78.0.3904.108 x64
**Extension:** AdGuard AdBlocker

### Additional message
<details><summary>Screenshot (gustmag.com)</summary>
<p>

![gustmag.com](https://user-images.githubusercontent.com/20749449/70498872-63a3df80-1add-11ea-81b5-04ad90a16bc7.png)

</p>
</details>

**Comment by bogachenko** [comment]
already added https://github.com/bogachenko/fuckfuckadblock/commit/18a22620d55f769bebd3d0735541235e730000da https://github.com/bogachenko/fuckfuckadblock/commit/96d057706ec15ce85e3215413e22522a733df604
