### ISSUE TITLE
madshiba.fun

### ISSUE THREAD

**Issue by raperov** [bogachenko/fuckfuckadblock#330]
### Basic information

**Check the link:** `https://c.madshiba.fun`
**Category:** Anti-adblock, need account
**Reported from:** Russia

### User environment

**Browser:** Chrome
**Adblocker:** uBlock Origin
**Extensions:** No
**DNS:** No

### Additional message

После авторизации обнаруживается АДблок

**Comment by bogachenko** [comment]
На страницу `c.madshiba.fun` зайти не могу, нулевой ping https://check-host.net/check-report/ac8b80ek33f

**Comment by raperov** [comment]
мой косяк, стёр один символ в адресе: https://fc.madshiba.fun/
