### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by Giingu** [bogachenko/fuckfuckadblock#331]
### Basic information

**Check the link:** `https://imgur.com/`
**Category:** Anti-adblock
**Reported from:** Spain

### User environment

**Browser:** Edge ( Not sure about the version )
**Adblocker:** uBlock Origin
**Extensions:** Too many to list, most of them disabled, no other adblocking or similar extension is enabled.
**DNS:** No

### Additional message

You need to try to upload something for it to pop up.
When trying it with Adblock (Not adblock plus) the anti adblock does not show up.
No, i did not and do not have both enabled simultaneously, i just installed it to check if by using other blocker it would still show up.

**Comment by krystian3w** [comment]
<q>`edge://settings/help`</q> to check and update Edge (stable now is 103.0.1264.44).

**Comment by bogachenko** [comment]
I tried on the browser Edge V103.0.1264.44, with the latest version of the uBO extension, with the included regional subscriptions for Spain - nothing. You probably have a lot of filters, restore to the default settings, but I can’t reproduce on the clean browser of Edge and uBO.
>Extensions: Too many to list, most of them disabled, no other adblocking or similar extension is enabled.

https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions

**Comment by krystian3w** [comment]
So you don't disable follow oldie topics?

**Comment by bogachenko** [comment]
Why open thousands of tickets for one specific site. I do not freeze these tickets, it’s easier to track the problem and do not waste time searching for information, because it will be on one page.

**Comment by Giingu** [comment]
Did not try the script, will do tomorrow, but after updating edge it still exists yeah

**Comment by bogachenko** [comment]
Did you do the operations that I advised you above? Does the issue only exist on the Edge browser?

**Comment by xonkiz** [comment]
> https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions

no, the problem is AMO continues to ignore requests to allow user prioritization of extension functions
