### ISSUE TITLE
dogemate.com

### ISSUE THREAD

**Issue by raperov** [bogachenko/fuckfuckadblock#333]
### Basic information

**Check the link:** `https://dogemate.com/games/roll`
**Category:** Anti-adblock, need account
**Reported from:** Russia

### User environment

**Browser:** Chrome
**Adblocker:** uBO
**Extensions:** no
**DNS:** no

### Additional message
После нажатия кнопки "ROLL NOW" появляется сообщение:
"1please disable your adblock, translator or javascript blocker and try again after refreshing the page."

**Comment by bogachenko** [comment]
У тебя, после обновления списка, ролл работает? Уведомления об использовании нет, а ролл, что с ним?

**Comment by bogachenko** [comment]
@raperov `dogemate.com##+js(aopr, Date.prototype.toUTCString)` работает для тебя?

**Comment by bogachenko** [comment]
@raperov `@@||dogemate.com/banner/*$image,1p` это работает для тебя?

**Comment by Yuki2718** [comment]
Fixed in uBlock filters.
