### ISSUE TITLE
fc.lc

### ISSUE THREAD

**Issue by iltblock35** [bogachenko/fuckfuckadblock#335]
### Basic information

**Check the link:** `https://fc-lc.com/JSrT3bpZ`
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:** MS edge Version 103.0.1264.44 (Official build) (64-bit)
**Adblocker:** uBlock Origin Last version
**Extensions:** Violentmonkey with AdsBypasser Lite
**DNS:** Google

### Additional message

This site has a script blocking access to the link (translated by Google)
This example is a error page, because the link doesn't exist

**Comment by bogachenko** [comment]
Give me full link ?

**Comment by iltblock35** [comment]
[Link](https://fc-lc.com/JSrT3bpZ)

**Comment by bogachenko** [comment]
`fc.lc,fc-lc.com##+js(abort-current-inline-script.js, eval, ignielAdBlock)` does it work for you?
