### ISSUE TITLE
This is unethical

### ISSUE THREAD

**Issue by vincedundee** [bogachenko/fuckfuckadblock#337]
I run a small [games news and reviews publishing website](https://rapidfirerocks.com). It makes very, very little from ads but we still put the effort in as we have an interest in the topic - if it were to grow, we'd have to consider paywalls or just shut it down - growth brings further costs. Given you're on github, you'll be fully aware that a lot of websites have developers and projects behind them. This isn't my first outing with a website. I've done this for 20 years. I've watched ad revenue plummet as the popularity of ad blockers increases. Each website project requires countless hours building up bespoke systems in the background, building a reputation, a community. I've thrown god knows how much money to third party systems, hosting. It's all money and time. Projects like this, ad blocker - they're no better than piracy. You are effectively providing people with the means to obtain a service without paying for it - while you might allude to some noble cause of giving the people an ad-free internet, you're actually just killing small publishers, killing smaller hobby sites and projects that can't sustain the cost of running a website - big publishers will hide behind paywalls, of which they have the marketing budget to sustain. 

I don't have some corporate backing or a desire to make tons and tons of money. I just want to be able to continue publishing things that are interesting, on a website I control without paying for it out my own pocket and the little tiny amount that ads bring in to help run sites like mine is being destroyed by projects like this.

**Comment by bogachenko** [comment]
Hello, what you wrote does not apply to my project, I do not block ads, I provide access to sites that restrict the end user in access, showing him annoying notifications about the use of the adblock, and also block pop-ups. Your site is not on my list.

**Comment by bogachenko** [comment]
As for advertising (which is not blocked by my list, at least for your site), it is terrible in any form for me, and with [my personal list](https://raw.githubusercontent.com/bogachenko/filterlist/main/bogachenkoPF.txt), where I pointwise delete it for sites/programs that I use. I hate advertising in any form. As for your site - you use targeted advertising from Google, many, including me, will say that this is bad. Why should I share my preferences with your site, or should I say share with Google? Maybe (they pay less for this) if you used a banner image that fit into the theme of the site (veiled), redirected to the content previously agreed with the advertiser of the site, then people would not mind.

Further, regarding the domain payment, the com domain is very expensive in comparison with other domains, as it is international and very popular. Check it https://www.godaddy.com/domainsearch/find?checkAvail=1&domainToCheck=rapidfirerocks

Or use the trick that you yourself described with a paid wall. Offer something to the end user when he buys a subscription from you (in addition to cut-out advertising), as Spotify did for example (I'm talking about rewinding songs, downloading and listening to songs in high quality, and so on).
