### ISSUE TITLE
bluemediafiles.com

### ISSUE THREAD

**Issue by Hellements** [bogachenko/fuckfuckadblock#338]
### Basic information

**Check the link:** `https://bluemediafiles.com`
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:** Firefox 103.0 (64-bit)
**Adblocker:** uBlock Origin 1.43.0
**Extensions:** 
**DNS:** NextDNS (filters: NextDNS Ads & Trackers Blocklist, oisd, 1Hosts (Pro), notracking, NoTrack Tracker Blocklist, AdGuard DNS filter)

### Additional message

I go to `https://igg-games.com`. Click to download anything. New tab opens with the address `https://bluemediafiles.com`. With uBlock enabled/disabled, I get a popup asking me to disable adblock, and it doesn't give me the download link. My uBlock has the default filters enabled and this fuckfuckadblock.
I'm probably getting this popup because NextDNS is blocking the ads, but fuckfuckadblock installed on my uBlock is not bypassing it.
Thanks in advance.

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin
I can't reproduce the problem, read and disable
