### ISSUE TITLE
washingtonpost.com

### ISSUE THREAD

**Issue by DFNCTSC** [bogachenko/fuckfuckadblock#34]
New overlay at WashingtonPost:

![](https://i.boring.host/1H5RbTIK.png)

https://www.washingtonpost.com/religion/2019/12/19/christianity-today-an-influential-evangelical-magazine-says-president-trump-should-be-removed-office/#click=https://t.co/NOx2da2amC

**Comment by bogachenko** [comment]
Read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-sites
