### ISSUE TITLE
try2link.com

### ISSUE THREAD

**Issue by DoingDog** [bogachenko/fuckfuckadblock#340]
### Basic information

**Check the link:** `https://try2link.com/level-4`
**Category:** Anti-adblock
**Reported from:** HK

### User environment

**Browser:** Chrome 105.0.5191.0 Win x64
**Adblocker:** uBlock Origin 1.43.0
**Extensions:** 
**DNS:** dns.google

### Additional message

Adblock not detected if I allow `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`

**Comment by bogachenko** [comment]
It is already allowed, by this rule `@@/^https?:\/\/(www\.)?[^\s]+\/ad[svbxo]?[-_]?[a-z]{1,15}\.js/$xmlhttprequest`

**Comment by DoingDog** [comment]
found it's blocked by a third party rule. im sorry
