### ISSUE TITLE
mifirm.net

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#341]
### Basic information

**Check the link:**  `https://mifirm.net/model/sweet.ttt#id`
**Category:** Anti-adblock
**Reported from:**  Indonesia

### User environment

**Browser:**  Chrome Latest
**Adblocker:**  Ublock Origin

**Comment by bogachenko** [comment]
[Read](https://github.com/bogachenko/fuckfuckadblock/issues/340#issuecomment-1202057876) and remove third party rules from your uBO.
