### ISSUE TITLE
soft98.ir

### ISSUE THREAD

**Issue by n00b-spectre** [bogachenko/fuckfuckadblock#344]
### Basic information

**Check the link:** `https://soft98.ir`
**Category:** Anti-adblock
**Reported from:** India

### User environment

**Browser:** Chrome 105.0.5195.102
**Adblocker:** uBlock Origin 1.44.2
**Extensions:** Dark reader, Shazam

**Comment by bogachenko** [comment]
I can not reproduce, all programs are downloaded properly.

**Comment by n00b-spectre** [comment]
![Disable AdRemoval](https://images2.imgbox.com/b5/e8/EpZxPB3M_o.png "Disable AdRemoval")

This pops up whenever I visit this page with uBlock Origin enabled (Vanilla Settings with Fuck Fuckadblock added as custom filter list). The text written there translates to "Disable the ad removal plugin". After this, the main contents of the page get deleted from the Page!
However, I noticed that this sometimes gets bypassed whenever a VPN is turned on. Also, the Brave browser isn't affected by this. I can easily access the site with default Brave settings.

**Comment by n00b-spectre** [comment]
I did a screen capture of the problem. [Check this out](https://anonymfile.com/AroP/new-incognito-tab-google-chrome-2022-09-09-20-25-08.mp4)
Hope this helps you to get a better understanding of the situation.

**Comment by bogachenko** [comment]
Please check with disabled filter - uBlock filters – Quick fixes.

**Comment by n00b-spectre** [comment]
Disabling  `uBlock filters – Quick fixes` fixes the problem.
Thanks for the support.
