### ISSUE TITLE
9anime.id

### ISSUE THREAD

**Issue by melnation-com** [bogachenko/fuckfuckadblock#345]
### Basic information

**Check the link:** `https://9anime.id/watch/overlord-iii.mw7x`
**Category:** Breakage
**Reported from:** Philippines

### User environment
**Browser:** Google Chrome
**Adblocker:** uBlock Origin
**Extensions:** OneTab `https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall`
**DNS:** CloudFlare

### Additional message

Not just me, I just recently discovered it at this hour, and this reddit often does not allow duplicate threads, so who knows who also got this issue.
https://www.reddit.com/r/9anime/comments/xc7285/entire_series_missing/

**Comment by bogachenko** [comment]
How does this relate to my filter list?
