### ISSUE TITLE
multiplayer.it

### ISSUE THREAD

**Issue by ReshiramZekrom1** [bogachenko/fuckfuckadblock#349]
### Basic information

**Check the link:** `https://multiplayer.it/`
**Category:** Anti-adblock
**Reported from:** Italy

### User environment

**Browser:** Chrome 105.0.5195.102
**Adblocker:** uBlock Origin 1.44.2
**Extensions:** HTTPS Everywhere, FastForward, SponsorBlock, Return YT Dislike, Tampermonkey, Keepa
**DNS:** Cloudfare DNS

**Comment by bogachenko** [comment]
>Tampermonkey

You can have false positives on any sites >> [README](https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions)
