### ISSUE TITLE
promo-visits.site

### ISSUE THREAD

**Issue by craticar** [bogachenko/fuckfuckadblock#350]
### Basic information

**Check the link:**  `https://promo-visits.site/bHZM6pL`
**Category:** Breakage
**Reported from:**  Trinidad and Tobago

### User environment

**Browser:**  Opera Version:90.0.4480.84; Chrome Version 105.0.5195.126 (Official Build) (64-bit)
**Adblocker:**  uBlock Origin 1.44.2
**Extensions:**  Always active Window - Always Visible, Cookie AutoDelete, Disable Page Visibility API, Ignore X-Frame headers, Noptcha: ReCAPTCHA & hCAPTCHA Solver, Pop up blocker for Chrome™ - Poper Blocker, Speed-Up Browsing, Force Background Tab, SponsorBlock for YouTube - Skip Sponsorships
**DNS:**  None

### Additional message
the page glitches when this filter is on

**Comment by bogachenko** [comment]
Please NEVER upload anything here (at least until I ask for it). You have the words, use it.
