### ISSUE TITLE
mahobeachcam.com

### ISSUE THREAD

**Issue by brru8999** [bogachenko/fuckfuckadblock#352]
### Basic information

**Check the link:** `https://mahobeachcam.com/`
**Category:** Breakage

### User environment

**Browser:** Chrome Version 105.0.5195.126
**Extension or program:** Ublock Origin
**DNS:** N/A
**Extensions:** Ublock Origin/Distill/Amazon Wish List

### Additional message
After a few seconds of viewing, the splash screen comes up saying some elements could not be loaded.

**Comment by brru8999** [comment]
**Browser:** Chrome Version 105.0.5195.126
**Extension or program:** Ublock Origin
**DNS:** N/A
**Extensions:** Ublock Origin/Distill/Amazon Wish List

**Comment by bogachenko** [comment]
Please don't upload anything here. You have a language, use words.

And don't break the markup.
