### ISSUE TITLE
soft98.ir

### ISSUE THREAD

**Issue by FlashWins** [bogachenko/fuckfuckadblock#353]
### Basic information

**Check the link:** `https://soft98.ir/internet/web-browser/3545-microsoft-edge-2.html`
**Category:** Anti-adblock
**Reported from:** Iran

### User environment

**Browser:** Microsoft Edge Version 105.0.1343.42 (Official build) (64-bit)
**Adblocker:** uBlock Origin 1.44.4
**Extensions:** Privacy  Badger
**DNS:** ControlD OISD Free DNS : 76.76.10.32 , 76.76.2.32

### Additional message

Admin of This site is a pain in the ass, literally! He purposely blocked adblockers on his site and constantly does that daily. If we block all of the scripts, download links will not show; if we don't block them and only block ads, a popup message will appear and whole post content will disappear after a few seconds.

**Comment by bogachenko** [comment]
>Extensions: Privacy Badger

https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions

>DNS: ControlD OISD Free DNS : 76.76.10.32 , 76.76.2.32

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin

**Comment by FlashWins** [comment]
"PS: In uBO, remove all third-party filters, leave the FFA list and the default settings, but delete this https://github.com/bogachenko/fuckfuckadblock/issues/344#issuecomment-1242679163, and there will be no problems with access on this and other sites."

That's not going to happen! I want to remove banners entirely, and there should be a way to disable the script that checks my browser constantly! Adblock lists only work fine when ads are eradicated; your list does NOT prevent that. 
And please do NOT mention the duplicated issues threads. This one is different because from the time of issue #344 until today, the admin of soft98 changed scripts of his site and hosted banners on the main domain, and even removed UTM links from them!!!

So: I won't allow this issue to get closed until the problem fixes entirely, and even with the quick fixes list being active with that valuable DNS and even privacy badger and etc..

**Comment by bogachenko** [comment]
@FlashWins 

>That's not going to happen! I want to remove banners entirely, and there should be a way to disable the script that checks my browser constantly! Adblock lists only work fine when ads are eradicated; your list does NOT prevent that.

My list should not prohibit advertising. I don't do ad blocking or removing tracking links. I only provide access to the site, access to this site is already granted, I can download anything on it - all programs without problems. If you want to block banner ads on this site, then go ahead and defeat them with the eyedropper.

>So: I won't allow this issue to get closed until the problem fixes entirely, and even with the quick fixes list being active with that valuable DNS and even privacy badger and etc..

I have already answered how to fix the problem, if you refuse to do this, then why are you asking me for advice, I suggest that you reconsider your views on this list and find [the best option](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#to-avoid-problems-with-the-fuck-fuckadblock).

@MasterKia How does this relate to the topic? Where I quote "He purposely blocked adblockers on his site and constantly does that daily." All I saw there is that you are trying to block ads, but I repeat that I do not deal with such problems.

**Comment by bogachenko** [comment]
I don't understand why should I try something? Here, in boring bold text, in black and white, it is written that **I don't block ads** but on the contrary, sometimes I unlock it to avoid triggering. https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues

I do ONLY remove anti-adblock and pop-ups, does any of what you describe fit this description?

**Comment by bogachenko** [comment]
It's funny, but you add it to the quick fixes, and I advise you to turn them off.

**Comment by bogachenko** [comment]
You drive me into a corner, then I will (like a snake) and ask the Japanese `Yuki2718` to remove it.

I just don't understand, these are regular banners with ads, not aggressive gifs. What is the problem?
