### ISSUE TITLE
hbogoasia.id

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#359]
### Basic information

**Check the link:**  https://www.hbogoasia.id/
**Category:** Breakage
**Reported from:**  Indonesia

### User environment

**Browser:**  Chrome Latest
**Adblocker:**  Ublock Origin
**Extensions:** 
**DNS:** 

### Additional message

 blank website when enable ublock origin

**Comment by bogachenko** [comment]
This yours `id##+js(nobab)` @okiehsch

**Comment by okiehsch** [comment]
I can't find that filter.

**Comment by bogachenko** [comment]
Damn, I should have called the gypsy. The problem is here

>komediservisi.com,id,komikit.com

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ec237e0aaae909b81a40fc2a41b46afd1045ca82
