### ISSUE TITLE
AdGuard for Windows now supports Scriptlets

### ISSUE THREAD

**Issue by SonOfDiablo** [bogachenko/fuckfuckadblock#36]
According to the Readme and issue #2 you state that AdGuard for Windows doesn't support scriptlets, which was correct at the time, but as of [December 25, 2019](https://adguard.com/en/versions/windows/release.html#version-733048) AdGuard for Windows now supports scriptlets.
   
I assume this means that we can now use fuckfuckadblock with AdGuard for Windows?

**Comment by bogachenko** [comment]
Yes, you can, but version 7.3 (which you refer to) **DOES NOT** yet provide for the display of scriptlets in the log.
