### ISSUE TITLE
tubeload.co[NSFW]

### ISSUE THREAD

**Issue by gototheskinny** [bogachenko/fuckfuckadblock#362]
### Basic information

**Check the link:**  `https://tubeload.co/f/lpe9vcbdwl9i/FS_-_Give_And_Take_-_Michael_Boston__Ethan_Sinns.mp4`
**Category:** Anti-adblock
**Reported from:**  Turkiye

### User environment

**Browser:**  Safari iOS 15.0
**Adblocker:**  Adguard for iOS 4.4.4
**Extensions:** 
**DNS:**  Nope

### Additional message

 this was in another site https://github.com/AdguardTeam/AdguardFilters/issues/134372 embedded and in that site https://github.com/AdguardTeam/AdguardFilters/issues/134236 same issue was there too.

**Comment by gototheskinny** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/134236

**Comment by gototheskinny** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/134372

**Comment by bogachenko** [comment]
~Welcome to the harsh reality.~ Read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos. I do not know how to make something work on this piece of shit. If you had a normal operating system, you wouldn't have any problems with advertising pop-ups.

**Comment by gototheskinny** [comment]
> ~Welcome to the harsh reality.~ Read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos. I do not know how to make something work on this piece of shit. If you had a normal operating system, you wouldn't have any problems with advertising pop-ups (_I checked on Windows and Android_).
> 
> 
> 
> PS: For the future, in the column `>Additional message` you can attach links to other Internet resources (now I did it for you), please do not write it in separate comments, it can be regarded as spam.

I didn't know platforms made such a difference. I know ios is so restrictive but so many people use ios/apple devices but I get you. I guess this filter is not for Safari ios/macos. Btw i wasn't talking about adguard mentions in there but I'll do that from now on thanks for the suggestion.

**Comment by rihaq** [comment]
Warning!!! ⚠️ ⚠️ ⚠️ ⚠️  Don't open this link, it contains gay porn

**Comment by gototheskinny** [comment]
> Warning!!! ⚠️ ⚠️ ⚠️ ⚠️  Don't open this link, it contains gay porn

Ur right I should've warned but it's been like 20 days since this issue is closed??

**Comment by bogachenko** [comment]
people are already notified by the NSFW label
