### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by intenzemotion** [bogachenko/fuckfuckadblock#366]
### Basic information

**Check the link:** `https://blockadblock.com/`
**Category:** Breakage
**Reported from:** Malaysia

### User environment

**Browser:** Google Chrome 107.0.5304.107
**Adblocker:** uBlock Origin 1.45.2
**Extensions:** FastForward & Tampermonkey (but they are all disabled prior testing for clear result)
**DNS:** Quad9

### Additional message

Site won't load while FFA is enabled, disabling FFA will enable the site to load again.

**Comment by bogachenko** [comment]
I can't reproduce. The site opens as usual, the issue is on your side.

**Comment by intenzemotion** [comment]
Thank you for your response. Disabling **AdGuard Base** from uBlock Origin seems to alleviate the issue for the moment, probably little conflict between the filters themselves.

p/s: It was funny in this case because the site is about blocking adblockers, won't actually going to use this site anyway.
