### ISSUE TITLE
typezebra.com

### ISSUE THREAD

**Issue by nermur** [bogachenko/fuckfuckadblock#368]
### Basic information

**Check the link:** `https://typezebra.com`
**Category:** Anti-adblock
**Reported from:** United States

### User environment

**Browser:** Firefox Developer Edition 108.0b5
**Adblocker:** uBlock Origin 1.45.2
**Extensions:** uBlock Origin
**DNS:** Quintex Alliance Consulting

### Additional message
Minor annoyance to at the bottom-left and seemingly nothing more.

**Comment by bogachenko** [comment]
You do not need to specify your city or state for the future. Only the country, it is necessary for problematic sites with a geo-block. If some site works only for Americans, then I will choose the American IP address of any state, the main thing is that the ping is good while in my country.

PS: By the way, this is a good site.
