### ISSUE TITLE
Does FFA update automatically?

### ISSUE THREAD

**Issue by RaptaG** [bogachenko/fuckfuckadblock#369]
Installed using the uBO method

**Comment by bogachenko** [comment]
Yup, I have the setting on my list that automatically updates it for you every 3 days  ([no more allowed](https://github.com/gorhill/uBlock/issues/3406#issuecomment-355748757), as far as I know), although I would recommend updating it manually at the beginning of each of your days when you work with a computer. Here it is:

```
! Expires: 3 days
```

**Comment by RaptaG** [comment]
Cool, good to know.
I know that the unsupported sites are there for issues not to be made, but is there any chance that you'll support `aternos.org` in FuckFuckAdBlock?

**Comment by bogachenko** [comment]
Too complicated for me, updated very often. I need more fan base to support this (if more people are interested in this, who will correct me and the problem lists, I will delete this article with unsupported websites altogether).
