### ISSUE TITLE
memoo.xyz

### ISSUE THREAD

**Issue by PutterPlace** [bogachenko/fuckfuckadblock#37]
### Basic information

**Check the link:** `https://memoo.xyz/DgR9nQK1`
**Category:** anti-adblock
**Reported from:** United States
**Filter lists:**

    AdGuard Base Filter
    EasyList
    Fuck Fuckadblock
      https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt

### User environment
**Browser:** Chrome v79.0.3945.130 x64
**Extension:** AdGuard AdBlocker

### Additional message
<details><summary>Screenshot (memoo.xyz)</summary>
<p>

![memoo.xyz](https://user-images.githubusercontent.com/20749449/73599736-5c60e700-450c-11ea-8605-286805691188.png)

</p>
</details>

**Comment by bogachenko** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/49065
