### ISSUE TITLE
Script manger?

### ISSUE THREAD

**Issue by malicerainbow** [bogachenko/fuckfuckadblock#373]
So this is just a filter there is no script needed with the custom adblock filter? so there's no need for a script manager?

**Comment by bogachenko** [comment]
No, there is no need. Installed the uBO or AdGuard extension, put the FFA sheet there and that's it, you can go into battle.

PS: I saw your question in reek/anti-adblock-killer for mac, [read it](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos) before you install

**Comment by malicerainbow** [comment]
So all I do is add this custom filter to my adblocker and that’s it?

**Comment by bogachenko** [comment]
If we are talking about normal operating systems, such as Windows / Linux / Android - yes.

**Comment by malicerainbow** [comment]
> If we are talking about normal operating systems, such as Windows/(GUI) Linux/Android - yes.
> I also draw your attention to the fact that **only** [uBlock Origin](https://github.com/gorhill/uBlock) and [AdGuard](https://adguard.com/) are supported.

But what about iOS?

**Comment by malicerainbow** [comment]
> Bought - use it, but you can forget about using the sheet with Mac OS together, for the reason described above. You will always have errors, and something will always fall off.

I have literally no idea what you just said

**Comment by malicerainbow** [comment]
> Bought - use it, but you can forget about using the sheet with Mac OS together, for the reason described above. You will always have errors, and something will always fall off.

But basically android works better with your filter of Mobil that’s what your saying correct?

**Comment by bogachenko** [comment]
>If we are talking about normal operating systems, such as Windows/(GUI) Linux/Android - yes.

**Comment by malicerainbow** [comment]
> If we are talking about normal operating systems, such as Windows/(GUI) Linux/Android - yes.

So I should get an android in order to use your filter of mobile?
