### ISSUE TITLE
antiblock.org

### ISSUE THREAD

**Issue by malicerainbow** [bogachenko/fuckfuckadblock#374]
### Basic information

**Check the link:**  `https://antiblock.org/?p=v3&demo`
**Category:** Anti-adblock
**Reported from:** United States

### User environment

**Browser:** Safari iOS 15.7.1
**Adblocker:** Adguard Adblocker 4.4.4
**Extensions:**  None
**DNS:**  None

### Additional message

I tried your custom filter on the test site that Reek of anti Adblock killer posted and it told me to remove my Adblocker

**Comment by malicerainbow** [comment]
Does not work on my gay porn site also 

![D459EED7-456B-4BC9-8BCF-A85907DECC77](https://user-images.githubusercontent.com/118444664/205232621-8b685794-0a9b-4a24-8e5a-e48cdefc1f18.png)

**Comment by malicerainbow** [comment]
I also did premium Adguard because it won’t let you add custom filters on iOS if you don’t so if this can’t be resolved please tell me see so I can cancel the trial before I’m charged!!!!!

**Comment by bogachenko** [comment]
>Browser: Safari iOS 15.7.1

I'm afraid I can't help you. Read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos

**Comment by malicerainbow** [comment]
> > > Browser: Safari iOS 15.7.1
> > 
> > 
> > I'm afraid I can't help you. Read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos
> 
> Good. 👍 he annoys with gay porno sites

So basically your a homophobe?

**Comment by malicerainbow** [comment]
> > > Browser: Safari iOS 15.7.1
> > 
> > 
> > I'm afraid I can't help you. Read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos
> 
> Good. 👍 he annoys with gay porno sites



> > Browser: Safari iOS 15.7.1
> 
> I'm afraid I can't help you. Read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos

So the only way your filter code will work with Mobil is if I get an android correct?

**Comment by bogachenko** [comment]
I answered you several times that - yes.
