### ISSUE TITLE
Issue w/ AdGuard installation instructions

### ISSUE THREAD

**Issue by Phe0nyx** [bogachenko/fuckfuckadblock#376]
Instead of what it says on the wiki, I had to go to the "customs" button then input the raw link. Maybe update it?

**Comment by bogachenko** [comment]
I have no idea what you just said.

**Comment by rihaq** [comment]
https://user-images.githubusercontent.com/1342577/206280426-b08bc553-fd64-4796-835e-d372dfe2448c.png

**Comment by gir489returns** [comment]
There is no wiki, what the fuck are you talking about?
