### ISSUE TITLE
Use another git hosting

### ISSUE THREAD

**Issue by rihaq** [bogachenko/fuckfuckadblock#377]
Why? 
--> https://giveupgithub.org

**Comment by gir489returns** [comment]
> words words words words words words words words words words words words

**Comment by bogachenko** [comment]
I wanted to switch to gitlab.com , after purchase github.com Microsoft (I don't really like this company, I thought/think this company will make a website, but so far this has not happened in my opinion), but gitlab.com not very popular when compared with the site above. Maybe I'll create a mirror there, or maybe not.

The reasons listed on your website are not satisfactory, and it is do not concern me much.
***
I have mirrors, if this particular site does not suit you - [here](https://github.com/bogachenko/fuckfuckadblock/wiki/Mirror-lists).
You can report problems on the site by mail (several Poles have done this in the past) - `bogachenkove@gmail.com` , or telegram - `@bogachenkove`, twitter - `@bogachenkove`, reddit (I rarely go there) - `u/bogachenkove`
