### ISSUE TITLE
AdBlock Plus support

### ISSUE THREAD

**Issue by SupaGamer2017** [bogachenko/fuckfuckadblock#378]
Apologies if I chose an incorrect label, I was trying to choose the closest one for this scenario.

I was attempting to add the filter list to Adblock Plus, but I received this error, stating that this isn't a valid filter list:
Is there any way to fix this error, or is this an issue on ABP's end? Thanks!

**Comment by bogachenko** [comment]
Read the information about this repository again and you will understand why there is an error. https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock
***
PS: https://github.com/bogachenko/fuckfuckadblock/issues?q=AdBlock+Plus+support

**Comment by SupaGamer2017** [comment]
Apologies.
