### ISSUE TITLE
startpage.com

### ISSUE THREAD

**Issue by xChAmeLIoNz** [bogachenko/fuckfuckadblock#379]
### Basic information

**Check the link:** `https://www.startpage.com/`
**Category:** Breakage
**Reported from:** Italy

### User environment

**Browser:** Firefox v107.0.1
**Adblocker:** uBlock Origin v1.45.2
**Extensions:** Dark Reader, UA switcher, Greasemonkey
**DNS:** N/A

### Additional message

After importing the custom filter list, Startpage started showing ads whenever I search something. If I disable the filter list it doesn't show ads.
NOTE: Search using google doesn't show ads.

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#known-issues
