### ISSUE TITLE
luffytra.xyz

### ISSUE THREAD

**Issue by kyoyacchi** [bogachenko/fuckfuckadblock#380]
### Basic information

**Check the link:**  `https://luffytra.xyz/embed2/?id=https://mixdrop.co/f/j90jo9zeh4e93o`
**Category:** Anti-adblock
**Reported from:** Turkey

### User environment

**Browser:**  Kiwi Browser
**Adblocker:**  uBlock Origin
**Extensions:**  Pixiv Toolkit, User Agent Switcher,Stylus, Search by Image, Better History, Eight Dollars, FastForward, Pixiv fanbox downloader,Violentmonkey, Unhook, sponsorblock, bitwarden, hotspot vpn, kellyc image downloader
**DNS:**  Cloudflare

### Additional message

I get this message while trying to watch anime from `www.tranimeizle.co`
and it provides videos from `luffytra.xyz`

**Comment by PegHorse** [comment]
Hello ^^

Add Anti Adblock Reek script in Violentmonkey or equal to it
https://github.com/reek/anti-adblock-killer/

For me it works
Have fun ^^

**Comment by kyoyacchi** [comment]
> Hello ^^
> 
> Add Anti Adblock Reek script in Violentmonkey or equal to it https://github.com/reek/anti-adblock-killer/
> 
> For me it works Have fun ^^
> 
> ![image](https://user-images.githubusercontent.com/7678316/211289437-5a25f4e1-57ff-4b49-bfe9-b87ab999908b.png)

Do you use it in Violentmonkey? I wasn't using it toprevent them conflicting each other. I'll try now

**Comment by kyoyacchi** [comment]
> Hello ^^
> 
> Add Anti Adblock Reek script in Violentmonkey or equal to it https://github.com/reek/anti-adblock-killer/
> 
> For me it works Have fun ^^
> 
> ![image](https://user-images.githubusercontent.com/7678316/211289437-5a25f4e1-57ff-4b49-bfe9-b87ab999908b.png)

Yeah, it really did work with Violentmonkey, was it necessary to use it in Violentmonkey too from the beginning? Anyway thanks for enlightening my ignorant self.

**Comment by bogachenko** [comment]
Sorry for taking so long to reply, but you shouldn't have closed this issue.

**Comment by kyoyacchi** [comment]
> Sorry for taking so long to reply, but you shouldn't have closed this issue.

![Screenshot_20230115-235206.jpg](https://user-images.githubusercontent.com/63583961/212566714-8dcfb5a1-af82-4f07-99a8-a8865a93bff3.jpg)

Stil same even after updating the list.

**Comment by kyoyacchi** [comment]
> Sorry for taking so long to reply, but you shouldn't have closed this issue.

Sorry and thank you for adding it to your filtre list. Arigatou gozaimasu.
