### ISSUE TITLE
rjno1.com

### ISSUE THREAD

**Issue by trimechee** [bogachenko/fuckfuckadblock#384]
Hello, I have message to disable adblocker in this site : 

`https://www.rjno1.com/`

**Comment by bogachenko** [comment]
I get antiadblock even when adblock is disabled.

**Comment by trimechee** [comment]
Hello @bogachenko  ! I make mistakle, really I am sorry to to have disturbed you, I read the article of Banana 

https://github.com/422658476/banana-detect-adblock

https://github.com/422658476/web-error

and its purpose is to help websites monetize their content and i think it's legit, i think it is not a good thing to fight this ad detector and it's better that i close this issue, thank you vey much :) May be there is message antiadblock beacause you use dns adblock ou custom web browser may be....the developer says we should use chrome or firefox

**Comment by trimechee** [comment]
Here i can use this website without adblock extension : https://www.rjno1.com/mpv-easy-player-en-us/

**Comment by bogachenko** [comment]
>and its purpose is to help websites monetize their content and i think it's legit, i think it is not a good thing to fight this ad detector and it's better that i close this issue, thank you vey much :) May be there is message antiadblock beacause you use dns adblock ou custom web browser may be....the developer says we should use chrome or firefox

Lol
***
Does it work for you?
```
rjno1.com##+js(no-setTimeout-if.js, (), 562)
rjno1.com##+js(no-setTimeout-if.js, (), 1046)
```

**Comment by trimechee** [comment]
Hello, oups i am not developer so i don't know where putting these codes, should i put this code : "rjno1.com##+js(abort-current-inline-script.js, document.getElementById, innerHTML)"

 in custom filters of ublock origin ? or just update the filters of fuckfuckadblock to use the new version ?

**Comment by bogachenko** [comment]
Put it in [My Filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)

**Comment by trimechee** [comment]
I specify that in the parameters of my os windows 10, I put the dns of adguard adblock but for this test, I activate the dns over https of microsoft edge dns google, I do "ipconfig /flushdns" and I put your 3 filters but this site still asks me to deactivate my adblock, I deactivate ublock origin and the site always asks me to deactivate my adblock, maybe this site detects the internal edge browser adblock, the native ad blockjeir of the chromium browsers which blocks heavy ads:

https://source.chromium.org/chromium/chromium/src/+/refs/tags/101.0.4951.54:components/heavy_ad_intervention/heavy_ad_features.cc


to circumvent this filter, perhaps read his article which technical explanation:

https://github-com.translate.goog/422658476/web-error?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by bogachenko** [comment]
Refresh the list @trimechee , is it working now?

**Comment by trimechee** [comment]
Awesome !! Thank you very much for all your efforts and generosity ! 💯 🥇
