### ISSUE TITLE
Anti-Paywall support

### ISSUE THREAD

**Issue by trimechee** [bogachenko/fuckfuckadblock#386]
Hello, i find these specefic filters and it says :"Click here to add Anti-Paywall list" , it will be great to integrate these filers, thank you very much ! 

`https://github.com/liamengland1/miscfilters`

**Comment by trimechee** [comment]
Hello, i find this article to bypass paywalls, may be , if technically possible, it will be great to  integrate in fuckfuckadblock some tricks ou filters ot these solutions and extensions to bypass paywalls, thank you !

https://www.online-tech-tips.com/computer-tips/12-ways-to-get-past-a-paywall/

**Comment by bogachenko** [comment]
I'll look later, it's not a quick process anyway.

**Comment by trimechee** [comment]
Great ! Thank you very much 🥇

**Comment by bogachenko** [comment]
More than half (all sites not tested) open normally and/or are fixed in uBO's default lists, it's best to report issue sites upon receiving an issue.
