### ISSUE TITLE
minecraft-schematics.com

### ISSUE THREAD

**Issue by Enzodtz** [bogachenko/fuckfuckadblock#387]
### Basic information

**Check the link:** `https://www.minecraft-schematics.com/register/`
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:** Chrome 109.0.5414.120 
**Adblocker:** AdGuard 4.1.53
**Extensions:** None

**Comment by bogachenko** [comment]
>Adblocker: AdGuard 4.1.53

What subscriptions do you use?

>DNS:

You removed this item, why?

**Comment by Enzodtz** [comment]
Hi, 

Sorry, I removed the DNS because I use no particular one. Probably that 8.8.8.8 one from google, right? 

Please take a look on `ipconfig /all` ethernet adapter output:

```
Ethernet Ethernet Adapter:
   ... 
   DNS Servers. . . . . . . . . . . . . . . : 192.168.15.1
                                                 fe80::f654:20ff:feab:a580%12
   ...
```
I'm not exactly sure about my subscriptions. I think that you meant that filters tab? I have "AdGuard's base filter", French, Russian, Chinese, German, Japanese, Spanish/Portuguese filters from adguard, EasyList Italy (from adguard too), EasyList Thai (adguard's) and List-KR (also adguard's). They also mention this "Filter for allowing useful ads and autopromotion ones". And obviously, fuckfuckadblock. "Filter for adguard DNS" is disabled.

If you need any more information please ask me.

**Comment by bogachenko** [comment]
You have too many 3rd party subscriptions, you can only check this site with AdGuard Base filter, Tracking Protection filter, Annoyances filter and Fuck Fuckadblock.

**Comment by Enzodtz** [comment]
Right, I disabled all filters but the base one and the error still remains.

**Comment by bogachenko** [comment]
Seems to be fixed, Update filters after 3-5 minutes and check.

**Comment by Enzodtz** [comment]
Hi, thanks for your help. Unfortunately, it seems that it's still there. Since you couldn't reproduce, here's a screenshot of the banner. 

![image](https://user-images.githubusercontent.com/7780770/216036785-02d89187-f6d3-4e3b-a3fb-f54ec095da6f.png)

Maybe this `Powererd by Admiral` could be useful?

**Comment by bogachenko** [comment]
2 questions,

when you installed my filter, did you check the box "Trusted"?
Go to the network request log and look (if you have checked the "Trusted" checkbox) at the very top of the log in pale yellow there is [the rule for the HTML type](https://github.com/bogachenko/fuckfuckadblock/commit/4814bedd0e82828002dceae9fd7d97c22827fc02) from my sheet - `minecraft-schematics.com##+js(abort-current-inline-script.js, document.createElement, admiral)` ?

**Comment by Enzodtz** [comment]
It seems that I had to update the filters. I thought that it would refresh automatically. Now it is working. Thanks a lot for your help!
