### ISSUE TITLE
Filters anti coin crypto mining

### ISSUE THREAD

**Issue by trimechee** [bogachenko/fuckfuckadblock#389]
Hello,  the real danger on the internet is crypto currency mining,  crypto mining techniques are becoming so sophisticated that mining just uses a small amount of cpu power without user noticing it, a press article talked about it .... unfortunately many browsers and even adblock and dns adblock don't say they block all malicious crypto coin currency mining sites by default, I tried to search and I found this site zerodot1 but and i tried to add his filters  to ublock origin but it doesn't work :( it will be great if fuckfuckadblock add option or make a second verson special anti-coin mining version to adding zerodot list and also olbat list and ShadowWhisperer and block list projcet list anti coin lists and if it's technically possible, maybe to unify them in a single list of filters to protect against crypto mining and thus simplify the task for millions users to adding these filters in one click because it seems difficult to find and add these filters especially since on the zerodot site, the download filters button does not work....thank you very much !

https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html

https://github.com/ShadowWhisperer/BlockLists

https://github.com/olbat/ut1-blacklists

https://github.com/blocklistproject/Lists

https://github.com/hoshsadiq/adblock-nocoin-list/

**Comment by bogachenko** [comment]
Only anti-adblock and pop-up ads

**Comment by bogachenko** [comment]
So far, I don’t see the point in this, the list of rules from hoshsadiq is not bad (in conjunction with uBlock filters - Resource abuse), but the idea is not bad, after all, I often saw mining, especially on video frames (but again, they were always banned by the above lists) .

**Comment by trimechee** [comment]
Hoshsadiq seems to have selective filters but not many, that's good, and zerodot has many sites, , it seems ublock origin ha said it can integratre more anti mining list but filter should respect the synstax end rules of ublock origin...ohh "I often saw mining, especially on video frames ", so are we protected from from mining video frames when we use ublock origin ? or when we use your filters please ?

**Comment by bogachenko** [comment]
> I have another question please, I have brave browser in reserve, I avoid installing ublock origin on brave to avoid possible conflict, I noticed that brave has an option to add our own addresses or filters... I I didn't really understand how to do it, are fuckfuckadblock's filters compatible with the native ad blocker of brave browser please?

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#brave-shields

When I checked six months ago, everything worked. But I would recommend ~in addition to the obvious - to abandon the use of Brave~ to abandon the built-in adblock in favor of uBO, because the latter has much more functions available.

>I expected to see hundreds of thousands of crypto sites in the list, did you include in this list all the sites from the lists of zerodot1, olbat, block list project, shadowwhisperer....?

These are their lists, not mine. I can't trust them and add them to my list automatically, because there may be false positives, as well as dead domains. This can have a bad effect on the image of the repository, such actions are very long in nature. You don't think that I copied and pasted my original Fuck Fuckadblock sheet from somewhere and here it is so big, no, it's a long and hard work - 3-4 years, with FFA Miner, too, the same situation, do not wait for everything at once.

**Comment by bogachenko** [comment]
Nope. Native - no, as far as I remember, there is very poor functionality, scriptlets from uBO will not work, and again, as far as I remember, third-party sheets cannot be installed in it, you can create filters there that very modestly hide the page content.

For information: Yandex, our terrible - Russian company (probably only Mail.ru Company is worse), in terms of blocking ads, they will interfere with you, third-party extensions will not work correctly, [for ex](https://github.com/AdguardTeam/AdguardFilters/issues/128412#issuecomment-1233937163) or [ex](https://github.com/AdguardTeam/AdguardFilters/issues/128412#issuecomment-1233937163).

**Comment by bogachenko** [comment]
>yandex android said "Our browser currently supports only AdGuard Content Blocker and Adblock Fast.

as I said https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#adguard-content-blocker

**Comment by bogachenko** [comment]
>Dnscache
>more effective ad blocking

where's the connection? Maybe I don't understand something, but this service was not created for this. And resetting it, as well as disabling it, as far as I know, does not entail effective ad blocking, but entails:

a) confidentiality (redirection to another ip - often this is done to hack PS4 game consoles, but on a computer with this didn’t deal, although nothing prevents an attacker from redirecting you to the ip he needs if your cache is corrupted).

b) a fresh ip for sites (if the site has switched to another ip, cleaning is necessary, because a 404 error may occur).

c) decrease in page opening speed.

**Comment by trimechee** [comment]
Thank you for these very intersting informations and i follow you in reddit and telegram 🥇 

sorry that seems offtopic .... i think I speak about adblock and dns client service to disable to block ads because i read this : 

https://winhelp2002.mvps.org/hosts.htm

"Windows DNS Client Service

Microsoft has done it again ... making changes to the Operating System, without any kind of explanation. If you upgraded recently to Windows 10 version 1709, most likely you will be unable to make any changes to the DNS Client, as it is grayed out. However if you had previously Disabled or set to Manual, the DNS Client Service you can still do so. Then to make things even worse ... the work-around Registry entries (see below) no longer apply in Windows 10/1709 ... they are simply ignored. To check your Windows version ... right-click the Start Menu and select > Run (type) winver (click OK)

Thankfully Keith M sends along the following workaround ...

From [sysinternals.com](https://docs.microsoft.com/en-us/sysinternals/) download the latest version of AUTORUNS ... it doesn't require any installation.
Run autoruns64.exe as ADMINISTRATOR and wait until it finishes it's scan.
In the program menu under OPTIONS, uncheck the "Hide Windows Entries" option
Go to the Services tab, scroll down to the Dnscache entry and clear (uncheck) the checkmark.
You can FILE / SAVE, to save a copy of the new configuration settings.
Close autoruns64, reboot and check the services manager -- DNS Client is disabled. [[screenshot](https://winhelp2002.mvps.org/autoruns.jpg)]
If you decide that you want the DNS Client service running ... You can make a little batch file that will flush the DNS whenever you desire.
Open Notepad and enter the following:

ipconfig /flushdns

Then File > Save As > change the file type to All files, and name the batch file to flushdns.bat and place it in your Windows folder.

Locate flushdns.bat right-click and select Send To > Desktop as shortcut.

Windows 10 (early versions) /8

In most cases the DNS Client Service is not needed, it is recommended to turn it off. These instructions are intended for a single (home-user) PC. If your machine is part of a "Domain", check with your IT Dept. before applying this work-around. This especially applies to Laptop users who travel or bring their work machines home. Make sure to reset the Service (if needed) prior to connecting (reboot required) to your work Domain ...

To resolve this issue (manually) open the "Services Editor"

Start | Run (type) "services.msc" (no quotes)
Win8 users - Control Panel > Administrative Tools > Services
Scroll down to "DNS Client", Right-click and select: Properties - click Stop
Click the drop-down arrow for "Startup type"
Select: Manual (recommended) or Disabled  click Apply/Ok and restart.
 [Hostsman](https://winhelp2002.mvps.org/hosts.htm#Related) includes an option to turn off the DNS Service [[screenshot](https://winhelp2002.mvps.org/hostsmandns.jpg)]

When set to Manual you can see that the above "Service" is not needed (after a little browsing - when set to Manual) by opening the Services Editor again, scroll down to DNS Client and check the "Status" column. It should be blank, if it was needed it would show "Started" in that column. There are several Utilities that can reset the DNS Client for you ... [[more info](https://winhelp2002.mvps.org/hosts.htm#Related)]

Important! If you are using [Network Discovery](http://windows.microsoft.com/en-US/windows7/What-is-network-discovery) then the DNS Client service is required and should not be set to either Manual or Disabled.

Workaround for using the MVPS HOSTS file and leaving the DNS Client service enabled (set to: Automatic)

If you find after a period of time that your browser seems sluggish with the DNS Client service enabled you can manually flush the DNS cache
Close all browser windows ... open a "Command Prompt" from the Start Menu > All Programs > Accessories > Command Prompt
Win8 users - Charms Bar > Search > (type) command prompt > Select: Command Promt (left pane) Ok the UAC prompt
(type) ipconfig /flushdns (press Enter) Then close the Command Prompt ...
A better Win10/8 workaround would be to add two Registry entries to control the amount of time the DNS cache is saved. ([KB318803](http://support.microsoft.com/kb/318803))

Flush the existing DNS cache (see above)
Start > Run (type) regedit
Win8 users - from the Charms Bar, select: Search (type) run and select Run (left pane) and (type) "regedit" (no quotes)
Navigate to the following location:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters
Click Edit > New > DWORD Value (type) MaxCacheTtl
Click Edit > New > DWORD Value (type) MaxNegativeCacheTtl
Next right-click on the MaxCacheTtl entry (right pane) and select: Modify and change the value to 1
The MaxNegativeCacheTtl entry should already have a value of 0 (leave it that way - see [screenshot](https://winhelp2002.mvps.org/dnscache.jpg))
Close Regedit and reboot ...
As usual you should always backup your Registry before editing ... see Regedit Help under "Exporting Registry files"
 For all other Questions, Issues and Solutions - see:[The HOSTS File FAQ](https://winhelp2002.mvps.org/hostsfaq.htm)
 For detailed Download and Extract Instructions - see: [Download Help](https://winhelp2002.mvps.org/hosts2.htm) "

**Comment by trimechee** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/dns-client-service-slow-initialization-if-hosts/1e71d00d-e027-494e-b215-f0e44a9bf392

"DNS Client service slow initialization if hosts file large
System: Windows 10 on Surface book 2 15''

My hosts file in Windows\System32\drivers\etc directory has about 95000 entries (I need that file - it blocks certain web-pages from being accessible by sending their addresses to to 0.0.0.0). After restarting/turning on/waking from hibernation/ the machine, it takes about 5 minutes before the internet connection is established (exactly the same problem existed in Windows 7).  

I believe that MS developers should take a look at the way DNS client service is implemented and optimize it.
