### ISSUE TITLE
vidlii.com

### ISSUE THREAD

**Issue by gir489** [bogachenko/fuckfuckadblock#39]
### Basic information

**Check the link/s:** `https://www.vidlii.com/watch?v=VQfMDJVOwdg`
**Category:** anti-adblock
**Reported from:** USA
**Filter lists:** I was using press the attack, but since you removed it, I took it down, still happens.

### User environment
**Browser:** Chrome 80.0.3987.116
**Extension:** AdGuard Version 3.3.8

**Comment by bogachenko** [comment]
>I was using press the attack, but since you removed it

I did not delete it, I renamed the repository - https://github.com/bogachenko/filterlist
