### ISSUE TITLE
How to use "CDN Filters"?

### ISSUE THREAD

**Issue by Insidevk18** [bogachenko/fuckfuckadblock#392]
### Additional message

Hello good morning. Sorry for the inconvenience, I wanted to see how the "CDN Filters" are used.
Are "LocalCDN" or "Decentraleyes" used in the extension?
I have looked for the way to put the links in my "LocalCDN" extension but there is no section for it apparently.
Thank you.

**Comment by bogachenko** [comment]
They do not need to be installed anywhere except uBO or AdGuard. Use this installation guide https://github.com/bogachenko/fuckfuckadblock/wiki/Installation-instruction
