### ISSUE TITLE
tii.la

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#400]
### Basic information

**Check the link:**  `https://tii.la/8fIjORyg`
**Category:** Anti-adblock
**Reported from:**  Indonesia

### User environment

**Browser:**  Latest Chrome
**Adblocker:**  Latest Ublock Origin
**Extensions:**  -
**DNS:**  -

**Comment by bogachenko** [comment]
Duplicate of #167
