### ISSUE TITLE
3kh0.net

### ISSUE THREAD

**Issue by Rahib777-7** [bogachenko/fuckfuckadblock#403]
### Basic information

**Check the link:** `https://3kh0.net/`
**Category:** Anti-adblock
**Reported from:** United States of America
### User environment

**Browser:**  Mobile Safari 16.1.1 
**Adblocker:**  Hyperweb
**Extensions:**  N/A
**DNS:**  NextDNS

### Additional message

shows blocking msg

**Comment by bogachenko** [comment]
>Browser: Mobile Safari 16.1.1

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#ios-and-macos

It won't work. You bought Apple products - sad.
