### ISSUE TITLE
filecr.com

### ISSUE THREAD

**Issue by zekecarter** [bogachenko/fuckfuckadblock#404]
### Basic information

**Check the link:** `https://filecr.com/`
**Category:** Anti-adblock
**Reported from:** Republic of Panama (Central America)

### User environment
**Browser:** Brave Versión 1.49.120 x64
**Adblocker:** uBlock Origin
**Extensions:** N/A
**DNS:** N/A

### Additional message:
filecr.com updated the page and when you click on download you get the window as in the image and fuckfuckadblock.txt does not work, could you update it?

**Comment by bogachenko** [comment]
please **don't upload images here!**

**Comment by bogachenko** [comment]
I can't reproduce the problem, which subscriptions have you activated in uBO - by default and FFA?

**Comment by zekecarter** [comment]
> I can't reproduce the problem, which subscriptions have you activated in uBO - by default and FFA?
> 
> PS: what are the subscriptions for your country by default?
> 
> > Reported from: Republic of Panama (Central America)

Can I send a test video?

**Comment by bogachenko** [comment]
nope. Go to ubo settings on the - Support tab, scroll down and copy the troubleshooting field

**Comment by zekecarter** [comment]
> Nope. Go to uBo settings on the - `Support` tab, scroll down and copy the `Troubleshooting` field. Paste it here.

this?

uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 88039
  cosmetic: 44817
  scriptlet: 17653
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 63372-534, never
    easyprivacy: 31007-1147, never
    plowe-0: 3751-590, never
    spa-0: 3541-150, never
    spa-1: 5132-66, never
    ublock-abuse: 78-0, never
    ublock-badware: 4611-0, never
    ublock-filters: 32807-116, never
    ublock-privacy: 287-0, never
    ublock-quick-fixes: 340-16, never
    ublock-unbreak: 1922-33, never
    urlhaus-1: 6492-0, never
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 872 ms
  maxAssetCacheWait: 4 ms

**Comment by bogachenko** [comment]
Yep, this. Answer the question above, please.

**Comment by zekecarter** [comment]
> Yep, this. Answer the question above, please.

I have updated the page now it shows different information.
I use the fuckfuckadblock in the custom filter of the brave browser, hope this works for you

uBlock Origin: 1.47.4
Chromium: 111
filterset (summary): 
  network: 89615
  cosmetic: 44757
  scriptlet: 17318
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 0-0, never
    easylist: 64293-44, 12m
    easyprivacy: 31065-1172, 11m
    plowe-0: 3752-931, 10m
    spa-0: 3541-11, 15m
    spa-1: 5132-194, 15m
    ublock-abuse: 78-0, 8m
    ublock-badware: 5099-114, 6m
    ublock-filters: 32027-119, 5m
    ublock-privacy: 293-1, 4m
    ublock-quick-fixes: 421-7, 3m
    ublock-unbreak: 1937-41, 2m
    urlhaus-1: 6859-0, 1m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 872 ms
  maxAssetCacheWait: 115 ms

**Comment by bogachenko** [comment]
> I use the fuckfuckadblock in the custom filter of the brave browser, hope this works for you

What does it mean? Does this mean that you have installed FFA in the built-in adblock of the Brave browser and together with this you are still using uBO?

**Comment by zekecarter** [comment]
> > I use the fuckfuckadblock in the custom filter of the brave browser, hope this works for you
> 
> What does it mean? Does this mean that you have installed FFA in the built-in adblock of the Brave browser and together with this you are still using uBO? Correct? If yes (because I don't see my sheet in the Troubleshooting field), please read this https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#brave-shields

i used to use brave browser and i activated all the ad blockers and additionally i added the FFA in the custom filter and it worked fine. and since it didn't work for me i tried installing the uBo extension optionally but it didn't work either. what would be your recommendation?

**Comment by bogachenko** [comment]
Please, disable the built-in ad blocker from the Brave Browser (and other extensions for blocking ads) and enable ONLY uBO, _only it and that's it_. In it, reset all the default settings (in the settings, this is the first tab at the very bottom of the page) and install my list, update all filters and go to this problematic site and check

**Comment by zekecarter** [comment]
> Please, disable the built-in ad blocker from the Brave Browser (and other extensions for blocking ads) and enable ONLY uBO, _only it and that's it_. In it, reset all the default settings (in the settings, this is the first tab at the very bottom of the page) and install my list, update all filters and go to this problematic site and check

ok... testing

**Comment by zekecarter** [comment]
> Please, disable the built-in ad blocker from the Brave Browser (and other extensions for blocking ads) and enable ONLY uBO, _only it and that's it_. In it, reset all the default settings (in the settings, this is the first tab at the very bottom of the page) and install my list, update all filters and go to this problematic site and check

sorry it didn't work. watch the video, as soon as you watch the video I will delete it.
[Video 0:45 second](https://www.youtube.com/watch?v=2Vja6GlCmGg)

**Comment by bogachenko** [comment]
Not right. On the website, click on the lion icon in the address bar and switch from on to off "Shield" and check.

**Comment by zekecarter** [comment]
> Not right. On the website, click on the lion icon in the address bar and switch from on to off "Shield" and check.

it worked with the aBo extension, it is a pity that it no longer works directly with the brave browser, yesterday it worked and today it doesn't, thank you very much.

**Comment by bogachenko** [comment]
You cannot use 2 ad blockers. There will always be problems, if not today, then tomorrow.

#### I don't use a Brave browser, you have disabled the built-in adblock, only for the current page, you can find on the Internet how to disable it permanently.
