### ISSUE TITLE
helmiau.com

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#405]
### Basic information

**Check the link:**  `https://www.helmiau.com/blog/helmiwrt-os`
**Category:** Breakage
**Reported from:**  Indonesia

### User environment

**Browser:**  Chrome Latest
**Adblocker:**  Ublock Origin
**Extensions:**  -
**DNS:**  -

**Comment by bogachenko** [comment]
Why are you opening another topic for this site when there is already one?
***
> Category: Breakage

Do you mean anti adblock?

**Comment by bogachenko** [comment]
Duplicate of #334
