### ISSUE TITLE
YouTube & Twitter Notifications

### ISSUE THREAD

**Issue by HDark15** [bogachenko/fuckfuckadblock#409]
Can't get notifications and on YouTube the Desktop notifications toggle not showing
Unless this get allowed

![firefox_HCTNuRAJFR](https://user-images.githubusercontent.com/34807171/230723719-7c419e9b-1413-4044-a017-4b2bdeea5d04.jpg)
![firefox_L99o8nIKVN](https://user-images.githubusercontent.com/34807171/230723722-a247e333-0781-4ab1-a200-8d0e21e9092e.jpg)

**Comment by bogachenko** [comment]
Sorry, in "service worker.js" often insert (pop-up) ads on all sorts of dubious sites. About `youtube.com` and `twitter.com` (of course there is no ads there) false positive.

**Comment by bogachenko** [comment]
>sorry I don't see the rules for that.

hands do not reach. now created [this rule](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy/_compare/381224b948f777b3b1f3911123df43a7aec46bb0...759ae277c4a77841414d7e620d764eeb2f0863c4) in the wiki.

>Why I can't post images here?

The lack of privacy and cluttering of the Issues tab with images is confusing, everything that can be said in language is not necessary to show.
