### ISSUE TITLE
fcd.su

### ISSUE THREAD

**Issue by Meldoner** [bogachenko/fuckfuckadblock#411]
### Basic information

**Check the link:** `https://n.fcd.su/QIQ`
**Category:** Anti-adblock
**Reported from:** Russia

### User environment

**Browser:** Google Chrome
**Adblocker:** uBlock
**DNS:** -

### Additional message
Doesn't let me into the site when adblock is on, fuckadblock doesn't help

**Comment by bogachenko** [comment]
Не совсем понимаю о чем ты, ты закрываешь модальное окно с просьбой разрешить уведомление (появляется через секунд 5 в правом верхнем углу) и скачиваешь => `https://n.fcd.su/QIQ/3augg` => `https://xfiley.me/6d7093d009303ec92bf320610e146b2arjr4tr5GL1tmR/yy35uS3bvCkADr015ZlfSMoI99MvKLldU` => `https://xfiley.me/2740ab5a5d9ad446ecd32a4c0472bfafTOdA/--rFsuTJQt1KGJ5kOuWCY4AiGiDmODTSOfsXfjl` => `https://xfiley.me/ad35cf50d263926ef9a43fd187eddbb1JhpBkX/fGbiV4AemoplKEXjx4dVVZ6xtW6OkKgM8aWiIoKAY` и скачиваешь свой файл `vash-fayl_CrcR4O9d.zip`
