### ISSUE TITLE
release-apk.com

### ISSUE THREAD

**Issue by gosndka** [bogachenko/fuckfuckadblock#412]
### Basic information

**Check the link:** `https://forum.release-apk.com/viewtopic.php?f=26&t=147141&p=175928#p175928`
**Category:** Anti-adblock
**Reported from:** IN

### User environment

**Browser:** Firefox 112.0.1
**Adblocker:**  Ublock origin 1.48.4
**Extensions:**  None
**DNS:**  Google dns

### Additional message

Both registered users and unregistered users face Antiadblock.

**Comment by bogachenko** [comment]
I can't reproduce the problem, did you follow [these](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#before-sending-a-report) steps?

**Comment by gosndka** [comment]
> I can't reproduce the problem, did you follow [these](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#before-sending-a-report) steps?

Yes, I have followed these steps. But as I was searching I found a similar request in uassets. https://github.com/uBlockOrigin/uAssets/issues/17626. After updating the filters once again, the browser becomes unresponsive and my whole system hangs.

**Comment by bogachenko** [comment]
So there, too, they advise what I threw above, they also cannot reproduce.

**Comment by bogachenko** [comment]
I still can't reproduce it, but I've added the basic rules.

**Comment by gosndka** [comment]
> So there, too, they advise what I threw above, they also cannot reproduce.

Could you register in the forum and check the below link? @bogachenko 

https://forum.release-apk.com/viewtopic.php?f=8&t=147236&p=176033#p176033

**Comment by bogachenko** [comment]
It's strange, how the bypass does not always work.
One time there is, updated the page - no, and so again and again.

**Comment by bogachenko** [comment]
To tell the truth, I think they have some kind of broken script for checking the use of an ad blocker for the end user, I have a notification for a couple of seconds even when the ad blocker is disabled and then disappears.

**Comment by bogachenko** [comment]
Added the site release-apk.com into [unsupported ones](https://github.com/bogachenko/fuckfuckadblock/wiki/Unsupported-sites/_compare/2703db454cf5930eb0102bacd4465be79a65c2c2...f822a9de60b36090b7c869ca93de05476c8f66ff). There is no way around this. The site loads the system heavily, and the block is triggered without using an ad blocker.
