### ISSUE TITLE
Not working on megaup.net

### ISSUE THREAD

**Issue by AlexIs387** [bogachenko/fuckfuckadblock#419]
When? Never?

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/issues/417#issuecomment-1522876873

**Comment by AlexIs387** [comment]
What did we have to provide? it's happening on ANY megaup.net link with ANY file to download, I tell you with the best vibes in the world: if you are tired of doing this, work as something you are really passionate about

**Comment by bogachenko** [comment]
At the beginning of your "report" everything worked, now I was able to reproduce the problem.

_Thank you for providing the information about which I wrote above._
