### ISSUE TITLE
textfonts.net

### ISSUE THREAD

**Issue by vavavr00m** [bogachenko/fuckfuckadblock#424]
### Basic information

**Check the link:**  `https://textfonts.net/`
**Category:** Anti-adblock
**Reported from:**  Philippines

### User environment

**Browser:**  Chrome 113.0.5672.93 (Official Build) (64-bit)
**Adblocker:**  uBlock Origin 1.49.2
**Extensions:**  Too many to mention but already tried uBlock Origin alone and still the same
**DNS:**  None

### Additional message

```
Adblock Detected!
Our website is made possible by displaying online advertisements to our visitors.
Please consider supporting us by whitelisting our website.
```

**Comment by bogachenko** [comment]
**Hi, please don't upload images here.**
You may also have problems with my list with uBO, I recommend reading this [comment](https://github.com/bogachenko/fuckfuckadblock/issues/423#issuecomment-1547054945).

**Comment by vavavr00m** [comment]
> **Hi, please don't upload images here.** 

Noted.

> You may also have problems with my list with uBO, I recommend reading this [comment](https://github.com/bogachenko/fuckfuckadblock/issues/423#issuecomment-1547054945).

Already seen it yesterday and updated it. Thanks!
