### ISSUE TITLE
drugs.com

### ISSUE THREAD

**Issue by Dreaming-Codes** [bogachenko/fuckfuckadblock#425]
### Basic information

**Check the link:** `https://www.drugs.com/`
**Category:** Anti-adblock
**Reported from:** Italy

### User environment

**Browser:** Chrome 113.0.5672.92
**Adblocker:**  AdNauseam 3.16.2b0 based on uBlock Origin v1.45.0
**Extensions:** None
**DNS:** Cloudflare DNS

### Additional message
```
www.drugs.com##.fc-ab-root
www.drugs.com##body:style(overflow: auto !important)
```

**Comment by bogachenko** [comment]
Hi, I can't reproduce it. Please go to the uBO settings in the Support tab, and find the Troubleshooting field, copy and paste everything in this field here in the comments.

**Comment by Dreaming-Codes** [comment]
> Hi, I can't reproduce it. Please go to the uBO settings in the Support tab, and find the Troubleshooting field, copy and paste everything in this field here in the comments.

AdNauseam: 3.16.2b0
Chromium: 113
filterset (summary): 
  network: 81714
  cosmetic: 124412
  scriptlet: 50419
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    easyprivacy: null
    eff-dnt-whitelist: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt?_=3: 182-0, 14h.51m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=3: 24230-14, 14h.51m
    https://www.joinhoney.com/whitelist/honey-smart-shopping.txt: 0-0, 14h.51m
    ITA-0: 12992-0, 14h.51m
    adguard-generic: 71157-1274, 14h.51m
    fanboy-cookiemonster: 47188-140, 14h.51m
  default: 
    user-filters: 0-0, never
    adnauseam-filters: 506-7, 14h.51m
    easylist: 66109-833, 14h.51m
    ublock-abuse: 70-3, 14h.51m
    ublock-badware: 7144-358, 14h.51m
    ublock-filters: 33060-5836, 14h.51m
    ublock-privacy: 392-72, 14h.51m
    ublock-quick-fixes: 359-36, 14h.51m
    ublock-unbreak: 2017-69, 14h.51m
filterset (user): [empty]
trustedset: 
  added: [array of 5 redacted]
modifiedUserSettings: 
  admap: [redacted]
  eventLogging: true
  firstInstall: false
  hidingAds: true
  clickingAds: true
  hyperlinkAuditingDisabled: false
  prefetchingDisabled: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2105 ms (selfie)
  maxAssetCacheWait: 240 ms

**Comment by Dreaming-Codes** [comment]
> * Clear cookies, cache and localStorage.

Tried


> * Do you have antiviruses or other blocking applications?

No


> * Do you use Cloudflare DNS directly? Don't you use programs similar to pi-hole or adguard home?

Directly


> * hosts.txt empty?

I'm on linux and /etc/hosts is empty


> * Can you try to reproduce this problem on another browser?

Yes, same on Firefox


> * Can you disable (temporarily?) this list honey-smart-shopping.txt

Tried, same result

Anyway, I have fixed this problem with:
```
www.drugs.com##.fc-ab-root
www.drugs.com##body:style(overflow: auto !important)
```
So if this is affecting only me, I think that you can close this as solved.

**Comment by bogachenko** [comment]
>Anyway, I have fixed this problem with:
`www.drugs.com##.fc-ab-root`
`www.drugs.com##body:style(overflow: auto !important)`

This is not the point, what you describe should be removed by the "generichide" rule, which is on my list.

**Comment by Dreaming-Codes** [comment]
> Are you talking about this?\n\nWelcome to drugs.com.\nPlease allow ads on our site.\nLooks like you're using an ad blocker. We rely solely on advertising to fund our site.\nUnblock ads for Drugs.com\n

Yes, going to try with uBO instead tomorrow

**Comment by bogachenko** [comment]
So did you install? I'm only able to reproduce your problem if I add the "badfilter" flag to `@@*$generichide,domain=drugs.com` to make it  `@@*$generichide,domain=drugs.com,badfilter` to "My Filters" which deactivates the generichide rule.

In other cases, the rule `@@*$generichide,domain=drugs.com` removes this notice.
