### ISSUE TITLE
Fuckfuckadblock added to uBlock badlists?

### ISSUE THREAD

**Issue by RicoHeat** [bogachenko/fuckfuckadblock#429]
<! https://github.com/uBlockOrigin/uAssets/raw/master/filters/badlists.txt --> The following was added to badlists.
# interfere negatively; generic exceptions to ad servers
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt
https://cdn.statically.io/gh/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt
https://raw.githack.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt
https://cdn.jsdelivr.net/gh/bogachenko/fuckfuckadblock/fuckfuckadblock.txt
https://cdn.jsdelivr.net/gh/bogachenko/fuckfuckadblock@master/fuckfuckadblock.txt
https://fuckfuckadblock.pages.dev/fuckfuckadblock.txt

**Comment by bogachenko** [comment]
~Congratulations on connecting to the Internet.~

They added it a long time ago #423, without clearly explaining the reason. Imposing your opinion is now the rule for gorhill.
