### ISSUE TITLE
tii.la

### ISSUE THREAD

**Issue by 0xh3LL0** [bogachenko/fuckfuckadblock#434]
### Basic information

**Check the link:** `https://tii.la/Sgi0jYdu`
**Category:** Breakage
**Reported from:** Indonesia

### User environment

**Browser:** Firefox 107
**Adblocker:** uBlock Origin 1.49.2
**Extensions:** channel blocker, tampermonkey, stylus, fastforward

**Comment by bogachenko** [comment]
Please do not open new topics about problematic sites if already have the necessary tickets.

**Comment by bogachenko** [comment]
Duplicate of #167
