### ISSUE TITLE
New unified unique crypto miners blocklist

### ISSUE THREAD

**Issue by trimechee** [bogachenko/fuckfuckadblock#435]
Hello, thank you so much for making a wonderful anti-cryptojacking list ! 🥇 

I have a suggestion please : make a unique unfied list to block all legitimate or non-legitimate crypto miners from all over the world because some miners use sophisticated techniques to only use a small amount of CPU power which makes it undetectable, and many people don't use crypto, these lists are scattered all over the web and it's hard to put them together so it will be great to make one unified blocklist containing all the crypto in the world so we can add them easily to our ad blocker or our custom dns via rethink dns or blitz ahadns or control d dns or next dns and this list would be updated often and thus no need to go searching in the different sites, thank you very much !

https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issuable_template=CryptoMiner
https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/cryptojacking/domains
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.txt
https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_UBO.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt
https://blocklistproject.github.io/Lists/adguard/crypto-ags.txt
https://blocklistproject.github.io/Lists/crypto.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_browser
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser_AdBlock.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_optional
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_optional.txt

**Comment by bogachenko** [comment]
Only real cases will get into the list, copy and paste is not suitable.
