### ISSUE TITLE
Circumvention ads

### ISSUE THREAD

**Issue by trimechee** [bogachenko/fuckfuckadblock#437]
Hello, it will be great to add these important filters to fight "circumvention ads" because Some providers have begun to show ads that are harder to detect for ad-blocking tools like ABP, thus tricking ad-blocker users into downloading and displaying unrequested and intrusive advertising ("circumvention ads").! 

Thank you !

https://github.com/abp-filters/abp-filters-anti-cv

**Comment by bogachenko** [comment]
I know about this repo, sometimes I take cases from them.
