### ISSUE TITLE
bsshotel.it

### ISSUE THREAD

**Issue by xAstroBoy** [bogachenko/fuckfuckadblock#440]
### Basic information

**Check the link:** `https://bsshotel.it/home`
**Category:** Breakage
**Reported from:**  Italy
### User environment

**Browser:** Chrome (Latest)
**Adblocker:** Ublock Origins
**Extensions:** None

**Comment by xAstroBoy** [comment]
Anti-adblock seems no not be effective any longer, the filter seems to not work here.

**Comment by xAstroBoy** [comment]
I made a tampermonkey script to block the client script to redirect to the disable adblock page.

**Comment by xAstroBoy** [comment]
Make a account, enter the client and after a bit the site will kick you out with the anti-adblock page

**Comment by bogachenko** [comment]
Okay, now I can reproduce, you should have warned right away that you need an account.

**Comment by xAstroBoy** [comment]
> Okay, now I can reproduce, you should have warned right away that you need an account.

Oh okay, im sorry
