### ISSUE TITLE
warungkomik.com

### ISSUE THREAD

**Issue by rheznendra** [bogachenko/fuckfuckadblock#443]
### Basic information

**Check the link:** `https://warungkomik.com`
**Category:** Anti-adblock
**Reported from:** Indonesia

### User environment

**Browser:** Vivaldi
**Adblocker:** Adguard

**Comment by rheznendra** [comment]
anti adblock is back again on this site, and the script generate aab element like every couple second

**Comment by rheznendra** [comment]
nvm, i found it.
`||warungkomik.com/wp-content/uploads/hgwuzv.js`

**Comment by bogachenko** [comment]
Updated the rule. Now it should work, although not for long - they will update it again.
