### ISSUE TITLE
viptools.es

### ISSUE THREAD

**Issue by animetrom** [bogachenko/fuckfuckadblock#444]
**Check the link:** viptools.es
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:** Firefox
**Adblocker:** Firefox 113.0.1
**Extensions:** Tampermonkey
**DNS:** None

**Comment by bogachenko** [comment]
There is a redirection from the website viptools.es to zefoy.com

`@@||pagead2.googlesyndication.com^$script,domain=zefoy.com`

**Comment by animetrom** [comment]
Thanks
