### ISSUE TITLE
onehack.us

### ISSUE THREAD

**Issue by maspodil** [bogachenko/fuckfuckadblock#45]
### Basic information

**Check the link/s:** `https://onehack.us/`
**Category:** anti-adblock
**Reported from:** US
**Filter lists:** default Ubo and this one

### User environment
**Browser:** Firefox 74.0
**Extension:**  Ublock origin 1.25.2

**Comment by maspodil** [comment]
It still is blocking my UBo @bogachenko

**Comment by maspodil** [comment]
![Capture](https://user-images.githubusercontent.com/62073132/76681231-e1b0de80-6616-11ea-9200-d22de5d6d8bd.PNG)
Please see the above image it's still blocking ubo @bogachenko

**Comment by bogachenko** [comment]
Clean the cookie, it should be all right. I can't reproduce it anymore.

**Comment by maspodil** [comment]
thanks it works now

**Comment by maspodil** [comment]
Sorry to bother you again but the website again started to block my Ubo @bogachenko
