### ISSUE TITLE
Update link broken

### ISSUE THREAD

**Issue by swathigrate** [bogachenko/fuckfuckadblock#452]
Hello sir ,
File is not updating link is broken... Please check once
Using kiwi browser+Temper monkey

**Comment by iam-py-test** [comment]
This filterlist is blocked from being installed in uBlock Origin, and for good reason. FFAB contains overly broad rules which open you up to tracking and ads. uBlock Origin's default filterlists are perfectly capable in terms of defusing anti-blocker.

Also, Kiwi Browser is not supported by uBlock Origin. Firefox Mobile is the only browser supported on Android.
Kiwi Browser also disables uBlock Origin on many websites (including some ad sites), reducing your protection from ads, trackers, and malware.
Thanks

**Comment by swathigrate** [comment]
> This filterlist is blocked from being installed in uBlock Origin, and for good reason. FFAB contains overly broad rules which open you up to tracking and ads. uBlock Origin's default filterlists are perfectly capable in terms of defusing anti-blocker.
> 
> Also, Kiwi Browser is not supported by uBlock Origin. Firefox Mobile is the only browser supported on Android. Kiwi Browser also disables uBlock Origin on many websites (including some ad sites), reducing your protection from ads, trackers, and malware. Thanks

Thanks for reply sir....firefox Android Not support to tampermonkey.... that's why using kiwi ......

**Comment by swathigrate** [comment]
![Screenshot_20230905-162928](https://github.com/bogachenko/fuckfuckadblock/assets/14991260/c66ff7de-235d-4669-8bfc-5b3943da8d8e)
Facing same issue with Firefox nighty android

**Comment by bogachenko** [comment]
I apologize.

I have updated the RAW link. View the README file. The person above will soon be banned (he just forgets to take pills, left the attention of doctors in the psycho-dispensary), in order not to rely on me, you can update the link to my list yourself, see
`https://fuckfuckadblock.pages.dev/fuckfuckadblock.txt?_=1`
after the sign `=`, delete the digit `1` and add any word or a random set of letters, for example `Hill-SukMikeHok` to get this `https://fuckfuckadblock.pages.dev/fuckfuckadblock.txt?_=Hill-SukMikeHok`.

**Comment by bogachenko** [comment]
In general, almost all extensions from the PC version of Firefox can be installed in the mobile version of Firefox.

README https://4pda.to/forum/index.php?showtopic=163303&st=13520#entry110337081

>Btw Firefox mobile support tampermonkey too

Yep, and at the same time officially.

**Comment by swathigrate** [comment]
> > > This filterlist is blocked from being installed in uBlock Origin, and for good reason. FFAB contains overly broad rules which open you up to tracking and ads. uBlock Origin's default filterlists are perfectly capable in terms of defusing anti-blocker.
> > > Also, Kiwi Browser is not supported by uBlock Origin. Firefox Mobile is the only browser supported on Android. Kiwi Browser also disables uBlock Origin on many websites (including some ad sites), reducing your protection from ads, trackers, and malware. Thanks
> > 
> > 
> > Thanks for reply sir....firefox Android Not support to tampermonkey.... that's why using kiwi ...... Is it any lite browser which is support tampermonkey +. Ublock+ our filter list.......
> 
> Adguard extension works fine on Kiwi browser. You can try it!!!
> 
> Btw Firefox mobile support tampermonkey too. Or you can install Iceraven browser (Firefox fork) there are many extensions available. You can download here: https://github.com/fork-maintainers/iceraven-browser

Hello sir,,,,

Thank you very much replying and value suggestions.....

.. Actually I installed which is you  suggested.... But not showing any addon in iceraven  browser..... I try to install the Mozilla Firefox addons (xpi)..... Not working......
