### ISSUE TITLE
lendrive.web.id

### ISSUE THREAD

**Issue by akn19** [bogachenko/fuckfuckadblock#453]
### Basic information

**Check the link:** `https://lendrive.web.id/`
**Category:** Anti-adblock
**Reported from:** Indonesia
### User environment

**Browser:** Firefox
**Adblocker:** uBlock Origin 
**Extensions:** None
**DNS:** cloudflare

**Comment by bogachenko** [comment]
I can't reproduce it, please describe in more detail the problem and steps to reproduce it.
