### ISSUE TITLE
motorsport.tv

### ISSUE THREAD

**Issue by xfunnypigx** [bogachenko/fuckfuckadblock#454]
### Basic information

**Check the link:** `https://motorsport.tv/super-gt/video/okayama-race/22169`
**Category:** Anti-adblock
**Reported from:** Germany

### User environment

**Browser:** Firefox 117.0
**Adblocker:** uBlock Origin
**Extensions:** Ghostery
**DNS:** None

**Comment by bogachenko** [comment]
I can't reproduce, which lists you have connected?

**Comment by xfunnypigx** [comment]
Strange. I use both of your lists linked on the repo. Unless you mean all of the ones on ublock?

**Comment by bogachenko** [comment]
in uBO.
***
>Extensions: None
>DNS: None

This data is relevant?

**Comment by bogachenko** [comment]
You have too many subscriptions, leave only the default ones + Fuck Fuckadblock sheets.

The Ghostery extension is not needed, why do you need it if you already have uBO?
