### ISSUE TITLE
doodstream.com

### ISSUE THREAD

**Issue by swathigrate** [bogachenko/fuckfuckadblock#455]
### Basic information

**Check the link:**  `https://doods.pro/d/2mhvms93ml5o`
**Category:** Anti-adblock
**Reported from:**  India

### User environment

**Browser:**  kiwi browser 
**Adblocker:** uBlock Origin
**Extensions:**  Tampermonkey 
**DNS:**  None

### Additional message

 when the time of playing videos showing error like "The publisher doesnt allow adblock, please disable and reload to continue watching!"...popup appears....

Please solve this issue...
Thanks you

**Comment by iam-py-test** [comment]
Kiwi Browser isn't supported by uBo: https://github.com/uBlockOrigin/uBlock-issues/issues/2791
You need to use Firefox Mobile.
Thanks

**Comment by swathigrate** [comment]
> Kiwi Browser isn't supported by uBo: [uBlockOrigin/uBlock-issues#2791](https://github.com/uBlockOrigin/uBlock-issues/issues/2791) You need to use Firefox Mobile. Thanks

Thanks for reply

**Comment by swathigrate** [comment]
![Screenshot_20230911-104446~2](https://github.com/bogachenko/fuckfuckadblock/assets/14991260/5fd4a693-6f05-4321-9992-c59b7161a5ab)
Hello sir , 

Thanks for fast updating....

Just now checked after updating filters.....still showing same error in kiwi browser.....

**Comment by bogachenko** [comment]
Hello, sorry, I can't check in kiwi browser at the moment.

Checked in Firefox PC/Mobile and in Chromium PC, could you change the browser and check?
