### ISSUE TITLE
darkino.online

### ISSUE THREAD

**Issue by KaKi87** [bogachenko/fuckfuckadblock#457]
### Basic information

**Check the link:** `https://www2.darkino.online/download/10280547`
**Category:** Anti-adblock
**Reported from:** France

### User environment

**Browser:** Iceraven 2.9.2
**Adblocker:** uBlock Origin 1.52.0
**Extensions:** None
**DNS:** None

### Additional message

I'm also reproducing the issue on Kiwi 116.0.5845.72, but didn't try with all extensions but uBO disabled because it's my main browser and I didn't want to take off my pants, as you say.

Thanks

**Comment by iam-py-test** [comment]
FYI, Kiwi Browser is not supported by uBlock Origin: https://github.com/uBlockOrigin/uBlock-issues/issues/2791
Thanks

**Comment by KaKi87** [comment]
Well, it works fine.

**Comment by KaKi87** [comment]
Hi,

The site changed their TLD from `online` to `biz` and I didn't had time to test your fix before they did, so I copied it into *My filters* while changing the TLD, but it didn't work.

Maybe they also changed their anti-adblock ?

Thanks
