### ISSUE TITLE
onepagelink.in

### ISSUE THREAD

**Issue by gosndka** [bogachenko/fuckfuckadblock#458]
### Basic information

**Check the link:** `https://onepagelink.in/VDDmhU`
**Category:** Anti-adblock
**Reported from:** IN

### User environment

**Browser:**  Firefox 118.0.1
**Adblocker:**  ublock origin
**Extensions:**  none
**DNS:**  none

**Comment by bogachenko** [comment]
The `onepagelink.in` website redirects to `gorating.in`
