### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by gosndka** [bogachenko/fuckfuckadblock#460]
### Basic information

**Check the link:** `https://www.youtube.com/watch?v=DgqhB3BBR-s`
**Category:** Anti-adblock
**Reported from:**  IN

### User environment

**Browser:**  Firefox v118.0.2
**Adblocker:**  ubo 1.52.2
**Extensions:**  none
**DNS:**  none

**Comment by bogachenko** [comment]
I used VPN different countries, I can’t reproduce a pop-up message. When using the default settings, there is nothing.

**Comment by ryanolee** [comment]
![image](https://github.com/bogachenko/fuckfuckadblock/assets/17767073/36e1d7e5-684b-4594-847a-e676e27b3a06)
This is what the pop up does look like if that does help.

**Comment by ryanolee** [comment]
^ Repoduced using uOriginBlock on Chrome: `118.0.5993.70 (Official Build) (64-bit) `

**Comment by bogachenko** [comment]
Do not load any images here, please

**Comment by megakarlach** [comment]
You can get that popup below by using any adblockers other than Ublock Origin (or by having an outdated filter).
Ublock Origin has the filter built-in so you may not see this message. The same thing may applies to few other countries such as Russia.
![image](https://github.com/bogachenko/fuckfuckadblock/assets/60382442/9fce7f54-5cd5-4b03-b5de-675cfb723143)

**Comment by gosndka** [comment]
@bogachenko as far I can tell by skimming through ubo similar issues on reddit and github, I guess yt is enforcing this on people who have accounts and using those accounts to block ads on their site. So using your google account may trigger that popup.

**Comment by BrianBlaze** [comment]
I don't know if this helps anyone, but I noticed that to get rid of this message I obviously add the subscription to ublock. And then I cleared out all history and cache then restart browser and now even on chrome my kids do not get the pop up again, for now.

It worked on 3 machines thus far and I haven't had to get my kids to sign out :)
