### ISSUE TITLE
arabic-for-nerds.com

### ISSUE THREAD

**Issue by bot1947** [bogachenko/fuckfuckadblock#462]
### Basic information

**Check the link:** `https://arabic-for-nerds.com/`
**Category:** Popup
**Reported from:** UK

### User environment

**Browser:** Chrome
**Adblocker:** uBlock Origin 1.52.2
**Extensions:** None
**DNS:** None

### Additional message

Thanks.

**Comment by bot1947** [comment]
NB this chrome extension (found it using reddit) can block it https://chrome.google.com/webstore/detail/admiral-sucks/bhkgjcmhgbpmedkghbphnfkjibekjdgp

Thanks

**Comment by Saulildo** [comment]
it can be easily bypassed bro
