### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by dandud100** [bogachenko/fuckfuckadblock#466]
### Basic information

**Check the link:** https://megaup.net/20jr2/test.txt 
**Category:** Breakage
**Reported from:** Germany 

### User environment

**Browser:** Chrome 
**Adblocker:** ublock origin 
**Extensions:** 
**DNS:** 1.1.1.1

**Comment by bogachenko** [comment]
Hello @ryanbr @Yuki2718, please add these advertising domains to your list.

```
||riperfienwa.com^
||nopoloferewer.com^
```
