### ISSUE TITLE
gplinks.co

### ISSUE THREAD

**Issue by swathigrate** [bogachenko/fuckfuckadblock#467]
### Basic information

**Check the link:**  `https://gplinks.co/RgXB4kli/?pid=882042&vid=245642624`
**Category:** Popup
**Reported from:**  India 

### User environment

**Browser:**  kiwi browser Android 
**Adblocker:**  uBblock Origin 
**Extensions:**  fuckfuckadblock
**DNS:**  None

### Additional message

Adblock pop up window appears

**Comment by bogachenko** [comment]
It may not work on Kiwi, use Firefox Mobile, I also ask that if you encounter problems on this site in the future (this site uses fly-by-night domains), please ping here without creating a new issue.
