### ISSUE TITLE
tomshardware.fr

### ISSUE THREAD

**Issue by Karewan** [bogachenko/fuckfuckadblock#468]
### Basic information

**Check the link:** `https://www.tomshardware.fr/`
**Category:** Anti-adblock
**Reported from:** France

### User environment

**Browser:** Chrome
**Adblocker:** uBlock 1.5.3
**Extensions:** -
**DNS:** 1.1.1.1

### Additional message

After 5 seconds, a popup shows up and asks to disable uBlock.

**Comment by Karewan** [comment]
uBlock filters 5/5 (all)
AdGuard – Ads
EasyList
AdGuard URL Tracking Protection
Online Malicious URL Blocklist
AdGuard – Annoyances 6/7 (all except uBlock filters – Cookie Notices)
uBlock filters – Annoyances
fr fr ca ca: AdGuard Français
Fuck Fuckadblock

**Comment by bogachenko** [comment]
The problem is the missing Easyprivacy list.

**Comment by bogachenko** [comment]
The problem is the missing Easyprivacy list.

**please do not upload images here.**
