### ISSUE TITLE
howtogeek.com

### ISSUE THREAD

**Issue by lupohan44** [bogachenko/fuckfuckadblock#471]
### Basic information

**Check the link:** `https://www.howtogeek.com/765940/how-to-enable-dns-over-https-on-windows-11/` 
**Category:** Anti-adblock
**Reported from:** US 

### User environment

**Browser:** Google Chrome 120.0.6099.71 x64
**Adblocker:** Adblock Plus
**Extensions:**  None
**DNS:**  None

**Comment by bogachenko** [comment]
I can't reproduce it. The rule in my filter works correctly and removes this notification:
```
Something went wrong. Please disable your blocker on How-To Geek

It looks like your blocker is attempting to interfere with the intended operation of this site. Support our writers and our copyrighted content by allowing our site to function as we intended. Please disable your blocker and add HowToGeek.com to your allowlist.



Frequently Asked Questions

I'm not using a blocker. Why am I seeing this message?
You're likely seeing this message because an app or extension on your computer is blocking ads. The app or extension may be a "privacy" or "malware" blocker, or a VPN.

I disabled my blocker. Why am I still seeing this message?
It's common to have two or more adblocking extensions running at the same time. See the question above.
```

go to the uBO settings => Support tab => scroll down, there will be a "Troubleshooting" field, send me this field here in the comments.

**Comment by bogachenko** [comment]
You are using Adblock Plus, [it](https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#adblock-and-adblock-plus) is not supported. Filters are only for unlock Origin or Adguard, if you want to use my filter, please remove adblock plus and install one of the following.

**Comment by lupohan44** [comment]
works perfectly after switch to ublock origin
