### ISSUE TITLE
Failed, not a valid filter list on adblock

### ISSUE THREAD

**Issue by williamg209** [bogachenko/fuckfuckadblock#472]
### Basic information

**Check the link:** 
**Category:** Breakage
**Reported from:** uk

### User environment

Chrome
Adblock

**Comment by bogachenko** [comment]
Read the information [about this repository](https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock) again and you will understand why there is an error.

_Namely, this line:_
> In this repository, filters are created for AdGuard and uBlock Origin.
***
I also suggest you take a look at this:
PS: https://github.com/bogachenko/fuckfuckadblock/issues?q=AdBlock+Plus+support
PSS: https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#adblock-and-adblock-plus
