### ISSUE TITLE
reidoplacar.com

### ISSUE THREAD

**Issue by Saulildo** [bogachenko/fuckfuckadblock#473]
**Check the link:** `https://reidoplacar.com/?p=10`
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:** Firefox
**Adblocker:** uBlock
**Extensions:** ClearURL, Decentraleyes
**DNS:** AdGuard

### Additional message
Annoying ass Brazilian website used to shorten links. There are an absurd number of ads, including pornographic ones.

**Comment by bogachenko** [comment]
Well, I removed this notification, but you need to post the full link.
