### ISSUE TITLE
/scripts/ads.js unlocked ?

### ISSUE THREAD

**Issue by nightznero** [bogachenko/fuckfuckadblock#474]
Helloz,

I would like to ask its the correct that ads scripts should be unlocked or ...?
Regards, NIGHTZNERO.

**Comment by bogachenko** [comment]
Yes. That's how it should be. The script you link to allows the byte script 
`https://showup.tv/scripts/ads.js`. On the showup.tv site (as on most sites) it is responsible for displaying notifications about the use of adblock. Its contents are usually like this `var canRunAds = !![];` although the name may change on different sites.

uBO has js redirection, Adguard too, but I don’t really like it.

https://github.com/gorhill/uBlock/blob/master/src/web_accessible_resources/prebid-ads.js
https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/web-accessible-resources/redirects/prebid-ads.js
