### ISSUE TITLE
canyoublockit.com

### ISSUE THREAD

**Issue by JuanPabloPearce** [bogachenko/fuckfuckadblock#481]
### Basic information

**Check the link:** `https://canyoublockit.com/testing/`
**Category:** Anti-adblock
**Reported from:** USA

### User environment

**Browser:** Firefox 123.0 x64 Bit
**Adblocker:** Adguard 7.16.0 (4542)
**Extensions:** Bitwarden, Adguard VPN, Dark Reader
**DNS:** OpenDNS ipv4 and ipv6

### Additional message

**Comment by bogachenko** [comment]
Already blocked in Easylist
