### ISSUE TITLE
tiktokcounter.net

### ISSUE THREAD

**Issue by ecc29** [bogachenko/fuckfuckadblock#482]
### Basic information

**Check the link:** `https://tiktokcounter.net/tech/?url8j=`
**Category:** Anti-adblock
**Reported from:** CA

### User environment

**Browser:** Firefox 115.8.0esr
**Adblocker:** uBlock Origin
**Extensions:** 
**DNS:** 1.1.1.1

### Additional message

The script on this page is also used by other websites to detect adblockers. It seems the code was from `https://ctr.sh`

**Comment by bogachenko** [comment]
Do you mean this text?
```
Wait time updated to 150s! Our website is made possible by displaying online advertisements to our visitors.
Please consider supporting us by disabling your ad blocker.
```

**Comment by ecc29** [comment]
The problem is not the text. The javascript will change the countdown timer from several seconds to 150s when it detect the adblocker. You have to wait more than 10 times longer with the adblocker turned on, and that's only the frist step, you will have to repeat this 3 times (sometimes 5 times).

**Comment by ecc29** [comment]
> Do you mean this text?
> 
> ```
> Wait time updated to 150s! Our website is made possible by displaying online advertisements to our visitors.
> Please consider supporting us by disabling your ad blocker.
> ```
The problem is not the text. The javascript will change the countdown timer from several seconds to 150s when it detect the adblocker. You have to wait more than 10 times longer with the adblocker turned on, and that's only the frist step, you will have to repeat this 3 times (sometimes 5 times).

**Comment by bogachenko** [comment]
What you are talking about directly refers to the text that I published above. The rule that I added for this site, complete with the existing rules from uBO, disables detection. This works for me, what about you?

**Comment by ecc29** [comment]
> What you are talking about directly refers to the text that I published above. The rule that I added for this site, complete with the existing rules from uBO, disables detection. This works for me, what about you?

Sorry for the confusion. The fix works with code on tiktokcounter.net, but there are other similar websites, for example, the fix doesn't work with this one https://sinonimos.de/?url8j=

**Comment by bogachenko** [comment]
>What you are talking about directly refers to the text that I published above. The rule that I added for this site, complete with the existing rules from uBO, disables detection. This works for me, what about you?

I deleted this text because you deleted 2 of your messages. I added a rule for the site as well `sinonimos.de` also. Check and write to me.
Also, please tell me which "Earn Money" website you use, maybe I will find more copies of such links and add it too.

**Comment by prpjzz** [comment]
hello, sorry for mentioned you, but i found this site use `https://ctr.sh`: `leechall.com`

**Comment by ecc29** [comment]
> I added a rule for the site as well `sinonimos.de` also. Check and write to me. Also, please tell me which "Earn Money" website you use (only `https://ctr.sh`?), maybe I will find more copies of such links and add it too.

Thanks, the new fix works with `sinonimos.de`. It was just a download link redirected to ctr.sh. I don't know other "Earn Money" website using this trick. ctr.sh redirect the link to tiktokcounter, in this format: `https://tiktokcounter.net/tech/?url8j=https://ctr.sh/XXXXXX`, so after the delayed count down timer on tiktokcounter, tiktokcounter kicked it back to `https://ctr.sh/XXXXXX`, then ctr.sh kicked me to the next similar website, in this case it was sinonimos.de. It looks like those websites are using similar code to detect the adblockers, just modified each one of them to evade uBO's detection. Maybe they have some parts of the codes in common, so a general rule will deal with all of them?

@prpjzz please feel free to join this discussion. If you know any similar websites using this trick, please post them here.

**Comment by bogachenko** [comment]
> It looks like those websites are using similar code to detect the adblockers, just modified each one of them to evade uBO's detection.

Yes, it is. However, in my experience, I can say that often sites like ctr.sh they are not limited to a couple of domains (but I cannot reproduce more than two yet).

**Comment by ecc29** [comment]
> Yes, it is. However, in my experience, I can say that often sites like ctr.sh they are not limited to a couple of domains (but I cannot reproduce more than two yet).

Interesting, they updated their website, the fix doesn't work anymore. This time they also tried to cover the redirect link to their website. The chain started from `https://psa.btcut.io/gtPr?src=PSA`, then it finally reached `tiktokcounter.net`. It seems `tiktokcounter.net` is providing adblock detecting service to other websites.
