### ISSUE TITLE
asupan.me

### ISSUE THREAD

**Issue by 0xh3LL0** [bogachenko/fuckfuckadblock#483]
### Basic information

**Check the link:** `https://asupan.me/category/bokep-indo/`
**Category:** Anti-adblock
**Reported from:** Indonesia

### User environment

**Browser:** FireFox115
**Adblocker:** uBlock Origin
**Extensions:** 
**DNS:** AdGuard Non-filtering

### Additional message

NSFW site

**Comment by bogachenko** [comment]
Hi @0xh3LL0 , does this site have any mirrors?

**Comment by 0xh3LL0** [comment]
i dont think so
