### ISSUE TITLE
Question/Broken

### ISSUE THREAD

**Issue by WWIA7062** [bogachenko/fuckfuckadblock#485]
Hi I don't use Adblock Plus and I don't want to switch everything over so I wanted to ask something, is there a version available for adblock?

**Comment by WWIA7062** [comment]
if not that's OK but I'm just trying to make sure since these looks good.

also I'm on ChromeOS Beta 123.0.6312.36 just to confirm

**Comment by bogachenko** [comment]
No. Sheets do not work on Adblock Plus and similar extensions, [only uBlock Origin or AdGuard](https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock).

Also READ ME https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#adblock-and-adblock-plus
