### ISSUE TITLE
Not compatible with Abblock Plus

### ISSUE THREAD

**Issue by tansautn** [bogachenko/fuckfuckadblock#489]
### Basic information

I subscibed long time ago, but don't check till today. Here is image from ABP (I tried both manual add raw link & auto subscribe method)
**Category:** Breakage
**Reported from:** Browsing using Singapore Socks (Always) via ProxyFox. Mozilla & localnet excluded. I'm live in Viet Nam

### User environment

**Browser:** Firefox 124.0.2 x64 
**Adblocker:** Adblock Plus - `https://adblockplus.org`
**Extensions:** It's quite a long-long list. So i'll put it bottom this comment.
**DNS:** 1.1.1.1 - cloudflare

### Additional message

list Extension installed & enabled : 
| Name   |   type  |  version | 
|----------|:-------------:|:------:|
 | English United States Dictionary | dictionary | 115.0 | true | @unitedstatesenglishdictionary | 
 | Vietnamese Dictionary | dictionary | 2.2.0.1webext | true | dictionary@vi.mozdev.org | 
 | Adblock Plus - free ad blocker | extension | 3.25.1 | true | {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d} | 
 | Add-ons Search Detection | extension | 2.0.0 | true | addons-search-detection@mozilla.com | 
 | AdSkip | extension | 1.2.7 | true | {b2d1e640-a2a2-4d86-970d-ba06ff92b52a} | 
 | Anti-Adblock Blocker | extension | 0.0.7 | true | {7616a0b7-d0b6-4a0d-ad65-c9b35d96bad4} | 
 | Auto Tab Discard | extension | 0.6.7 | true | {c2c003ee-bd69-42a2-b0e9-6f34222cb046} | 
 | Better Darker Docs | extension | 1.1.1 | true | batterdarkerdocs@threethan.github.io | 
 | Bing | extension | 1.6 | true | bing@search.mozilla.org | 
 | Buster: Captcha Solver for Humans | extension | 2.0.1 | true | {e58d3966-3d76-4cd9-8552-1582fbc800c1} | 
 | CanvasBlocker | extension | 1.9 | true | CanvasBlocker@kkapsner.de | 
 | ClearURLs | extension | 1.26.1 | true | {74145f27-f039-47ce-a470-a662b129930a} | 
 | Copy PlainText | extension | 1.15 | true | copyplaintext@eros.man | 
 | Decentraleyes | extension | 2.0.19 | true | jid1-BoFifL9Vbdl2zQ@jetpack | 
 | Default Bookmark Folder | extension | 4.0.0 | true | default-bookmark-folder@gustiaux.com | 
 | Download All Images | extension | 0.8.1 | true | {32af1358-428a-446d-873e-5f8eb5f2a72e} | 
 | DuckDuckGo | extension | 1.4 | true | ddg@search.mozilla.org | 
 | Enhancer for YouTube™ | extension | 2.0.123 | true | enhancerforyoutube@maximerf.addons.mozilla.org | 
 | Facebook Container | extension | 2.3.11 | true | @contain-facebook | 
 | Firefox Translations | extension | 1.3.4buildid20230720.091143 | true | firefox-translations-addon@mozilla.org | 
 | Flagfox | extension | 6.1.73 | true | {1018e4d6-728f-4b20-ad56-37578a4de76b} | 
 | Foxy Gestures | extension | 1.2.12 | true | {e839c3f9-298e-4cd0-99e0-464431cb7c34} | 
 | FoxyProxy Standard | extension | 7.5.1 | true | foxyproxy@eric.h.jung | 
 | FoxyTab | extension | 2.31 | true | foxytab@eros.man | 
 | Google | extension | 1.4 | true | google@search.mozilla.org | 
 | HackBar Quantum | extension | 1.5 | true | {2e084b0a-695c-4c75-adb0-08e5ed15aa7c} | 
 | iCloud Bookmarks | extension | 2.3.40 | true | firefoxdav@icloud.com | 
 | IDM Integration Module | extension | 6.42.3 | true | mozilla_cc3@internetdownloadmanager.com | 
 | Image Search Options | extension | 3.0.12 | true | {4a313247-8330-4a81-948e-b79936516f78} | 
 | Imagus | extension | 0.9.8.74 | true | {00000f2a-7cde-4f20-83ed-434fcb420d71} | 
 | ImTranslator: Translator, Dictionary, TTS | extension | 16.76 | true | {9AA46F4F-4DC7-4c06-97AF-5035170634FE} | 
 | JSON Lite | extension | 21.3.0 | true | {16a49f65-1369-4839-a5ef-db2581e08b16} | 
 | Link Gopher | extension | 2.6.2 | true | linkgopher@oooninja.com | 
 | Media Panel | extension | 2.6 | true | {68d048f4-9449-4c97-8425-6dac7f743b14} | 
 | Modify Header Value (HTTP Headers) | extension | 0.1.8 | true | jid0-oEwF5ZcskGhjFv4Kk4lYc@jetpack | 
 | NoScript | extension | 11.4.29 | true | {73a6fe31-595d-460b-a920-fcc0f8843232} | 
 | Notifier for Gmail™ | extension | 1.1.6 | true | jid0-GjwrPchS3Ugt7xydvqVK4DQk8Ls@jetpack | 
 | OCR - Image Reader | extension | 0.4.0 | true | {e4c6eef1-8b3b-4daa-8757-707702e7528d} | 
 | Open Image In New Tab | extension | 1.1.0 | true | open-image-in-new-tab@mint.as | 
 | Popup Blocker (strict) | extension | 0.7.0 | true | {de22fd49-c9ab-4359-b722-b3febdc3a0b0} | 
 | Pretty XML | extension | 0.1.0 | true | {dd6008c8-a74c-47ab-8df5-04412a046725} | 
 | React Context DevTool | extension | 3.2 | true | {512fb108-d4a6-4652-a6d3-bc8846258186} | 
 | React Developer Tools | extension | 5.0.2 | true | @react-devtools | 
 | Reverse Image Search | extension | 0.2.3 | true | jid0-iiiWfb12bgHj8iKloOou74fb6jh@jetpack | 
 | Shadertoy unofficial plugin. | extension | 0.13.243 | true | {cab6fe0d-6896-4cb6-a40c-1613dd3ed8f9} | 
 | Stylebot | extension | 3.1.3 | true | {52bda3fd-dc48-4b3d-a7b9-58af57879f1e} | 
 | Tab Stash | extension | 3.0 | true | tab-stash@condordes.net | 
 | Tampermonkey | extension | 5.1.0 | true | firefox@tampermonkey.net | 
 | Text Link | extension | 6.1.9 | true | {54BB9F3F-07E5-486c-9B39-C7398B99391C} | 
 | Universal Bypass | extension | 13.15.2.1 | true | {529b261b-df0b-4e3b-bf42-07b462da0ee8} | 
 | User-Agent Switcher and Manager | extension | 0.5.0 | true | {a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7} | 
 | Voz Next | extension | 1.3.2 | true | voznext@nmtrung.com | 
 | Wappalyzer - Technology profiler | extension | 6.10.68 | true | wappalyzer@crunchlabz.com | 
 | Web Archives | extension | 5.0.0 | true | {d07ccf11-c0cd-4938-a265-2a4d6ad01189} | 
 | Web Design Pirate | extension | 1.6 | true | {02e80daa-0940-4e05-82ee-bb920a9517ad} | 
 | Web Developer | extension | 2.0.5 | true | {c45c406e-ab73-11d8-be73-000a95be3b12} | 
 | Web Developer Form Filler | extension | 1.3.0 | true | {d354848e-5fd6-41c3-84d3-76e920aac579} | 
 | webhint | extension | 2.4.15 | true | {e748cb59-4901-4bea-b74a-1d8dab98e3c7} | 
 | Wikipedia (en) | extension | 1.3 | true | wikipedia@search.mozilla.org | 
 | Zoom Page WE | extension | 19.13 | true | zoompage-we@DW-dev | 
 | Language: English (US) | locale | 124.0.20240401.114208 | true | langpack-en-US@firefox.mozilla.org | 
 | Language: Tiếng Việt (Vietnamese) | locale | 124.0.20240401.114208 | true | langpack-vi@firefox.mozilla.org | 
 | Dark space - The best dynamic theme | theme | 1.1.2 | true | {22b0eca1-8c02-4c0d-a5d7-6604ddd9836e} |

**Comment by bogachenko** [comment]
Sheets do not work on Adblock Plus and similar extensions, [only uBlock Origin or AdGuard](https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock).

Also READ ME https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#adblock-and-adblock-plus
