### ISSUE TITLE
gplinks.co

### ISSUE THREAD

**Issue by NHM2005** [bogachenko/fuckfuckadblock#493]
### Basic information

**Check the link:** `https://gplinks.co/nr2is3nm/?pid=887746&vid=372995239`
**Category:** Anti-adblock
**Reported from:** Bangladesh

### User environment

**Browser:** Kiwi Browser Version 124.0.6327.4
**Adblocker:** uBlock Origin 1.57.0
**Extensions:** Youtube BG; Browser Boost - Extra Tools; History AutoDelete; uBlock Origin; Image Downloader; Cookie AutoDelete; Video Downloader Plus; Picture-in-Picture Extension; Youtube audio_only; WebGPU Fingerprint Defender
**DNS:** No use

### Additional message

in this domain firstly, tell me wait for 15s. After waiting, "continue" button appears below of page. After tapping continue,then it notify about ads blocker

**Comment by bogachenko** [comment]
`gplinks.*##+js(no-fetch-if.js, googlesyndication)`
`@@||gplinks.in/track/$xhr`
does this work for you?

**Comment by NHM2005** [comment]
> `gplinks.*##+js(no-fetch-if.js, googlesyndication)` `@@||gplinks.in/track/$xhr` does this work for you?

Sorry, I'm a noob user.
Can you tell me how i set up that codes for working

**Comment by bogachenko** [comment]
go to the settings in uBO and paste these 2 rules into the fields in the "My Filters" tab, please

**Comment by NHM2005** [comment]
I'm not seeing that any more.
Can't detect as ad blocker

**Comment by bogachenko** [comment]
Great (although for some reason it still triggers for me). Remove these 2 rules from the My Filters tab and update my sheet.
