### ISSUE TITLE
mlwbd.st 

### ISSUE THREAD

**Issue by NHM2005** [bogachenko/fuckfuckadblock#494]
### Basic information

**Check the link:** `https://mlwbd.st/movie/shaitaan-2024/`
**Category:** Popup
**Reported from:** Bangladesh

### User environment

**Browser:** Cromite Version 124.0.6367.202
**Adblocker:** Default add blocker of browser (but added all custom filter of ublock at browser settings  that used in ublock by default.
**Extensions:** No extension 

### Additional message

For making size small, video was edited. 
(By default, browser popup feature remain disabled. I enabled for some feature. And added all filter list for blocking unnecessary pop-up. But is won't works. Only ads were blocked )

**Comment by bogachenko** [comment]
> Adblocker: Default add blocker of browser (but added all custom filter of ublock at browser settings that used in ublock by default.

https://github.com/bogachenko/fuckfuckadblock/wiki/About-Fuck-Fuckadblock

In the speech about the goals of the project, there is a direction about the original uBO and AdGuard extensions, correct operation for other extensions, even those made on their basis, such as AdNauseam (which is made on the basis of uBO) or, in your case, the built-in ad blocker from the Cromite browser, is not guaranteed.

**Comment by NHM2005** [comment]
Ok

**Comment by bogachenko** [comment]
@NHM2005 Even despite the blocking method, pop-up advertising was detected, nevertheless use the official uBO or AdGuard extensions
