### ISSUE TITLE
angxlzz.com

### ISSUE THREAD

**Issue by Saulildo** [bogachenko/fuckfuckadblock#499]
### Basic information

**Check the link:** `https://angxlzz.com/` 
**Category:** Anti-adblock
**Reported from:** Brazil

### User environment

**Browser:**  Kiwi Browser
**Adblocker:**  uBlock 1.58.0
**Extensions:**  TamperMonkey
**DNS:** AdGuard

**Comment by bogachenko** [comment]
>DNS: AdGuard

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#blocking-by-dns-with-adguard-for-windowsmacandroid-and-ublock-origin

> Extensions: TamperMonkey

https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions

>Browser: Kiwi Browser

I didn't check it for mobile, but as far as I remember, this browser has support for Google extensions, so I think it will work for this browser too, although sometimes there are exceptions for browsers forks.
