### ISSUE TITLE
notebookcheck.net

### ISSUE THREAD

**Issue by Tobbe** [bogachenko/fuckfuckadblock#5]
### Basic information

**Check the link:** `https://www.notebookcheck.net`
**Category:** anti-adblock
**Reported from:** Sweden
**Filter lists:**
[x] Auto-update filter lists 
[x] Parse and enforce cosmetic filters
[ ] Ignore generic cosmetic filters

My filters ​​​​​3 used out of 3​​​​

Built-in (5/7)
uBlock filters ​​​​​17,445 used out of 17,467​​​​
uBlock filters – Badware risks​ ​​​​274 used out of 275​​​​
uBlock filters – Privacy​​​​​ 161 used out of 162​​​​
uBlock filters – Resource abuse ​​​​​113 used out of 113​​​​
uBlock filters – Unbreak​​​​​ 967 used out of 969​​​​

Ads (1/4)
EasyList ​​​​​90,816 used out of 91,096​​​​

Privacy (1/3)
EasyPrivacy ​​​​​17,136 used out of 17,210​​​​

Malware domains (2/4)
Malware Domain List ​​​​​1,090 used out of 1,105​​​​
Malware domains​​​​​ 26,896 used out of 26,896​​​​

Annoyances (0/6)

Multipurpose (1/4)
Peter Lowe’s Ad and tracking server list ​​​​​2,949 used out of 2,950​​​​

Regions, languages (0/36)

Custom (2/2)
AakList (Anti-Adblock Killer) ​​​​​2,118 used out of 2,178​​​​
Fuck Fuckadblock​​​​​ 2,475 used out of 6,577​​​​

### User environment
**Browser:** Chrome
**Extension:** uBlock Origin 1.19.6

### Additional message
Please remove both the anti ad-block message, and the extra ads they show because of the ad-block

**Comment by bogachenko** [comment]
Update the filter and check again. If the problem is solved, close the question;)

**Comment by Tobbe** [comment]
It doesn't seem to work 😞 

![image](https://user-images.githubusercontent.com/30793/59674556-d0d85700-91c3-11e9-8dcc-e38652d84a31.png)

**Comment by bogachenko** [comment]
Try to clear the cache and cookies.

**Comment by bogachenko** [comment]
If clearing cookies and cache did not help (but it should have helped), try this (and see if it breaks something) 
`notebookcheck.net##+js(abort-current-inline-script.js, document.createElement, iframe)`

**Comment by Tobbe** [comment]
Clearing cache and cookies did not help.

Both your rules work, and none of them seems to break anything (just doing a quick test)

**Comment by bogachenko** [comment]
>Clearing cache and cookies did not help.

Strange.

> Both your rules work, and none of them seems to break anything (just doing a quick test)

Okay. I will add this new rule. They should not break anything by idea, but if suddenly - write me ;)
