### ISSUE TITLE
unknowncheats.me

### ISSUE THREAD

**Issue by gir489returns** [bogachenko/fuckfuckadblock#501]
### Basic information

**Check the link:** `https://www.unknowncheats.me/forum/helldivers-2-a/645905-server-updated.html`
**Category:** Anti-adblock
**Reported from:** USA

### User environment

**Browser:** Edge Version 126.0.2592.102 (Official build) (64-bit)
**Adblocker:** AdGuard Version 4.3.53
**Extensions:** Bitwarden, FoxyProxy, SponsorBlock for YouTube
**DNS:** Cloudflare Anti-Malware DoH.

### Additional message

At the bottom of the page, you will see this:

```
Enjoying our free services? We're committed to keeping your experience free and without restrictions, but please consider supporting us by disabling your adblocker or whitelisting our site.
```

**Comment by bogachenko** [comment]
Hello, please don't post images here, it's unnecessary. If you ever find a problematic site again, describe the problem in words, thank you. Have a nice day.
