### ISSUE TITLE
zeemoontv-24.blogspot.com

### ISSUE THREAD

**Issue by rigaz29** [bogachenko/fuckfuckadblock#506]
### Basic information

**Check the link:**  `https://zeemoontv-24.blogspot.com/`
**Category:** Anti-adblock
**Reported from:**  Indonesia

### User environment

**Browser:**  Latest Chrome
**Adblocker:**  Latest Ublock Origin Lite

**Comment by bogachenko** [comment]
The blog has been deleted. For your information, the new uBO v3 manifest is not supported for this sheet.
