### ISSUE TITLE
faucetcrypto.com

### ISSUE THREAD

**Issue by arbarbosa1979** [bogachenko/fuckfuckadblock#51]
### Basic information

**Check the link/s:** `https://www.faucetcrypto.com`
**Category:** anti-adblock
**Reported from:** USA

### User environment
**Browser:** Chrome 81.0.4044.129 and Firefox 76.0
**Extension or program:** Nano Adblocker v1.0.0.142
**Filter lists:**  Default, bogachenko's Filter List​ and Fuck Fuckadblock

**Comment by bogachenko** [comment]
You mean the site faucetcrypto.com itself or third-party short-sites on faucetcrypto.com?

**Comment by arbarbosa1979** [comment]
> ~You mean the site faucetcrypto.com itself or third-party short-sites on faucetcrypto.com?~
> I think third-party sites. I removed pop-ups with ads and an anti-block from some third-party sites, if you see something else let me know.

```
<!-- <script src="js/app.js"></script> -->
 <script src="https://www.faucetcrypto.com/js/newv2/app.js?id=718acfc0c1c268e47469"></script>
```

**Comment by bogachenko** [comment]
AND? The script that you gave loads other scripts, one of which is responsible for the antiadblock - `fuckadblock.min.js` from the website `cdnjs.cloudflare.com`. In my sheet, this script is already allowed by the rule `@@||cdnjs.cloudflare.com/*/fuckadblock.$script,third-party` that allows you to bypass the anti-adblock and not receive annoying messages in the future.
Check if the above script is allowed in your browser using the logger uBlock.

**Comment by arbarbosa1979** [comment]
uBlock Origin v1.26.2 + standard filters, Fuck Fuckadblock and bogachenko's Filter List.

No other script or adblock installed and still this message still appears:

[Error printscreen](https://imgur.com/xQwcGxu)

Before it was working, but it stopped working a few days ago.

Specifically in this url: `https://www.faucetcrypto.com/dash/generate-link/short-fc`
I don't mind turning off adblock on this site, as it has few ads, but another less friendly site may try to use the same solution.

**Comment by bogachenko** [comment]
I asked you to check your rule-exception log, to make it look like mine 
https://user-images.githubusercontent.com/8535285/81848468-e525ff00-95a0-11ea-958a-3a0ddec437f4.png
you should have the same.

I checked on 2 computers and my smartphone, I can reproduce this problem if block it `https://cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js` but nothing more
Well no matter, check this rule

`faucetcrypto.com##+js(abort-on-property-read.js, FuckAdBlock)`

**Comment by arbarbosa1979** [comment]
Yes, here it was the same in your image, but it wasn't working, but after restarting the computer 3x and resetting the addon settings, after all that, it finally started working, but I couldn't identify exactly what the problem was.

Thank you very much for your patience and time spent solving this problem, have a good day.
