### ISSUE TITLE
tw-calc.net

### ISSUE THREAD

**Issue by tim21** [bogachenko/fuckfuckadblock#52]
### Basic information

**Check the link/s:** `https://tw-calc.net/`
**Category:** anti-adblock
**Reported from:** Greece

### User environment
**Browser:** Firefox 76
**Extension or program:** uBlock

### Additional message
Any other page other than homepage displays a blocking message, making site unusable.

**Comment by bogachenko** [comment]
Update the sheet. U can also add this 
`tw-calc.net##.horizontal_large.container, .vertical.container, .cookie` 
to remove empty (from ads) boxes and the top banner notifying you about the use of cookies.
Have fun.

**Comment by tim21** [comment]
thanks for the very fast response!
while this fixed the adblock message, it also disabled item previews on the site and every item now gives this error on hover : http://prntscr.com/sdly28 . 
is this too fixable? thanks in advance!
