### ISSUE TITLE
.adsbygoogle

### ISSUE THREAD

**Issue by haze2422** [bogachenko/fuckfuckadblock#55]
Vivaldi 3.1.1906.3 ( Chrome/81.0.4044.132 ), Nano Adblocker 1.0.0.142 ( uBO 1.26.0 )

Внезапно обнаружил на https://www.pixiv.net/bookmark.php пустые плейсхолдеры, полез в логгер, а там *#@#.adsbygoogle ( Fuck Fuckadblock )

**Comment by bogachenko** [comment]
У меня обрусифицированный код там, проверить не могу, как и удалить это правило, ведь оно помогает обойти легкие (написанные на коленке) антиблокировщики. Да, оно вызывает иногда не ту реакцию, как хотелось бы, об этом уже писали https://github.com/bogachenko/fuckfuckadblock/issues/11, но легче добавить общее правило, а уже потом писать исключения под него.

Добавь в "Мои фильтры" `pixiv.net##.adsbygoogle`.

**Comment by bogachenko** [comment]
@okiehsch This https://github.com/uBlockOrigin/uAssets/commit/516db934010ab4600dd8c78c5cfd428bcd3904ad blocks Google captcha when you create an account

**Comment by okiehsch** [comment]
Thx.
