### ISSUE TITLE
wetransfer.com

### ISSUE THREAD

**Issue by yokoffing** [bogachenko/fuckfuckadblock#56]
### Basic information

**Check the link/s:** `https://wetransfer.com`
**Category:** anti-adblock
**Reported from:** USA

### User environment
**Browser**: On any
**Extension or program**: uBlock Origin

### Additional message
Filter needed: `||backgrounds.wetransfer.net/*/adblocker-whitelist$3p,domain=wetransfer.com`

**Comment by llacb47** [comment]
you forgot `important` 😛
