### ISSUE TITLE
anti-adblock https://vidstream.*

### ISSUE THREAD

**Issue by zouzou05** [bogachenko/fuckfuckadblock#59]
### Basic information

  
**Site:** https://vidstream.*
**Screenshot:** https://prnt.sc/stey7o

**Check the link/s:**  https://vidstream.kim/f/V8grUDia8E/?vclid=4a36092cc67944a484fb1e822b18c4ef678aad4df0b3f986515b7128zlllsxWdlslElsRcSfzRPMMsMfpaqlSKcRnklsEslsCGMDslElsPbOcREMpMRxEBKtcBZWOlsEslsCMcGlslElsOqOONZsOhOzsEslsWQUlslElsMOcSbzMqWQRGxlsEslsxMcGlslElskOWusOWuekQGMsMhzOsOOEaTxOlabbOanEMsMsiZlslh

**or ths link:** https://vidstream.kim/f/KePz7bt83P/?vclid=1a74c1239a9d60b5803f4db4efbe6dbe155086883dd51032a8f63eadzlllsxMcGlslElskOWusOWuekQGMsMhzOsOOEaTxOlabbOanEMsMsiZlsEslsCMcGlslElsOqOONZsOhOzsEslsWQUlslElsMOcSbzMqWQRGxlsEslsCGMDslElsPbOcREMpMRxEBKtcBZWOlsEslsxWdlslElsRcSfzRPMMsMfpaqlSKcRnklslh

**Category:** anti-adblock

### User environment
**Browser:** chrome
**Extension or program:** uBo 1.27.10

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock/wiki/Unsupported-sites
