### ISSUE TITLE
Error Add FIlter AdGuard Extension

### ISSUE THREAD

**Issue by Gazouu** [bogachenko/fuckfuckadblock#6]
![image](https://user-images.githubusercontent.com/29520490/59756018-3f331d00-9289-11e9-9578-eab3cf2365a8.png)
![image](https://user-images.githubusercontent.com/29520490/59756091-5d008200-9289-11e9-9892-a5b03ed4f2fa.png)
![image](https://user-images.githubusercontent.com/29520490/59756135-70abe880-9289-11e9-96be-3a0351c5c44c.png)

**Comment by bogachenko** [comment]
https://github.com/bogachenko/fuckfuckadblock#raw
