### ISSUE TITLE
Manga-TR.com

### ISSUE THREAD

**Issue by Tmp341** [bogachenko/fuckfuckadblock#61]
### Basic information

**Check the link/s:** [Manga-TR](https://manga-tr.com/index.html)
**Category:** Anti-adblock
**Reported from:** Turkey

### User environment
**Browser:** Firefox 77.0.1 x64
**Extension or program:** uBlockOrigin 1.27.10

### Additional message 
Website was working until today. I don't know what they added, website loads etc but i can't click on the links. It is like i'm clicking on a glass. When i disable uBlockOrigin for the site, i can click on them. I couldn't find any anti-adblock on the site, but it is most likely an ad script prevents my uBlockOrigin from working. I don't know which script causes it. I don't like whitelisting anysite.

### Scripts used:

* Built-in uBlockOrigin filters.
* Adguard Base, Easylist
* Easy Privacy
* Dan Pollock’s hosts file, MVPS HOSTS, Peter Lowe’s Ad and tracking server list
* Adguard Turkish
* [uBlockProtectorList](https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt)
[AntiAdblockKiller](https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt)
[WarningRemoval](https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/ThirdParty/WarningRemoval.txt)
[FuckFuckAdblock](https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt)
[FanboysRegionalTR](https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/firefox-regional/fanboy-adblocklist-tky.txt)

**Comment by llacb47** [comment]
Reek AAK is outdated.

**Comment by Tmp341** [comment]
@llacb47 I know it is.
