### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by WC12366** [bogachenko/fuckfuckadblock#63]
### Basic information

**Check the link/s:** [https://blockadblock.com/](https://blockadblock.com/)
**Category:** Anti-adblock
**Reported from:** China

### User environment
**Browser:** Chrome
**Extension or program:** Adblock Plus

**Comment by bogachenko** [comment]
The syntax of this filter list supports only 2 extensions - uBlock Origin and Adguard, [this is stated in README.md](https://github.com/bogachenko/fuckfuckadblock/blob/master/.github/README.md).
You can also read https://github.com/bogachenko/fuckfuckadblock/wiki/Adblock-Plus-Support
