### ISSUE TITLE
digitaltrends.com

### ISSUE THREAD

**Issue by gir489** [bogachenko/fuckfuckadblock#64]
### Basic information

**Check the link/s:** `https://www.digitaltrends.com/gaming/evo-2020-canceled-co-founder-allegations/`
**Category:** Anti-adblock
**Reported from:** USA

### User environment
**Browser:** Chrome
**Extension or program:** AdGuard

**Comment by gir489** [comment]
![image](https://user-images.githubusercontent.com/7742541/86944787-3c1a0180-c116-11ea-80c2-fffa36a9b481.png)

**Comment by llacb47** [comment]
Add `||hocgeese.com^`
