### ISSUE TITLE
rgj.com

### ISSUE THREAD

**Issue by gir489** [bogachenko/fuckfuckadblock#68]
### Basic information

**Check the link/s:** `https://www.rgj.com/story/news/2020/07/28/douglas-county-sheriff-library-board-dont-call-911-black-lives-matter/5530078002/`
**Category:** Anti-adblock
**Reported from:** USA

### User environment
**Browser:** Chrome
**Extension or program:** AdGuard

**Comment by bogachenko** [comment]
Can't reproduce the problem, give me a list of all your filters and steps to reproduce (maybe a screenshot too).

**Comment by gir489** [comment]
I'm only using fuckfuckadblock as a custom filter rule set and the AdGuard AdBlocker extension for Chrome.

![image](https://user-images.githubusercontent.com/7742541/88942108-d07c0d80-d257-11ea-9abc-11cb3679a3c1.png)

**Comment by llacb47** [comment]
Try uBlock Origin

**Comment by llacb47** [comment]
🙄

**Comment by bogachenko** [comment]
@llacb47 Surprised that I deleted your comment? I've been meaning to ask you for a long time, do you even get paid to campaign for uBO? You propagandize not only in my repo, but also in other places, and I do not like it very much.

**Comment by llacb47** [comment]
I wish, I could always use some extra money. Will you pay me to promote adguard instead?

**Comment by bogachenko** [comment]
@llacb47 I will not, you should talk to Andrey Meshkov. I'm sure he'll give you a job.
