### ISSUE TITLE
clubpenguinhq.net

### ISSUE THREAD

**Issue by jenabaivab** [bogachenko/fuckfuckadblock#69]
### Basic information

**Check the link/s:** `https://clubpenguinhq.net/`
**Category:** Anti-Adblock
**Reported from:** India

### User environment
**Browser:** Edge Chromium
**Extension or program:** Adguard for Windows

### Additional message
Read about this website from a user on Reddit who used Opera GX and still couldn't access it with adblocker.

**Comment by KSPortalcraftmods** [comment]
Hey I am the person from reddit thanks for posting it here.

**Comment by bogachenko** [comment]
I could not find your post on reddit. I made a blind fix. Check it should work, if not, throw your link to the post here.


PS: Disable third-party ad blocking extensions and container extensions for custom scripts, as well as DISABLE Opera's ad blocker.
