### ISSUE TITLE
fcdot.lc

### ISSUE THREAD

**Issue by JonasNo** [bogachenko/fuckfuckadblock#74]
### Basic information

**Check the link/s:** `https://fcdot.lc/2020/07/financial-technology-transforms-to-invest-in-the-stock-market/?a=c212aWxTTko=`
**Category:** Breakage 
**Reported from:** Sweden

### User environment
**Browser:** Chrome
**Extension or program:** uBlock Origin

### Additional message
The filter list is breaking the countdown, it doesn't start counting. So I'm guessing it's detected.

**Comment by bogachenko** [comment]
It doesn't work for me even when the blocker is disabled.

**Comment by bogachenko** [comment]
For the future, the site depends on cookies, so in the Additional message section, publish the site **from** which you went **to** the one that you want to add to the list.
