### ISSUE TITLE
dropgalaxy.in

### ISSUE THREAD

**Issue by sanGtH** [bogachenko/fuckfuckadblock#79]
### Basic information
**Check the link/s:** `https://dropgalaxy.in/utxwy8ayuxh0`
**Category:** breakage
**Reported from:** India

### User environment
**Browser:** Chrome
**Extension or program:**  uBlock Origin

### Additional message

The timer of 15 secs does not start.

**Comment by bogachenko** [comment]
@sanGtH I want to ask you about something, on October 28, 2020 (not fixed yet) if you add this rules

`||dropgalaxy.*/js/countd.js?$important,script` 
`dropgalaxy.*###countdown`

to "My filters" you **will break the cooldown** with 15 seconds (**and** at the same time **break the anti-block**), which you talked about, but if you do not pay attention to this, go through captcha from Google (but wait 15 seconds mentally), you **can still** download the file/s if you click on the blue "Create Download Link" button, right?

**Comment by sanGtH** [comment]
Thanks bro, it just worked so ncie! Now even that timer disappered :dancing_men:

**Comment by blazesprings** [comment]
Again the anti adblock message is appearing..
![image](https://user-images.githubusercontent.com/80951522/112081234-5400bb00-8ba9-11eb-99e3-100163f1da17.png)
