### ISSUE TITLE
allcaster.pl

### ISSUE THREAD

**Issue by FadeMind** [bogachenko/fuckfuckadblock#8]
**Site Sample** | 
----------------|
https://allcaster.pl/serial-online/homeland/S03E09

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1903 x64
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.1.2817 RELEASE** 
Stealth Mode:					       | **enabled**

|**Stealth Mode Setup**
|:--------------------------
|Hide your search queries
|Send Do-Not-Track header
|Remove X-Client-Data header from HTTP requests
|Strip tracking parameters from URLs
|Self-destructing third-party cookies
|Block WebRTC/Location API/Java
|Disable cache for 3rd-party requests
| **=== FILTERS ENABLED ===**
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| Fuck Fuckadblock
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| Fanboy's Cookiemonster List
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

### Issue:

BLANK POPUP window. 

<details><summary><b>Screenshot:</b></summary>

![scr-1562679113-001](https://user-images.githubusercontent.com/9846948/60892062-c22f0e00-a25e-11e9-9314-89fd46bd3358.png)

![scr-1562679160-001](https://user-images.githubusercontent.com/9846948/60892080-cce9a300-a25e-11e9-9417-4fff848563d0.png)

</details><br/>

@bogachenko

**Comment by bogachenko** [comment]
My rules consist mostly of scriptlets. The Adguard program does not yet support them (read this https://github.com/bogachenko/fuckfuckadblock#adguard), so I fixed the pop-up window for the Adguard extension. To remove this window in the program, try this: `allcaster.pl#%#AG_abortOnPropertyWrite('_pop');`
