### ISSUE TITLE
Kickassanime.rs

### ISSUE THREAD

**Issue by gbisheraz581m** [bogachenko/fuckfuckadblock#81]
### Basic information

**Check the link/s:** https://www1.kickassanime.rs/
**Category:**  Anti-adblock
**Reported from:** India

### User environment
**Browser:** Mozilla Firefox 82.04
**Extension or program:** ublock origin

### Additional message
The mentioned website displays a popup to disable adblock please fix this

**Comment by gbisheraz581m** [comment]
They updated their anti adblock again, could you please help? @bogachenko

**Comment by bogachenko** [comment]
You should be thinking about changing the site for watching anime. They seem to be looking at the edits in the filters, for the last day they have already changed the script 2 times.
