### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by Liz-chan** [bogachenko/fuckfuckadblock#82]
### Basic information

**Check the link/s:** `https://www.newyorker.com/magazine/2020/11/09/how-the-coronavirus-hacks-the-immune-system`
**Category:** Anti-adblock
**Reported from:** United States

### User environment
**Browser:** Chrome
**Extension or program:** uBlock Origin

**Comment by Liz-chan** [comment]
It seems the message doesn't pop up anymore, but the article still gets snipped so you can only read the beginning.

**Comment by bogachenko** [comment]
@Liz-chan test `newyorker.com##+js(aopr, HTMLIFrameElement)`
