### ISSUE TITLE
full-download.com

### ISSUE THREAD

**Issue by antiadblocks** [bogachenko/fuckfuckadblock#83]
### Basic information

**Check the link/s:** `https://full-download.com`
**Category:** 
**Reported from:** 

### User environment
**Browser:**
**Extension or program:** 

### Additional message

This site can’t be reached subscribe.adblockplus.org’s server IP address could not be found.

**Comment by bogachenko** [comment]
For heaven's sake, don't remove the markup the next time you post your report.

Regarding the `subscribe.adblockplus.org` site, everything works fine for me, the problem is on your side.
