### ISSUE TITLE
uptostream.com

### ISSUE THREAD

**Issue by Furax-31** [bogachenko/fuckfuckadblock#84]
### Basic information

**Check the link/s:**  ```https://www.tirexo.pro/```
**Category:**  Anti-adblock
**Reported from:**  France

### User environment
**Browser:** Brave Nightly 1.18.46
**Extension or program:** Brave Shield

### Additional message

There is an anti-adblock message when you want to watch a stream, example : https://www.tirexo.pro/streaming-5522996.html

**Comment by bogachenko** [comment]
If you mean video frame, then it's not `tirexo.pro`, it's `uptostream.com` -> `https://uptostream.com/iframe/mzkolr83mora`

And it's unlocked from me, checked on opera and firefox

**Comment by Furax-31** [comment]
Screenshot

![3](https://user-images.githubusercontent.com/61207108/98804474-8853b600-2416-11eb-818b-90c314a77696.png)

**Comment by Furax-31** [comment]
On Firefox the video works, but on Brave I have this message:
![3](https://user-images.githubusercontent.com/61207108/98804700-c650da00-2416-11eb-95bb-42df11ba6aa7.png)

**Comment by bogachenko** [comment]
Yes he. I don't use the Brave browser, what is Brave Shied?

I suspect he is the problem. My list works ONLY with AdGuard and uBlock Orgin (and their forks, for example AdNauseam), is Brave Shied a separate program? If yes, and it is not based on one of these 2 extensions, then it simply will not work there.

**Comment by Furax-31** [comment]
Brave Shield is the browser's built-in blocker, effectively only AdblockPlus syntax works. I'll find another alternative, thanks anyway;)

**Comment by bogachenko** [comment]
>effectively only AdblockPlus syntax works

https://github.com/bogachenko/fuckfuckadblock/wiki/Support-policy#unsupported-and-semi-supported
