### ISSUE TITLE
tomshardware.com

### ISSUE THREAD

**Issue by FuccDucc** [bogachenko/fuckfuckadblock#85]
### Basic information

**Check the link/s:** `https://www.tomshardware.com/`
**Category:** Anti-AdBlock

### User environment
**Browser:** Google Chrome
**Extension or program:** uBlock Origin

### Additional message
If you go to any page on tomshardware.com with uBlock Origin and your filter list enabled, you'll not be able to load the page as it will redirect you to this within 3 seconds:

This blocker page, where it redirects you to, is at `https://www.tomshardware.com/cc.html` - I don't know which Anti-AdBlock product they use, but not a single adblocker currently knows how to stop it (i tried many).

But that anti-adblocker, even though we dont know which one, was discussed before at [https://www.reddit.com/r/Adblock/comments/hb6sy3/adblocker_interference_detected/](https://www.reddit.com/r/Adblock/comments/hb6sy3/adblocker_interference_detected/) so multiple popular sites use it. The website that reddit page is about though, is no longer using it, or is using an outdated version of it, that common adblockers can already stop, because i can visit there. But i cannot visit Tomshardware.

```
AD BLOCKER INTERFERENCE DETECTED

Thank you for visiting this site. Unfortunately we have detected that you might be running custom adblocking scripts or installations that might interfere with the running of the site.

We don't mind you running adblocker, but could you please either disable these scripts or alternatively whitelist the site, in order to continue. Thanks for your support!
```

Maybe you can identify the anti-adblocker and stop those scripts on all sites? Including Tomshardware, so i can browse it ad-free.

**Comment by FuccDucc** [comment]
Update: there are more occurences on the web for whatever this is: [https://www.google.com/search?q=%22Adblocker+Interference+Detected%22](https://www.google.com/search?q=%22Adblocker+Interference+Detected%22)

**Comment by llacb47** [comment]
Test
`*-gb.js|$script,1p,domain=space.com|laptopmag.com|techradar.com|bikeperfect.com|tomshardware.com|whathifi.com|musicradar.com,redirect=noopjs`

**Comment by FuccDucc** [comment]
> Test this filter:
> `*-gb.js|$script,1p,domain=space.com|laptopmag.com|techradar.com|bikeperfect.com|tomshardware.com|whathifi.com|musicradar.com,redirect=noopjs`

It works! Thanks.

But now, can @bogachenko include this in his filter list? You @llacb47 can make a PR for that maybe?

Also, isn't there a way to detect this particular anti-adblocker and strip it from any sites that use it?
