### ISSUE TITLE
dropgalaxy.in

### ISSUE THREAD

**Issue by sanGtH** [bogachenko/fuckfuckadblock#86]
### Basic information

Check the link/s: `https://dropgalaxy.in/vsizgedhy3ej`
Category: Breakage
Reported from: India

### User environment
Browser: Chrome
Extension or program: uBlock Origin

### Additional message
It is throwing error when timer is skipped.

**Comment by bogachenko** [comment]
Duplicate of #79

**Comment by blazesprings** [comment]
Again the anti adblock message is appearing..
![image](https://user-images.githubusercontent.com/80951522/112081124-2b78c100-8ba9-11eb-82f2-0fa969b7d7b7.png)
