### ISSUE TITLE
toontownrewritten.com

### ISSUE THREAD

**Issue by piorrro33** [bogachenko/fuckfuckadblock#89]
### Basic information

**Check the link:** https://www.toontownrewritten.com/ 
**Category:** Breakage 
**Reported from:** France

### User environment

**Browser:** Firefox
**Extension or program:** uBlock Origin

### Additional message
Not much to say. Generic filter breaks the disclaimer saying that there is no relationship between Disney and TTR, preventing you from browsing further.

**Comment by piorrro33** [comment]
Wouldn't making an exception for this website be more appropriate than removing the filter? There are probably other websites that depend on this filter to remove the adblocker warning, hence why it is there in the first place.

**Comment by bogachenko** [comment]
I think it will break other sites as well. I don't remember why I added it.
