### ISSUE TITLE
freemiumaccounts.net

### ISSUE THREAD

**Issue by animetrom** [bogachenko/fuckfuckadblock#90]
Please remove script BlockAdBlock.
Not work in site.

**Comment by bogachenko** [comment]
I'm not a telepath, what is the address of the problem site?

**Comment by bogachenko** [comment]
on which specific site does it not work?

**Comment by animetrom** [comment]
Sure.

The website: https://freemiumaccounts.net/

Print showing the error: https://prnt.sc/vq3uok

**Comment by bogachenko** [comment]
Please do not delete the markup with the issue next time, but fill it in. It was created for a reason, it will help save time for you and me. And by the way, you don't have to upload screenshots, I don't need them.

Have a nice day.
