### ISSUE TITLE
hqq.tv

### ISSUE THREAD

**Issue by dev1anceONE** [bogachenko/fuckfuckadblock#91]
### Basic information

**Check the link:** `https://hqq.to/player/embed_player.php?vid=210263224276212228234224232274257223194271217271255&autoplay=none&hash_from=82ef4948159e5d6000a526f066c9ec78`
**Category:** Anti-Adblock, Breakage
**Reported from:** Poland

### User environment

**Browser:** Google Chrome
**Extension or program:** uBlock Origin

### Additional message
When I play a movie (`https://cda-hd.cc/50344/mosul-2019-online`), the filter stops it, if it wants it to play on, it stops it again and again and again

**Comment by bogachenko** [comment]
I cannot reproduce

**Comment by bogachenko** [comment]
I cannot reproduce what you are saying. Can you record a video and send it to me?

**Comment by dev1anceONE** [comment]
Now it works, but when i uncheck Yours filterlist it work yesterday, today when i update some filters it works with Yours filterlist - so never mind. Maybe some filter was not updated(But i check it few times - Clear uBlock cache then update all filters), or fuckfuckadblock collide with the original ones from uBlock Origin, because yesterday i disabled all and check everyone. And as I mentioned, everything works, so some original uBlock filters had to collide. So sorry for Your lost time. Next time with such a problem, I will try to record a video with the selected list, of course if there is such a problem with Your list.
