### ISSUE TITLE
forum.release-apk.com

### ISSUE THREAD

**Issue by Rusenche** [bogachenko/fuckfuckadblock#93]
### Basic information

**Check the link:** `https://forum.release-apk.com/viewtopic.php?f=26&t=107119`
**Category:** Anti-adblock
**Reported from:** Bulgaria

### User environment

**Browser:** Centbrowser v.4.2.10.171 x86 portable
**Extension or program:** uBlock origin v.1.31.2

### Additional message

```
Our website shows online advertisements to our visitors to cover the cost of hosting.

Please, consider supporting us by deactivating our Web in your Ad Blocker. !!! How to disable AdBlock - > https://www.wikihow.com/Disable-AdBlock

DISABLE YOUR ADBLOCKER ON OUR WEB TO ENJOY THE CONTENT
1.- Press the adblocker icon.
2.- Select "Do not act on pages of this domain" (or similar).
You can also press the "Activated on this site" or "Pause adblocker" button.
3.- Press the "Refresh" button of your browser to see the content you want to view.
```

In short: They force us to turn off the ad blocker.

I use your filter: [https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt](https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt)

I enclose a photo.

[http://store.picbg.net/pubpic/D4/B3/8622aec7df32d4b3.png](http://store.picbg.net/pubpic/D4/B3/8622aec7df32d4b3.png)

**Comment by bogachenko** [comment]
I cannot reproduce with default settings, try this and write `||release-apk.com/ext/*/AntiAdblock/$script`

**Comment by Rusenche** [comment]
Thank you for your cooperation.

The problem turned out to be me. Here's what caused the problem: "forum.release-apk.com##[class].adsbygoogle" When I deleted it, everything was fine!
