### ISSUE TITLE
animetvn.tv

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#99]
### Basic information

**Check the link:** `https://animetvn.tv/xem-phim/f167324-vlad-lovetap-01.html`
**Category:** Popup and Anti-adblock

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Please fix.

**Comment by bogachenko** [comment]
@ryanbr Your rule blocks the mirror from the playhydrax.com player (triggers antiadblock), please add this rule `@@*$websocket,domain=redirect-ads.com` or this `@@||1ulebzhsv7.buzz^$domain=redirect-ads.com`

Also you too @alex-302

**Comment by krystian3w** [comment]
AdGuard base see any EasyList commit in 1 hour = so possible wait for fix in origin list.
